### ISSUE TITLE
Handle vuln_update notification post vulnerabilities refactor 

### ISSUE THREAD

**Issue by nightfurys** [anchore/anchore-engine#1002]
Vulnerabilities refactor PR https://github.com/anchore/anchore-engine/issues/1001 disabled the result diffing in the vuln_update notification path

https://github.com/anchore/anchore-engine/blob/41615e56aedb9fd06288418e25733330776d7cf9/anchore_engine/services/catalog/catalog_impl.py#L1605-L1610

Update this logic to use the new vulnerability report format from policy-engine and implement the diff

**Comment by Toure** [comment]
@nightfurys can I close this issue or should it be left open as a tracker?

**Comment by zhill** [comment]
This is no longer needed. Was resolved in v0.10.0

**Comment by nightfurys** [comment]
The issue was fixed in https://github.com/anchore/anchore-engine/commit/05463ce09740cbb6451603a521add3835b57cf95
