### ISSUE TITLE
Restore functionality of Hints as they were in 0.8.2

### ISSUE THREAD

**Issue by Toure** [anchore/anchore-engine#1006]
**Is this a request for help?**:
No.
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
Bug Report.

**Version of Anchore Engine and Anchore CLI if applicable**:
Anchore-Engine 0.9.3

**What happened**:
A regression was introduced within the time frame of 0.9.0, the hints functionality was inadvertently removed due to
code cleanup and introduction of new features.

**What did you expect to happen**:
The codebase which was removed is responsible for processing the hints for each of the supported packages, without this functionality, end users can not amend new details for a given package.

**What docker images are you using**:
anchore-engine:latest

**How to reproduce the issue**:
1. Deploy Anchore enterprise
2. Create a custom docker image with hints files embedded
3. Analyse the newly created docker image.
4. Check the status of the new image which will show a status of analysis failed.

**Comment by zhill** [comment]
Closed by #1008
