### ISSUE TITLE
Unable to find Config File /config/config.yaml

### ISSUE THREAD

**Issue by Akshatcobalt** [anchore/anchore-engine#103]
I created the following directory structure:-
/root/aevolume/config/config.yaml
/root/aevolume/db
/root/aevolume/docker-compose.yaml

When I'm running docker-compose up command as root user frominside aevolume directory I get the ERROR Unable to find Config File /config/config.yaml

**Comment by nurmi** [comment]
@Akshatcobalt - can you share your docker-compose.yaml snippet, in particular the section that describes the volume mounts for the anchore-engine service?

**Comment by Akshatcobalt** [comment]
Sure. Here it is:- 
version: '2'
services:
  anchore-engine:
    image: docker.io/anchore/anchore-engine:latest
    #privileged: true
    depends_on:
     - anchore-db
    ports:
     - "8228:8228"
     - "8338:8338"
    volumes:
     - /root/aevolume/config
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    environment:
     # NOTE: this should be set to the same name as this service (e.g. anchore-engine)
     - ANCHORE_HOST_ID=dockerhostid-anchore-engine
     - ANCHORE_ENDPOINT_HOSTNAME=anchore-engine
  anchore-db:
    image: "postgres:9"
    volumes:
     - /root/aevolume/db/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata/
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    #uncomment to expose a port to allow direct/external access to the DB, for debugging
    #ports:
    # - "2345:5432"

**Comment by nightfurys** [comment]
@Akshatcobalt, the volumes are not correctly mounted in your docker-compose

volumes for anchore-engine should be:
```
voumes:
- /root/aevolume/config:/config/:z
```
volumes for anchore-db should be:
```
voumes:
- /root/aevolume/db:/var/lib/postgresql/data/pgdata/:z
```

**Comment by nurmi** [comment]
This issue should be addressed by the information provided - please re-open ticket if there are other/related questions!
