### ISSUE TITLE
Add support for `grype version` command in grype-wrapper

### ISSUE THREAD

**Issue by Vijay-P** [anchore/anchore-engine#1036]
**Is this a request for help?**:

NO
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**:
N/A grype-integration branch

**What happened**:
Schema version of grype DB download should be keyed off of grype installation. (We should download the version that is supported by the installed grype version). This information can be retrieved from the `grype version` command. See linked discussion: https://github.com/anchore/anchore-engine/pull/1028#discussion_r632270861

**What did you expect to happen**:

`grype-wrapper` should have a method for calling `grype version` and serialize the response into a dataclass.

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by dspalmer99** [comment]
Done
