### ISSUE TITLE
Support Amazon Linux CVEs

### ISSUE THREAD

**Issue by josepplaltg** [anchore/anchore-engine#112]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**: version 0.2.4

 
**What happened**: We're using AmazonLinux as baseimage but seems Anchor-engine doesn't have this CVEs

**What did you expect to happen**:
To have the AmazonLinux CVEs due to the amount of users that are using this OS due to the optimizations is has for AWS.

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**: Scan any Amazon Linux based image.

**Anything else we need to know**:

**Comment by zhill** [comment]
@josepplaltg thanks for the feature request! Is this currently blocking your use of Anchore? We've got this on our radar for sure, but no ETA on adding support just yet. We'll keep this updated with progress and any questions.

**Comment by josepplaltg** [comment]
@zhill  AL1 would be nice, most of our current containers run AL1 because is the image we're currently running on our production instances(Puppet managed). The migration to AL2 is planned but it's not gonna happen during next months due to the work we've to do with the changes regarding Systemd adoption an other bit differences between AL1 and AL2.

**Comment by nurmi** [comment]
Adding a note here that anchore-engine 0.3.1 includes support for detecting vulnerabilities in amazon linux 2 based images - we'll leave the ticket open since there is an explicit request for amazon linux 1, but as AL 1 (vulnerability mapping) is not supported in anchore engine.

**Comment by nurmi** [comment]
We're going to close out this ticket as we have added AMZN linux 2 support (in anchore engine v0.3.1) - if there is a specific need (currently) for amzn 1, please open a new ticket for the feature request.
