### ISSUE TITLE
load_config.loadconfig should not set localconfig['default_bundle_file'] to None

### ISSUE THREAD

**Issue by fabian-braun** [anchore/anchore-engine#113]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**: v0.2.4

 
**What happened**: 
Catalog service failed to start with error message: 
```Exception: unable to initialize default user data - exception: coercing to Unicode: need string or buffer, NoneType found```

**What did you expect to happen**:

Successful start of catalog service.

**Any relevant log output from /var/log/anchore**:

```
[service:catalog] 2018-11-05 13:35:23+0000 [-] [bootstrap] [ERROR] cannot create/init/register service: catalog - exception: unable to initialize default user data - exception: coercing to Unicode: need string or buffer, NoneType found
[service:catalog] 2018-11-05 13:35:23+0000 [-] [bootstrap] [ERROR] cannot start service (see above for information)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_engine/services/common.py", line 362, in makeService
    rc = smodule.initializeService(sname, localconfig)
  File "/usr/lib/python2.7/site-packages/anchore_engine/services/catalog/__init__.py", line 109, in initializeService
    raise Exception ("unable to initialize default user data - exception: " + str(err))
Exception: unable to initialize default user data - exception: coercing to Unicode: need string or buffer, NoneType found
```

**What docker images are you using**:
docker.io/anchore/anchore-engine:v0.2.4
I'm using a Kubernetes setup with a config-map mounted to `/config` in the pod.

**How to reproduce the issue**:

First I thought this issue was due to the formatting of my yaml-config, but it turned out to be related to the anchore_default_bundle.json file which was missing in my config-map. After adding the file to my config map the error went away.
It is somehow related to the following code in `anchore_engine/configuration/localconfig.py`:
```    
    # copy the src installed files unless they already exist in the service dir conf
    for key, fname in [('default_bundle_file', 'anchore_default_bundle.json'),
                       ('anchore_scanner_analyzer_config_file', 'analyzer_config.yaml')]:
        try:
            default_file = os.path.join(localconfig['service_dir'], fname)
            localconfig[key] = default_file
            if not os.path.exists(default_file):
                src_file = os.path.join(resource_filename("anchore_engine", "conf/"), fname)
                if os.path.exists(src_file):
                    shutil.copy(src_file, default_file)
        except:
            localconfig[key] = None
```
I suspect that the localconfig['default_bundle_file'] was set to None by the last line of this snippet which then later on led to the above error message in `catalog/__init__.py`. However I was not able to analyze further because any exceptions are swallowed by the except block in above snippet. The volume I mount should have write-access so that cannot be the problem. 
However, I think `localconfig['default_bundle_file']` shouldn't be set to None here.

The final Exception is raised in the `initializeService` function because `os.path.exists` cannot be invoked with `None`.

**Comment by zhill** [comment]
@fabian-braun we'll take a look. Thanks for the report. Generally, the anchore_default_bundle.json is copied into the "service_dir" location (/config by default) from the installed anchore-engine and should not be required in the config map, but i suspect the way you're mounting the config map is mapping each key as a file. Is that correct? Normally, I'd recommend just setting the "service_dir" key in the config.yaml to a directory other than the default so that the writes go to another directory than /config. Our Helm chart does this to also remove the problem with read-only config map mounts. But the handling in this specific case could certainly be better and clearer.

**Comment by fabian-braun** [comment]
@zhill yes, correct, I have a config map with each key as a file. I understand your approach of letting `service_dir` point somewhere else inside the container filesystem. But now that I found out about all this, I'm actually happy that I can provide my own `anchore_default_bundle.json` in a config map.

Feel free to close this issue if it's too minor :)

**Comment by zhill** [comment]
@fabian-braun yes, it actually is a nice little feature to be able to provide the default. We'll keep this open as a way to track cleaning up that specific error path since a type issue should never surface to a user.
