### ISSUE TITLE
how to define my own policy rules?

### ISSUE THREAD

**Issue by wangpei-nice** [anchore/anchore-engine#1178]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
neither

**Version of Anchore Engine and Anchore CLI if applicable**:
version: 0.9.1

**What happened**:
To define my own policy by changing anchore_default_bundle.json, but  every container has the same json file in /anchore_service/bundles/, I don't know which one I should modify.
![image](https://user-images.githubusercontent.com/81410079/130452282-442a5897-bfe7-41a0-b4e7-1f39d74b080d.png)

**What did you expect to happen**:

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by dspalmer99** [comment]
@wangpei-nice You should use anchore-cli to manage your policy, rather than editing the policy file in the container directly,. See the documentation for doing so [here](https://github.com/anchore/anchore-engine/blob/master/docs/content/docs/usage/cli_usage/policies/_index.md#managing-policies).

**Comment by wangpei-nice** [comment]
> @wangpei-nice You should use anchore-cli to manage your policy, rather than editing the policy file in the container directly,. See the documentation for doing so [here](https://github.com/anchore/anchore-engine/blob/master/docs/content/docs/usage/cli_usage/policies/_index.md#managing-policies).

Thanks for your suggestion!
