### ISSUE TITLE
Update Click and SQLAlchemy dependencies to latest, as new major versions are available

### ISSUE THREAD

**Issue by nurmi** [anchore/anchore-engine#1204]
Ticket to track keeping up-to-date with some important underlying dependencies of anchore engine - namely Click (which has a different focused ticket at #908 noting a security fix in Click >= 8.0) and SQLAlchemy.  At present, plan is to upgrade Click to 8.0.1 and SQLAlchemy to 1.4.23 (latest at the time of creating this ticket).

**Comment by zhill** [comment]
Closed by #1205
