### ISSUE TITLE
Unable to add image

### ISSUE THREAD

**Issue by macedemo** [anchore/anchore-engine#122]
I followed the directions here but got this error when I tried to run the anchore-cli image add command

$ anchore-cli image add docker.io/library/alpine:latest
Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {u'raw_exception_message': u'could not get manifest/digest for image (docker.io/library/alpine:latest) from registry (https://index.docker.io) - error: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://docker.io/library/alpine:latest, rc=1, stdout=None, stderr=b\'time="2019-01-03T15:27:51Z" level=fatal msg="pinging docker registry returned: Get http://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.11:53: read udp 127.0.0.1:47137->127.0.0.11:53: i/o timeout" \\n\''}

the anchor-engine is up:
624fe064da39        anchore/anchore-engine:latest   "/docker-entrypoint.…"   2 hours ago         Up 2 hours (healthy)   0.0.0.0:8228->8228/tcp, 0.0.0.0:8338->8338/tcp   anchore_anchore-engine_1

**Comment by macedemo** [comment]
@zhill yes it is still occurring and thank you for moving this to the appropriate place. within the anchore-engine container? I just tried and ping is not existent so tried to install and got an error:


#apt install iputils-ping
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcap2-bin libidn11 libpam-cap
The following NEW packages will be installed:
  iputils-ping libcap2-bin libidn11 libpam-cap
0 upgraded, 4 newly installed, 0 to remove and 3 not upgraded.
Need to get 127 kB of archives.
After this operation, 489 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libidn11 amd64 1.33-2.1ubuntu1
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 iputils-ping amd64 3:20161105-1ubuntu2
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 libcap2-bin amd64 1:2.25-1.2
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpam-cap amd64 1:2.25-1.2
  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.1ubuntu1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/i/iputils/iputils-ping_20161105-1ubuntu2_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libc/libcap2/libcap2-bin_2.25-1.2_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libc/libcap2/libpam-cap_2.25-1.2_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

but a ping from the host seems to work fine to for archive.unbutu.com:
$ ping archive.unbutu.com
PING archive.unbutu.com (209.126.123.11) 56(84) bytes of data.
64 bytes from static-ip-209-126-123-11.inaddr.ip-pool.com (209.126.123.11): icmp_seq=1 ttl=128 time=36.6 ms
64 bytes from static-ip-209-126-123-11.inaddr.ip-pool.com (209.126.123.11): icmp_seq=2 ttl=128 time=35.9 ms
64 bytes from static-ip-209-126-123-11.inaddr.ip-pool.com (209.126.123.11): icmp_seq=3 ttl=128 time=37.6 ms


From the host it seems to resolve to an IP for  registry-1.docker.io but I don't get a response (not sure if the disabled echo requests): 

$ ping registry-1.docker.io
PING registry-1.docker.io (52.70.175.131) 56(84) bytes of data.

So it seems like my host can resolve but the container cannot. I so makes me think a configuration with docker so did this:
$ docker run -it ubuntu /bin/bash
root@e21ecec1d6f0:/# apt update
0% [Connecting to archive.ubuntu.com] [Connecting to security.ubuntu.com]

So I think I have a docker configuration issue WRT name resolution?

**Comment by nurmi** [comment]
thanks @macedemo for the update and description of the ultimate docker configuration / solution!
