### ISSUE TITLE
Anchore does not interpret OVAL definitions correctly for non-ksplice issues

### ISSUE THREAD

**Issue by navzen2000** [anchore/anchore-engine#1237]
**Is this a request for help?**:

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

**Version of Anchore Engine and Anchore CLI if applicable**:

Anchore currently reports issue against OEL8 which is a false postitive.

Issue reported by Anchore :ELSA-2021-9151
https://linux.oracle.com/errata/ELSA-2021-9151.html

RPM version inside docker image:
openssl-libs-1.1.1g-15.el8_3.x86_64

Oval Definition
https://linux.oracle.com/oval/com.oracle.elsa-20219151.xml

Inside docker image, ksplice is not enabled and as per oval definition, the rule needs to be processed if ksplice version is used

<criterion test_ref="oval:com.oracle.elsa:tst:20219151021" comment="Oracle Linux arch is x86_64"/>
<criteria operator="OR">
<criteria operator="AND">
<criterion test_ref="oval:com.oracle.elsa:tst:20219151003" comment="openssl is earlier than 2:1.1.1g-15.ksplice1.el8_3"/>
<criterion test_ref="oval:com.oracle.elsa:tst:20219151004" comment="openssl is signed with the Oracle Linux 8 key"/>
<criterion test_ref="oval:com.oracle.elsa:tst:20219151005" comment="openssl is ksplice-based"/>
</criteria>
<criteria operator="AND">
<criterion test_ref="oval:com.oracle.elsa:tst:20219151009" comment="openssl-devel is earlier than 2:1.1.1g-15.ksplice1.el8_3"/>
<criterion test_ref="oval:com.oracle.elsa:tst:20219151010" comment="openssl-devel is signed with the Oracle Linux 8 key"/>
<criterion test_ref="oval:com.oracle.elsa:tst:20219151011" comment="openssl-devel is ksplice-based"/>
</criteria>
<criteria operator="AND">
<criterion test_ref="oval:com.oracle.elsa:tst:20219151012" comment="openssl-libs is earlier than 2:1.1.1g-15.ksplice1.el8_3"/>
<criterion test_ref="oval:com.oracle.elsa:tst:20219151013" comment="openssl-libs is signed with the Oracle Linux 8 key"/>
<criterion test_ref="oval:com.oracle.elsa:tst:20219151014" comment="openssl-libs is ksplice-based"/>
</criteria>
<criteria operator="AND">
<criterion test_ref="oval:com.oracle.elsa:tst:20219151015" comment="openssl-perl is earlier than 2:1.1.1g-15.ksplice1.el8_3"/>
<criterion test_ref="oval:com.oracle.elsa:tst:20219151016" comment="openssl-perl is signed with the Oracle Linux 8 key"/>
<criterion test_ref="oval:com.oracle.elsa:tst:20219151017" comment="openssl-perl is ksplice-based"/>
</criteria>
</criteria>

Similar false positives are being reported for other rpms as anchore is not able to interpret oval rules for ksplice related issues correctly
**What did you expect to happen**:
If rpm is not ksplice based, then issue should not be reported.
OVAL definitions need to be processed correctly
Index of OVAL definitions
https://linux.oracle.com/oval/

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by zhill** [comment]
HI @navzen2000 , the current system does not execute OVAL checks directly against the container content because that would require re-pulling each image every time a vulnerability DB update is detected. It looks like this issue is that the OVAL contains constraints that are a regex match on the version string independently of the distro version and version "is less than" check. We'll take a look at this to see how these constraints can be processed without requiring container content itself for each evaluation.

Is it possible for ksplice-based rpms to be used in a container? I assume they are not expected since ksplice is for the kernel itself.

**Comment by RoxaBee** [comment]
the current system does not execute OVAL checks directly against the container content because that would require re-pulling each image every time a vulnerability DB update is detected.

**Comment by RoxaBee** [comment]
Is it possible for ksplice-based rpms to be used in a container? I assume they are not expected since ksplice is for the kernel itself.

Ksplice can be used to patch select user space packages (openssl and glibc). So you could run ksplice inside the container if it has Ksplice aware libraries inside and PTRACE is allowed inside the container.

**Comment by zhill** [comment]
Thanks @RoxaBee. Anchore generates a vulnerability database from the various sources that describe constraints that can be tested against a static SBoM. Anchore's "analysis" phase consumes the image content to create the SBoM and then we do vulnerability scans against that static content.

Is use of ksplice inside a container something you are doing or need to support? I'm asking so we can consider our solutions with your use-cases in mind. Thanks!

**Comment by RoxaBee** [comment]
Hi @zhill thanks for the additional context. We do not include Ksplice in our Oracle Linux container images. I think as long as you added a regex for Ksplice so images not running Ksplice wouldn’t get findings for Ksplice ELSAs that would address the issue.

**Comment by zhill** [comment]
Thanks @RoxaBee , that's the plan and it should be released in Engine 1.0 expected next week.

**Comment by navzen2000** [comment]
Hi @zhill
We upgraded to v1.0.0 but the false positive issue still persists.
We have used grype  as ANCHORE_VULNERABILITIES_PROVIDER in policy engine (docker-compose)

Anchore Issue reported: ELSA-2019-4852, ELSA-2021-9151 for openssl-libs-1:1.1.1g-15.el8_3

Within container:
rpm -qav|grep openssl
openssl-libs-1.1.1g-15.el8_3.x86_64

Note: Container does not have ksplice enabled.

**Comment by zhill** [comment]
Closing this as resolved with the 1.0 release. Please re-open if you see issues persist.

**Comment by navzen2000** [comment]
Re-opening as the issue re-surfaced again on 

Ksplice is not present in container
rpm packages installed

bash-4.4# rpm -qav|grep rpm
rpm-4.14.3-19.el8.x86_64
rpm-libs-4.14.3-19.el8.x86_64

Issue reported by Anchore

Vulnerability ID        Package                       Severity        Fix                        CVE Refs        Vulnerability URL                                          Type        Feed Group        Package Path
ELSA-2022-0368          rpm-4.14.3-19.el8             Medium          0:4.14.3-19.el8_5.2                        https://linux.oracle.com/errata/ELSA-2022-0368.html        rpm         ol:8              pkgdb
ELSA-2022-0368          rpm-libs-4.14.3-19.el8        Medium          0:4.14.3-19.el8_5.2                        https://linux.oracle.com/errata/ELSA-2022-0368.html        rpm         ol:8              pkgdb

Anchore version in docker compose: v1.0.1

**Comment by navzen2000** [comment]
@zhill
