### ISSUE TITLE
could not get image record from anchore

### ISSUE THREAD

**Issue by omerlh** [anchore/anchore-engine#14]
I followed the documentation on how to run anchore locally using docker-compose, and look like it is running. When I run:
```
./anchore-cli  --url http://localhost:8228/v1 --insecure --u admin --p foobar evaluate check ubuntu:latest 
```
It failed with the error above. I also run `system status` and look like everything is up:
```
Service catalog (http://localhost:8082): up
Service apiext (http://localhost:8228): up
Service analyzer (N/A): up
Service simplequeue (http://localhost:8083): up
Service kubernetes_webhook (http://localhost:8338): up
Service policy_engine (http://localhost:8087): up
```
And I also look at the logs, but could not find anything relevant there.

**Comment by acathrow** [comment]
Was the image already analyzed? (did you run anchore-cli image add ubuntu:tatest )

Running 'anchore-cli image list' will show the list of images analyzed by your anchore installation.

**Comment by omerlh** [comment]
Thanks, that was the issue.
