### ISSUE TITLE
Add Wildcard on Registries

### ISSUE THREAD

**Issue by gambol99** [anchore/anchore-engine#142]
**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Description**

We presently use quay.io for the vast majority of own public images, however we also have a number of vendor images also in quay.io which require authentication to docker pull. At present anchore doesn't support this setup as the credential is tried to the entire registry.

It would be nice to add multiple `anchore-cli registry add quay.io/{regex|path} <username> <password>` with unmatched entries falling through to default noauth. Another option would be to add auth to an image, but i'm guessing this would be a larger structural code change.

**Comment by zhill** [comment]
@gambol99 yes, this is currently an issue and we're considering a similar approach

**Comment by zhill** [comment]
Will be starting work on this shortly. One question is around overlapping strings/matches and how to pick which one to use: e.g. docker.io/library/* entry and docker.io/* entry. For a simple wildcard support it's easy, just pick the longest substr that matches (the most specific), but with regex it gets more complicated. For now, I'll implement simple wildcard/prefix matches as I think that addresses most of the use-cases without a larger change.

So, the "registry" value will be:
* Registry-only if no '/' in the value denoting a repo extension
* Exact match on registry/repo if no wild-card '*' found in str
* Prefix match on registry/repo if trailing '*' found.

Is there a use-case for a leading wildcard? I can't think of a case where you'd want to use the same cred on different registries but the same repo. Maybe AWS ECR? Still doesn't seem like it would make sense.

**Comment by zhill** [comment]
Closing, since completed in 41dada6 and released in 0.4.0 of Engine.
