### ISSUE TITLE
Auto-clean down/orphaned service records

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#145]
The system status API response includes all service records, even those that have exited the system (there is currently no clean exit), this can lead to a large number of down/orphaned service entries that impose load on the system's service checker over time and can also lead to significant load on the simplequeue service if the system is configured to send events to the webhook notifiers.

The default behavior of the helm chart is to use the pod id as the host_id, so k8s deployments with significant auto-scaling or churn will see this behavior.

Proposed solution is to provide a configurable service entry timeout value to will cause entries that have been down/orphaned for longer than the timeout to be auto-flushed and minimize impact as well as keep the service record list clean and useful. This could lead to unknown orphans in cases where a service actually is still running but unable to connect to update the service record but external orchestration systems and healthchecks can help mitigate such issues.

The configuration value will be an entry in the catalog service section since the catalog manages service state checks.

**Comment by erdarun** [comment]
I'm also facing the same issue

**Comment by zhill** [comment]
@erdarun the cli and api provide a way to remove service entries, you just have to do it one at a time.

`anchore-cli system status` to list services...

for each down/orphaned entry:
`anchore-cli system del <host_id> <servicename>`

**Comment by zhill** [comment]
A workaround to reduce system load due to this condition is to disable the events notification system.
In config.yaml:

```
...
services:
...
  catalog:
    event_log:
      notification:
        enabled: false
...
```

In the helm chart you can use:
```
anchoreCatalog:
  events:
    notification:
      enabled: false

```

**Comment by antimack** [comment]
+1 a really must-have improvement, we have spot-instances for our k8s clusters and the orphaned services list growing really fast

**Comment by jonny-wg2** [comment]
+2. Experienced this issue today!

I think I might run a script to detect this and auto clean this though. Really bummer though that this happens.

**Comment by jonny-wg2** [comment]
Maybe we can add something similar to

```

#! bin/bash
# script to fix https://github.com/anchore/anchore-engine/issues/145
anchore-cli system status > outputdata

# identify down (orphaned) services and delete them to restart them
# output of the script would be
# achore-cli system del anchore-engine-analyzer-75f56b58bb-49vqz analyzer
cat outputdata | grep "down (orphaned)" | while read line
do
    POD=`echo $line | cut -sd "(" -f2 | awk -F "," '{print $1}'`
    SERVICE=`echo $line | awk -F " " '{print $2}'`
    echo "achore-cli system del $POD $SERVICE"
done
```

**Comment by nurmi** [comment]
Hello @jonny-wg2 

A feature was added to anchore-engine (v0.4.0) to auto-remove orphaned service entries, which fires once per day.  A script such as the one you have outlined will also still work to manually remove the orphaned entries, but any service that has entered the 'orphaned' state will be cleared out by the system every 24 hours as well.  

Are you seeing orphaned services persisting longer than this time?  We can look into that (we would start by inspecting the catalog log files, looking for 'handle_service_watcher' log entries) as well!

Best
-Dan

**Comment by frittentheke** [comment]
@nurmi this auto-removal is great. But in case of a Kubernetes deployment of Anchore and potentially lots to pods being deleted or nodes rolled running this once a day is not enough.
I just ran into the issue of images not being scanned (as they were assigned to an Analyzer pods that does not exist anymore). 

Before finding this issue here, I though adjusting the image_analyze_timeout_seconds setting (https://github.com/helm/charts/issues/18580)  was the only approach.

Would you consider doing a more frequent service record cleanup and maybe even integrating a little more with Kubernetes events of Analyzer pods being re-scheduled?

**Comment by nurmi** [comment]
@frittentheke 

I'm not opposed to making the orphan cleanup timer configurable, that would be a great PR or separate ticket for the FR!

However, I wanted to be clear that there really shouldn't be any functional problem with orphaned services records existing in the system - anchore analyzers poll an active queue for work tasks (i.e tasks are not assigned to services, only services that are actually running will take jobs), for example.  Nothing in anchore will assign or even attempt to contact services that are in down or orphaned state, we only keep the records around for display purposes. 

Best
-Dan

**Comment by frittentheke** [comment]
@nurmi thank your for your very quick reply. 

Maybe this is a misconception on my side, but if an Analyzer goes away (becomes orphaned) the job it was doing (the image it was scanning) will not finish. But in the database the "job" remains assigned to the now gone Analyzer. I suppose this exactly what https://github.com/anchore/anchore-engine/issues/296 is about: The analyze not being rescheduled to a new Analyzer.

**Comment by nurmi** [comment]
Hi @frittentheke - 

Thanks for that clarification!  That is correct, and appreciate the filing of the separate issue #296 to discuss the graceful shutdown (to augment the existing configurable timeout) approach to improve the handling image analysis re-queue under these conditions.  I just wanted to make it clear here that the 'orphaned service' by itself (which can happen to any service) is just a display artifact in general (i.e. no functional problem with 'orphaned services' existing).  The side effect of an analyzer going down mid-analysis I think is at the core of it, and I think #296 is the right place to discuss improvements there.

Best
-Dan

**Comment by flickerfly** [comment]
Here's a one-liner to do the cleanup:
`anchore-cli system status | grep " down "  | tr -d "(" | tr -d "," |awk '{print "anchore-cli system del "$3" "$2}'`

Well, that builds the commands you can push to xargs or review the output and paste it back in the terminal.
