### ISSUE TITLE
Feature: Add optional policy parameter for vulnerabilities older than N days

### ISSUE THREAD

**Issue by emaildanwilson** [anchore/anchore-engine#149]
It would be great if I could add policy rules which WARN if vulnerabilities are found of a certain type and BLOCK if they have been discovered for longer than a certain number of days. Ideally for our use case this should be driven off of the actual CVE date or fix date but as long as updates run frequently the created date (which appears to be written to the db already) would work for now.

For example,

Trigger Name | Description | Parameter | Description | Example
-- | -- | -- | -- | --
package | Triggers if a found vulnerability in an image meets the comparison criteria. | days_past_creation | Matches when the vulnerability was reported more than the provided value of days ago. | 30

Then end users could define policies similar to...

```
{      
  "name": "CustomPolicy",
  "version": "1_0",
  "comment": "Policy for date based vulnerabilities",
  "id": "policy1", 
  "rules": [
      {
        "action": "STOP",
        "gate": "vulnerabilities",
        "id": "stophigh",
        "params": [
          { "name": "package_type", "value": "all" },
          { "name": "severity_comparison", "value": ">=" },
          { "name": "severity", "value": "high" },
          { "name": "days_past_creation", "value": 30}
        ],
        "trigger": "package"
      },
      {
        "action": "WARN",
        "gate": "vulnerabilities",
        "id": "warnhigh",
        "params": [
          { "name": "package_type", "value": "all" },
          { "name": "severity_comparison", "value": ">=" },
          { "name": "severity", "value": "high" }
        ],
        "trigger": "package"
      }
  ]
}
```

Is this something that makes sense as a feature for this project?
Is there a better approach to implementing a feature like this that is preferred?

**Comment by nurmi** [comment]
hi @emaildanwilson - 

I really like this idea, and to your question I believe that it does make sense as a new parameter feature for the existing vulnerability policy gate.  If this is something you would like to try to implement and contribute as a PR, we would be more than happy to help with any questions/clarifications!  Either way, I've marked the issue as an enhancement that we can track the progress of, here.

**Comment by emaildanwilson** [comment]
I'll attempt to get a PR put together for discussion over the next week or two.
