### ISSUE TITLE
"Analysis fail" - how can I know why?

### ISSUE THREAD

**Issue by omerlh** [anchore/anchore-engine#15]
I'm trying to analyze images, and the analysis failed. I'm suspecting networking issues, as I'm on an unstable network right now - but I would like to know for sure. By looking at the logs, I could not find any error that could explain why the analysis failed. Where else can I look? I'm running anchore using `docker-compose`.

**Comment by acathrow** [comment]
It's an area we need to work on and are planning on adding that to the results returned from the _image get_ command.
In the mean time we'd need to look at logs. Running docker logs can sometimes be noisy but if you look at the anchore-worker.log in /var/log/anchore you'll see more details.

By the way did the image add complete successfully ?

We have a community slack channel where we can help a little more interactively. You can email slack@anchore.com for an invitation. The next couple of days will be a little slow given the holidays but someone will be around

**Comment by omerlh** [comment]
Yes, the image add completed successfully. I'll take a look at this file, see what's going on.
Thanks!

**Comment by omerlh** [comment]
The folder `/var/log/anchore` does not exist...  Maybe I should enable debug logs?

**Comment by acathrow** [comment]
The logs will be inside the container running the engine.
If you run `docker ps` you'll see the two containers running.
Grab the id of the container running the engine and exec into it.
eg.
docker exec -it 0c142cf79843 bash

this will give you a bash shell on that engine container.
You'll find the logs in /var/log/anchore

**Comment by omerlh** [comment]
I used docker compose:
```
<>$ docker-compose run anchore-engine bash
Starting tmp_anchore-db_1 ... done
[root@270f48e1ae84 /]# ls -la /var/log
total 48
drwxr-xr-x 1 root root  4096 Dec 19 20:48 .
drwxr-xr-x 1 root root  4096 Dec 19 20:50 ..
drwxr-xr-x 2 root root  4096 Nov 28 16:08 anaconda
-rw------- 1 root utmp     0 Nov 28 16:07 btmp
-rw-r--r-- 1 root root     0 Dec  4 19:48 dpkg.log
-rw-r--r-- 1 root root   193 Nov 28 16:07 grubby_prune_debug
-rw-r--r-- 1 root root 23944 Nov 28 16:07 lastlog
drwxr-xr-x 2 root root  4096 Nov 28 16:08 rhsm
-rw------- 1 root root     0 Nov 28 16:07 tallylog
-rw-rw-r-- 1 root utmp     0 Nov 28 16:07 wtmp
-rw------- 1 root root  3361 Dec 19 20:48 yum.log
[root@270f48e1ae84 /]# 
```
And as you can see, no logs...

**Comment by acathrow** [comment]
Are you sure that isn't the DB container?

**Comment by omerlh** [comment]
Sorry, it was my mistake - I think it was running new container each time. Anyway, any log file (api, catalog, worker) contains only the following error: 
```
oci runtime error: exec failed: container_linux.go:265: starting container process caused "exec: \"car\": executable file not found in $PATH"
```
Do you think this is related

**Comment by acathrow** [comment]
So if you have the I'd of the container can you run.
docker exec -it 1234567880 bash

Where you replace 1234567890 with your container id

**Comment by omerlh** [comment]
Sorry, my mistake – not being clear enough. I’ve sent the errors  from the logs…

**Comment by acathrow** [comment]
Would it be possible to email me the log to andrewc@anchore.com
usually I'd say let's talk on our community slack but today and tomorrow will be harder than usual with the holiday break.

**Comment by nurmi** [comment]
Hi @omerlh 

The first thing I do when adding an image succeeds but analysis fails (i.e. the status of the image goes to 'analysis_failed') is to check the 'worker' logs, which is where analysis work happens.  Simplest way to do this is by looking at the 'anchore-worker.log' file in the anchore-engine container (mine is called 'anchore-engine_1', but you would substitute the container name/ID of the anchore-engine container in your environment):

```
$ docker-compose up -d
Starting anchore-db_1 ... 
Starting anchore-db_1 ... done
Starting anchore-engine_1 ... 
Starting anchore-engine_1 ... done
$ docker exec -t -i anchore-engine_1 cat /var/log/anchore/anchore-worker.log
```

and look for log messages that indicate a problem with the image you're seeing the analysis_failed status against - you should see it try to pull/download the image from registry, perform an anchore analysis on the image, then store the results back to the anchore-engine catalog/DB.

Best,
-Dan

**Comment by omerlh** [comment]
Found the issue, sorry for doing a very very stupid mistake. I was using the command `car` instead of `cat` to get the logs...
Anyway, here is the real issue I think, from `achore-worker.log`:
```
<>$ docker exec 3efcece1b674 cat /var/log/anchore/anchore-worker.log.1 | grep ERROR
2017-12-25 08:41:14+0000 [-] [Thread-22142] [anchore_engine.clients.localanchore_standalone/squash()] [ERROR] command failed with exception - command failed: cmd=tar -C /tmp/50db646a-8eab-4fcc-8d88-2b8cd5b673fd/rootfs -x -f /tmp/50db646a-8eab-4fcc-8d88-2b8cd5b673fd/squashed_tmp.tar exitcode=2 stdout= stderr=tar: etc/fonts/conf.d: Directory renamed before its status could be extracted
2017-12-25 08:41:15+0000 [-] [Thread-22142] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: failed to download, unpack, analyze, and generate image export - exception: command failed: cmd=tar -C /tmp/50db646a-8eab-4fcc-8d88-2b8cd5b673fd/rootfs -x -f /tmp/50db646a-8eab-4fcc-8d88-2b8cd5b673fd/squashed_tmp.tar exitcode=2 stdout= stderr=tar: etc/fonts/conf.d: Directory renamed before its status could be extracted
```
I'll sent it also via email - totaly understanding delay in response, it is only here in Israel that we work during Christma/new year :)

**Comment by acathrow** [comment]
Thanks for taking the time to dig in - we are working on improving this area of logging so soon that'll be easier.
As you can see tar seems to fail extracting one of the layers of the image archive.
I'm going to presume that your container host is either RHEL, CentOS or Oracle Linux and that you're using the overlay(2) filesystem - if that's not the case please let us know so we can dig in further.

There's a bug in the overlay filesystem kernel code that is fixed in 4.13 you can see the upstream moby (docker) issue here: https://github.com/moby/moby/issues/19647 It's not 100% reproducible and it will fail in different places/images.
This bug was fixed in 4.13 but not yet backported to the RHEL/CentOS 3.10 kernel tree.
Overlay2 is now the default in RHEL/CentOS however they do have some caveats listed in their release notes. Short of switching CentOS/RHEL to device mapper or moving to a different container host the only work around is to make sure that we are not using overlay2 storage as temp space for the image extraction. We're planning on adding this as an optional volume in the docker compose file but only came up with this idea right before the holiday break.
I'll do some testing this morning but IIRC you'd need to create a volume for that maps to /root/.anchore/anchoretmp inside the container.
I've got some family related activities early this morning but I'll make sure I test this today and I'll update the issue here.
Thanks for your patience.

**Comment by omerlh** [comment]
First - no rush :) Enjoy your time with your family, which is a lot more important than a random dude from GitHub...

I'm running this using docker-compose on mac - maybe this is the issue?

**Comment by acathrow** [comment]
Are you running the latest release, so you know what version?

**Comment by acathrow** [comment]
Thanks, I booted up a mac to check and indeed they use an older kernel too.
So I did the following
- edited config.yaml to add the following line in the top section:
tmp_dir: '/scratch'

added a new volume in my docker compose that mounts a scratch volume on the host to the container
eg
-/path/to/my/scratch/dir:/scratch

**Comment by omerlh** [comment]
Is `scratch volume` something special on mac? I couldn't find anything about it on google...

**Comment by acathrow** [comment]
No, just a term for temporary working area. Just create a directory for it.

**Comment by omerlh** [comment]
Thank you, look like this solved it. BTW the scan time is pretty long (~30 min), not something that can be used in CI, which require fast feedback. Is that something your aware to?

**Comment by acathrow** [comment]
That's an incredibly long time. What size image and what system were you running this one?
As part of the analysis we download the image layers, expand them and then checksum each files. This is an I/O intensive task however usually that time is measured in seconds or a minute or so for a very, very large file - I've not seen this level of time before.
If it makes sense to discuss more interactively on slack you can email slack@anchore.com or andrewc@anchore.com and I can get you on the community channel.
thanks.

**Comment by omerlh** [comment]
Sure, I'll send you a message. Thanks!

**Comment by abdulmujeeb** [comment]
> That's an incredibly long time. What size image and what system were you running this one?
> As part of the analysis we download the image layers, expand them and then checksum each files. This is an I/O intensive task however usually that time is measured in seconds or a minute or so for a very, very large file - I've not seen this level of time before.
> If it makes sense to discuss more interactively on slack you can email [slack@anchore.com](mailto:slack@anchore.com) or [andrewc@anchore.com](mailto:andrewc@anchore.com) and I can get you on the community channel.
> thanks.

Hello. 

I'm facing the same problem. I'm analyzing golang:1.11-alpine3.8 and it takes more than 30 minutes to scan. Did you find any solution?

I'm using Mac. I applied the fix suggested in this post by creating a '/scratch' directory, but the scan remains too slow. 

I know that this defect is closed. Asking here because my problem is very relevant to the last point made in this post.
