### ISSUE TITLE
Error response from policy service during bundle validation. Validation could not be performed: failed post url=http://demo1-anchore-engine-policy:8087/v1/validate_bundle HTTP Code: 500

### ISSUE THREAD

**Issue by amiagraw12** [anchore/anchore-engine#151]
**Is this a request for help?**:
Yes
---
I am trying to add new policy bundle from enchore-engine and getting below error. 
root@demo1-anchore-engine-api-74d8f8b5d5-tqn6z:/anchore_service_config# anchore-cli policy add anchore_bundle.json
Error: Error response from policy service during bundle validation. Validation could not be performed: failed post url=http://demo1-anchore-engine-policy:8087/v1/validate_bundle
HTTP Code: 500

Can you please help on this i am new in anchore.

**Comment by nurmi** [comment]
hi @amiagraw12 ,

That message is indicating that there is something in the bundle document that isn't conforming to the bundle format.  Some things that can help diagnose:

1) run the command with --debug and --json to get the most information from the server (e.g. anchore-cli --debug --json policy add ....)
2) if you could include your anchore_bundle.json as an attachment, we and others could help to verify format
3) check out the anchore policy hub (https://github.com/anchore/hub) for some examples of pre-packaged bundles that you can use as a baseline!

Let us know with a bit more information, and we can try to help

**Comment by amiagraw12** [comment]
Hi @nurmi 

I appreciate your quick response. 

Please find the command output as below:

root@demo1-anchore-engine-api-74d8f8b5d5-tqn6z:/anchore_service_config# anchore-cli --debug --json policy add anchore_bundle.json
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
DEBUG:anchorecli.clients.apiexternal:POST url=http://localhost:8228/policies?detail=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "POST /policies?detail=True HTTP/1.1" 500 225
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 500
{
    "detail": {},
    "httpcode": 500,
    "message": "Error response from policy service during bundle validation. Validation could not be performed: failed post url=http://demo1-anchore-engine-policy:8087/v1/validate_bundle"

looks like port 8087 is not exposed. if it is so can you please help where I need to expose it. 

Setup details:
C:\Users\xxxx>kubectl get pods
NAME                                                READY   STATUS    RESTARTS   AGE
anchorecli-59569989c-qqh2d                          1/1     Running   1          23d
bio-first-app-mongodb-85555667cb-xwgtn              1/1     Running   5          71d
demo1-anchore-engine-analyzer-684d778c44-lrfgx      1/1     Running   2          23d
demo1-anchore-engine-api-74d8f8b5d5-tqn6z           1/1     Running   1          23d
demo1-anchore-engine-catalog-5644fd4fdb-tswdr       1/1     Running   1          23d
demo1-anchore-engine-policy-65bf5d7fdd-7mxvp        1/1     Running   2          23d
demo1-anchore-engine-simplequeue-57859f5fcf-5wzcj   1/1     Running   1          23d
demo1-postgresql-74cf4cbdbc-g48cq                   1/1     Running   2          23d

I have attached policy bundle as below
[anchore-bundle.txt](https://github.com/anchore/anchore-engine/files/2917947/anchore-bundle.txt)

. will check anchore policy hub. 

Thanks 
Amit Agrawal

**Comment by zhill** [comment]
Found this issue in the code. It is a version problem in the bundle (version 1_1 instead of 1_0) and bad error handling for that specific condition. The version field is the schema version, not the version of the bundle content. It must always be 1_0 until a new version format is released for 1_1
