### ISSUE TITLE
Add namespace filter to vulnerability query:

### ISSUE THREAD

**Issue by nurmi** [anchore/anchore-engine#162]
Feature request to add the ability to specify a namespace for filtering results of queries made to v1/query/vulnerabilities route, similar to the namespace filter available in the v1/query/images/by_vulnerability route.  Specific ask follows:

It would be useful to be able to filter the results of a "GET /query/vulnerabilites>id=" on namespaces. Ideally this could support multiple values and wildcards so you can do something like 'nvd*,centos*' to only see Red Hat RHSAs and their mapped CVE data. If you happen to already know what you are looking for this makes it easier to scope your query to get just the data you need/want back.

**Comment by zhill** [comment]
Implemented without wildcards, just lists (e.g. namespace=debian:8,debian:9) in 6300f5faa0c94aea3d2d7ace7b0cfb0062dd92c1

**Comment by zhill** [comment]
Will create a new issue for wildcard support.

**Comment by zhill** [comment]
Added to milestone since already done for 0.5.1. Additional enhancement in #280 for future work.
