### ISSUE TITLE
Issue Adding Images

### ISSUE THREAD

**Issue by leetsg0** [anchore/anchore-engine#167]
Hello,

I've been having an issue with the anchore engine scanning a local image in my local registry.  I'm getting the following error.

Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {u'raw_exception_message': u'could not get manifest/digest for image (localhost:5000/textron:latest) from registry (https://localhost:5000) - error: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://localhost:5000/textron:latest, rc=1, stdout=None, stderr=b\'time="2019-03-28T16:28:14Z" level=fatal msg="pinging docker registry returned: Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused" \\n\''}

The image is not one that I created but one that has been provided to me.

Leets

**Comment by vennemp** [comment]
Just a heads up. I resolved this issue now by creating dns records in my private dns servers (Active Directory in this case). What is strange is that there were valid dns entries in a public dns zone (though A records were private IPs). Our admin is new to AWS and created the r53 zone as public. Curl to the private registry from anchore succeeded but the image add thru the skopeo error- same as above. 

Creating the private dns zone AD resolved this issue immediately. Any idea why??
