### ISSUE TITLE
Incorrect packages list on Debian & false positive

### ISSUE THREAD

**Issue by guedou** [anchore/anchore-engine#169]
# Previously reported at https://github.com/anchore/anchore/issues/63

**Version of Anchore Engine and Anchore CLI if applicable**:

latest docker images used with docker-compose
 
**What happened**:

anchore analyses apt packages that are not installed (flaged as "rc"), and can report them as vulnerable

**What did you expect to happen**:

anchore should not report vulnerabilities about uninstalled packages.

**How to reproduce the issue**:

Install an old Debian, install some vulnerable packages, remove them with "apt-get remove".

**Anything else we need to know**:

I wll suggest that you also retrieve ${Status} variables and filter out packages marked as "deinstall".

**Comment by nurmi** [comment]
Thank you @guedou !  We've reviewed and agree with your assessment - apt-get remove doesn't always result in a record remaining in the current dpkg listing that the anchore analyzer runs, but it does if (for example) the package contains a config file that is left behind after the remove (resulting in the 'rc' state).  We'll make progress on updating the analyzer to include the status field and take it into account when storing the package manifest for dpkg-based images, and will update this ticket on progress!

**Comment by guedou** [comment]
Thanks!
