### ISSUE TITLE
Issue feeds sync

### ISSUE THREAD

**Issue by jymun** [anchore/anchore-engine#170]
HI, I got an error during feeds sync.
What should I do?
<pre><code>
# curl -v -H 'x-anchore-password: pbiU2RYZ2XrmYQ' https://ancho.re/v1/account/users/anon@ancho.re

* About to connect() to ancho.re port 443 (#0)
*   Trying 104.28.12.5...
* Connected to ancho.re (104.28.12.5) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=sni189579.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
*       start date: Mar 30 00:00:00 2019 GMT
*       expire date: Oct 06 23:59:59 2019 GMT
*       common name: sni189579.cloudflaressl.com
*       issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /v1/account/users/anon@ancho.re HTTP/1.1
> User-Agent: curl/7.29.0
> Host: ancho.re
> Accept: */*
> x-anchore-password: pbiU2RYZ2XrmYQ
>
< HTTP/1.1 403 Forbidden
< Date: Wed, 10 Apr 2019 05:20:50 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d35dd8b81efa5f8eecb8bf654606deab61554873649; expires=Thu, 09-Apr-20 05:20:49 GMT; path=/; domain=.ancho.re; HttpOnly
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 4c5246173ec9ae93-KIX
<
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host ancho.re left intact

</code></pre>

**Comment by jymun** [comment]
# curl --verbose -H 'x-anchore-password: pbiU2RYZ2XrmYQ' https://ancho.re/v1/account/users/anon@ancho.re
* About to connect() to ancho.re port 443 (#0)
*   Trying 104.28.13.5...
* Connected to ancho.re (104.28.13.5) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=sni189579.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
*       start date: Mar 30 00:00:00 2019 GMT
*       expire date: Oct 06 23:59:59 2019 GMT
*       common name: sni189579.cloudflaressl.com
*       issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /v1/account/users/anon@ancho.re HTTP/1.1
> User-Agent: curl/7.29.0
> Host: ancho.re
> Accept: */*
> x-anchore-password: pbiU2RYZ2XrmYQ
>
< HTTP/1.1 403 Forbidden
< Date: Wed, 10 Apr 2019 05:10:48 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=da8390ecc086bdfa2db62245fb68ede711554873048; expires=Thu, 09-Apr-20 05:10:48 GMT; path=/; domain=.ancho.re; HttpOnly
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 4c5237679f38aeb1-KIX
<
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

**Comment by nurmi** [comment]
hi @jymun 

Can you please try a feed sync again?  We've updated some of our site settings which may have been responsible for the 403 responses you were seeing.

**Comment by jymun** [comment]
Thanks. 200 code is output.
