### ISSUE TITLE
[question] Why is the /status endpoint protected by Basis Auth ?

### ISSUE THREAD

**Issue by henrikjohansen** [anchore/anchore-engine#172]
Is there a specific reason as to why the `/status` endpoint is protected by Basic Auth? There seems to be no sensitive information in that data ? I'd really like to use this for healthchecking of my Anchore deployment but I am not keen on having to distribute a username/password for that ... 

Without Basic Auth :
```
$ curl http://x.x.x.x:8228/v1/status
Unauthorized
```

With Basic Auth :
```
$ url --user admin:foobar http://x.x.x.x:8228/v1/status
{
  "available": true,
  "busy": false,
  "db_version": "0.0.9",
  "detail": {},
  "message": "all good",
  "up": true,
  "version": "0.3.4"
}
```

**Comment by zhill** [comment]
@henrikjohansen there are other healthcheck routes: /health and /version both are unauthenticated, and /health returns an empty 200 and is intended for load balancers and other health checks.

**Comment by henrikjohansen** [comment]
Thanks - that solves my immediate issue.
