### ISSUE TITLE
Red Hat vs. CentOS false positives

### ISSUE THREAD

**Issue by MichaelW-SD** [anchore/anchore-engine#177]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**: 0.3.3

 
**What happened**:
A scan of a CentOS based image shows vulnerabilities and provides versions that fix the problems. Those versions are already installed in the image. It seems that anchore is not recognizing CentOS version numbers.

$ anchore-cli image vuln image all
Vulnerability ID        Package                           Severity        Fix                             Vulnerability URL                                      
RHSA-2019:0679      libssh2-1.4.3-12.el7         High             0:1.4.3-12.el7_6.2      https://access.redhat.com/errata/RHSA-2019:0679        

Anchore reports that libssh2 has a vulnerabilities and that the Red Hat version 0:1.4.3-12.el7_6.2 fixes the problem. Installed is this version:

$ rpm -q libssh2
    libssh2-1.4.3-12.el7.x86_64 

The versions are identical except for the Red Hat postfix "_6.2" that CentOS does not include in its versions.

**What did you expect to happen**:
Correct identification of CentOS version numbers and no reported vulnerability.

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:
anchore/anchore-engine:latest

**How to reproduce the issue**:
Scan a recent CentOS based image that has libssh2 installed (other packages have the same problem like systemd, systemd-libs, openssl-libs)

**Anything else we need to know**:

**Comment by nurmi** [comment]
Hi @MichaelW-SD 

We're not quite seeing the same condition that you describe currently, but wanted to run by what we're seeing.  What I'm seeing currently is demonstrated with the below procedure, which shows that there are packages available in centos that correspond to the versions indicated in the result from anchore:

```
# docker run -t -i centos:latest /bin/bash
[root@11407c78fde8 /]# yum info libssh2
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirrors.usc.edu
 * extras: repos.lax.quadranet.com
 * updates: centos.mirror.ndchost.com
base                                                                                                                                                                                                                                    | 3.6 kB  00:00:00     
extras                                                                                                                                                                                                                                  | 3.4 kB  00:00:00     
updates                                                                                                                                                                                                                                 | 3.4 kB  00:00:00     
(1/4): base/7/x86_64/group_gz                                                                                                                                                                                                           | 166 kB  00:00:00     
(2/4): extras/7/x86_64/primary_db                                                                                                                                                                                                       | 188 kB  00:00:00     
(3/4): base/7/x86_64/primary_db                                                                                                                                                                                                         | 6.0 MB  00:00:01     
(4/4): updates/7/x86_64/primary_db                                                                                                                                                                                                      | 3.4 MB  00:00:01     
Installed Packages
Name        : libssh2
Arch        : x86_64
Version     : 1.4.3
Release     : 12.el7
Size        : 334 k
Repo        : installed
From repo   : CentOS
Summary     : A library implementing the SSH2 protocol
URL         : http://www.libssh2.org/
License     : BSD
Description : libssh2 is a library implementing the SSH2 protocol as defined by
            : Internet Drafts: SECSH-TRANS(22), SECSH-USERAUTH(25),
            : SECSH-CONNECTION(23), SECSH-ARCH(20), SECSH-FILEXFER(06)*,
            : SECSH-DHGEX(04), and SECSH-NUMBERS(10).

Available Packages
Name        : libssh2
Arch        : i686
Version     : 1.4.3
Release     : 12.el7_6.2
Size        : 134 k
Repo        : updates/7/x86_64
Summary     : A library implementing the SSH2 protocol
URL         : http://www.libssh2.org/
License     : BSD
Description : libssh2 is a library implementing the SSH2 protocol as defined by
            : Internet Drafts: SECSH-TRANS(22), SECSH-USERAUTH(25),
            : SECSH-CONNECTION(23), SECSH-ARCH(20), SECSH-FILEXFER(06)*,
            : SECSH-DHGEX(04), and SECSH-NUMBERS(10).

Name        : libssh2
Arch        : x86_64
Version     : 1.4.3
Release     : 12.el7_6.2
Size        : 135 k
Repo        : updates/7/x86_64
Summary     : A library implementing the SSH2 protocol
URL         : http://www.libssh2.org/
License     : BSD
Description : libssh2 is a library implementing the SSH2 protocol as defined by
            : Internet Drafts: SECSH-TRANS(22), SECSH-USERAUTH(25),
            : SECSH-CONNECTION(23), SECSH-ARCH(20), SECSH-FILEXFER(06)*,
            : SECSH-DHGEX(04), and SECSH-NUMBERS(10).

#
```

After updating those packages with 'yum update' and analyzing the updated centos+yumupdates image, anchore is no longer matching those vulnerabilities.

Let us know if this helps to clarify, we're happy to discuss/look closer if you are finding that something isn't lining up in the way you expect.

**Comment by MichaelW-SD** [comment]
Thanks for the quick response. You pointed me in the right direction. Our image is not using yum for package management and did not correctly resolve all dependencies.
This was not anchore related at all.
