### ISSUE TITLE
Feature Request: Set a timeout for whitelisted Vulnerabilities.

### ISSUE THREAD

**Issue by dfederlein** [anchore/anchore-engine#178]
**Is this a request for help?**:

No.

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

Feature request for the ability to set an expiration date for whitelists in custom policies. This way one'd be able to “mute” an alert on a policy, and revisit it again at a later date. The use case would be that a security exception should have an end date (ie: release of patch) and while there may be a whitelist needed for short term reasons, the ability to go through another exception request once the expiration date of the whitelist action has occurred would be greatly helpful.

**Comment by zhill** [comment]
Closed by ca613ec0d33be115557cd54f21adff090cfe109b
