### ISSUE TITLE
Iterator over accounts is used as a list

### ISSUE THREAD

**Issue by mattpag** [anchore/anchore-engine#190]
Since `IdentityManager.list_accounts()` uses `filter()`, the return value of the function is an iterator.

In places like like https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/catalog/__init__.py#L969, where the engine may loops over the accounts multiple times, it ends up executing code for every account only once then skipping it entirely whenever the iterator is used in the rest of the function.

**Comment by zhill** [comment]
Yes, this is a bug, the return should be a list. I've not assessed its actual impact so see if it is ever used more than once.
