### ISSUE TITLE
analysis_failed for an image in ECR after taking time to analyze.

### ISSUE THREAD

**Issue by ethicalmohit** [anchore/anchore-engine#194]
**BUG REPORT**:

```
Analysis Status: analysis_failed
Image Type: docker
Image ID: 972829967e989c2b5759942269d650dcfc93ed5fa2ed7663da0ed89449559f20
Dockerfile Mode: Actual
Distro: None
Distro Version: None
Size: None
Architecture: None
Layer Count: None
```

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.4.0
 
**What happened**:
I have added an ecr registry with authentication keys and afterwards, I have added an image it was added successfully while checking vuln it gives analysis failed.

```
anchore-cli --u admin --p foobar --url http://localhost:8228/v1 image vuln <account-id>.dkr.ecr.us-east-1.amazonaws.com/repo:latest all
Error: image is not analyzed - analysis_status: analysis_failed
HTTP Code: 404
Detail: {u'error_codes': []}
```

**What did you expect to happen**:
The image should be analyzed completed and I must be able to see the vulnerabilities after the analysis is completed.

**Any relevant log output from /var/log/anchore**:

***Commands:***
```
anchore-cli --u admin --p foobar --url http://localhost:8228/v1 registry add <account-id>.dkr.ecr.us-east-1.amazonaws.com <access-key> <access-key> --registry-type=awsecr
anchore-cli --u admin --p foobar --url http://localhost:8228/v1 image add <account-id>.dkr.ecr.us-east-1.amazonaws.com/repo:latest --dockerfile=Dockerfile
```

**What docker images are you using**:
The base image which was based on python:slim.

**Comment by nurmi** [comment]
hi @ethicalmohit - thank you for the report!

Anchore moves images through states that start when an image is first 'add'ed to the engine - 'not_analyzed', 'analyzing', and finally 'analyzed' or 'analysis_failed'.  If you see an image that has reached the 'analysis_failed' state, it typically means that there was an issue during the image analysis process itself, which happens in the worker service.  Determining the reason why this has happened is a troubleshooting activity, and anchore supports a couple of different information sources that can help you to get more information about what has happened!

A good resource is located on our docs site, using the troubleshooting guide:

https://docs.anchore.com/current/docs/troubleshooting/

Starting there, and getting event/log information should get you more information that can be used to either resolve, or if you find information but need help interpreting, then please bring some of that info back to this ticket and we can help diagnose!

**Comment by ethicalmohit** [comment]
@nurmi Thanks for your reply. I have checked the system status and verified that all of the services were up and running. However, in event details, I can see that the policy engine service was down at the moment when I have added the image. 

How can i re-initiate scan on that image now?

**Comment by nurmi** [comment]
@ethicalmohit - you can initiate a rescan of any image that is in the ‘analysis_failed’ state by running the same ‘anchore-cli image add’ as was used to initially add the image.
