### ISSUE TITLE
Unable to sync feed after first feed download

### ISSUE THREAD

**Issue by ankitdas156** [anchore/anchore-engine#197]
**Is this a request for help?**:

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

**Version of Anchore Engine and Anchore CLI if applicable**:

 
**What happened**:

**What did you expect to happen**:

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by ankitdas156** [comment]
This is a request for help. 
I am able to see the initial feeds that got downloaded during my first run. But after few days when I am trying to sync the feeds, I am getting an empty array.
         
The last feed that got synced was about 2 months ago and I am unable to sync it now.
I am using anchore-cli for this.
_anchore-cli system feeds list
Feed                   Group                  LastSync                          RecordCount        
vulnerabilities        alpine:3.3             2019-02-28T15:00:19.203779        457                
vulnerabilities        alpine:3.4             2019-02-28T15:00:38.863192        681                
vulnerabilities        alpine:3.5             2019-02-28T14:59:59.124783        875                
vulnerabilities        alpine:3.6             2019-02-28T14:59:56.158890        918                
vulnerabilities        alpine:3.7             2019-02-28T14:59:57.529965        919                
vulnerabilities        alpine:3.8             2019-02-28T15:00:30.381093        996                
vulnerabilities        amzn:2                 2019-02-28T15:00:37.640084        135                
vulnerabilities        centos:5               2019-02-28T15:00:06.192750        1323               
vulnerabilities        centos:6               2019-02-28T15:00:07.576775        1320               
vulnerabilities        centos:7               2019-02-28T15:00:09.198086        754                
vulnerabilities        debian:10              2019-02-28T15:00:23.377323        19688              
vulnerabilities        debian:7               2019-02-28T15:00:24.622082        20455              
vulnerabilities        debian:8               2019-02-28T15:00:28.928234        21192              
vulnerabilities        debian:9               2019-02-28T15:00:26.028341        19913              
vulnerabilities        debian:unstable        2019-02-28T15:00:27.612658        20442              
vulnerabilities        ol:5                   2019-02-28T14:59:52.535893        1228               
vulnerabilities        ol:6                   2019-02-28T14:59:53.800864        1385               
vulnerabilities        ol:7                   2019-02-28T14:59:54.920334        854                
vulnerabilities        ubuntu:12.04           2019-02-28T15:00:03.205937        14946              
vulnerabilities        ubuntu:12.10           2019-02-28T15:00:04.693347        5652               
vulnerabilities        ubuntu:13.04           2019-02-28T15:00:10.919710        4127               
vulnerabilities        ubuntu:14.04           2019-02-28T15:00:12.505458        17929              
vulnerabilities        ubuntu:14.10           2019-02-28T15:00:13.965565        4456               
vulnerabilities        ubuntu:15.04           2019-02-28T15:00:16.148477        5748               
vulnerabilities        ubuntu:15.10           2019-02-28T15:00:17.523267        6511               
vulnerabilities        ubuntu:16.04           2019-02-28T15:00:31.583246        14908              
vulnerabilities        ubuntu:16.10           2019-02-28T15:00:00.542281        8647               
vulnerabilities        ubuntu:17.04           2019-02-28T15:00:01.802264        9157               
vulnerabilities        ubuntu:17.10           2019-02-28T15:00:33.325810        7935               
vulnerabilities        ubuntu:18.04           2019-02-28T15:00:34.578590        9160               
vulnerabilities        ubuntu:18.10           2019-02-28T15:00:36.054174        7247 _

While trying to sync the feeds, I am getting the following
anchore-cli system feeds sync

WARNING: This operation should not normally need to be performed except when the anchore-engine operator is certain that it is required - the operation will take a long time (hours) to complete, and there may be an impact on anchore-engine performance during the re-sync/flush.

**Really perform a manual feed data sync/flush? (y/N)y
 [ ]**

I am sure, I am making some mistake here. But unable to find what and where.

**Comment by zhill** [comment]
hi @ankitdas156 there is a known issue (#198)  the latest anchore release in the response for the feed sync API call that returns a 500 when it should return a 200 because the sync was actually successful. That is likely what you're seeing. The empty array is a consequence of that issue. If you do a listing of the feeds you should see updated timestamps indicating success.

**Comment by zhill** [comment]
Closing since no updates and the issue has been resolved in code with the fix for #198
