### ISSUE TITLE
Error: could not access anchore service

### ISSUE THREAD

**Issue by s-rohil** [anchore/anchore-engine#2]
I am getting the following error:

` anchore-cli image list`
`Error: could not access anchore service`

I did:
`export ANCHORE_CLI_URL=http://localhost:8228/` and also created a new environment variable for username and password (different from the one present in my config.yaml under "anchoreio>anchorecli>auth")

Also, i do not have root privileges, so i have created aevolume and anchore-cli under $HOME

**Comment by zhill** [comment]
HI @s-rohil! For the url, you'll need to set it to _http://localhost:8228/v1/_. Did you update the user and pass in the config.yaml to reflect your new values in your environment? The config.yaml determines the admin credentials so you can change them but what you use in your environment and in the config must match. You can use the '--debug' flag just after 'anchore-cli' to get more detailed output about what is wrong as well.

Are you running anchore-engine with the containers we provide on dockerhub or running it directly from source?

**Comment by s-rohil** [comment]
i am currently running containers provided on docker hub. I am configuring using docker-compose. i have also registered on navigator and entered those credentials as well in the config.yaml

this is what i get now:
`anchore-cli --debug image list`

`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): anchore.io
DEBUG:urllib3.connectionpool:https://anchore.io:443 "GET / HTTP/1.1" 200 None
INFO:anchorecli.clients.apiexternal:Base = https://anchore.io
INFO:anchorecli.clients.apiexternal:Url = https://anchore.io/images
DEBUG:anchorecli.clients.apiexternal:GET url=https://anchore.io/images
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): anchore.io
DEBUG:urllib3.connectionpool:https://anchore.io:443 "GET /images HTTP/1.1" 404 None
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 404`

**Comment by s-rohil** [comment]
On running the same command again:

`anchore-cli --debug image list`
`DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
Error: could not access anchore service (user=username url=http://localhost:8228/v1/): HTTPConnectionPool(host='localhost', port=8228): Max retries exceeded with url: /v1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d167ed0>: Failed to establish a new connection: [Errno 61] Connection refused',))`

**Comment by zhill** [comment]
Can you give the output of 'docker ps' and 'docker-compose ps'? The other thing to check is the output of the anchore-engine container to ensure that it is running properly and the services inside it are available. Check the logs of the engine container using 'docker logs <containername>' and verify that the service came up and is working properly. You should see steady checks and updates in the logs. If not, then something prevented the processes from starting properly or they have crashed. The error's you're seeing indicate that nothing is listening on the ports so I suspect either the port is different than the default, it isn't getting mapped on the local host correctly, or the container is not starting properly (perhaps can't connect to db fully).

If you run the docker compose up without daemon mode you can also confirm that startup is completing successfully as the logs will stream to stdout.

**Comment by s-rohil** [comment]
quick question before i send the outputs.. 
do i need to start a postgres instance by downloading the package from brew or does the postgres instance start on its own with the configs given in the config.yaml?

**Comment by s-rohil** [comment]
`docker ps`
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                            NAMES
6b8ed6db49b4        anchore/anchore-engine:latest   "/bin/sh -c /usr/b..."   4 seconds ago       Up 3 seconds        0.0.0.0:8228->8228/tcp, 0.0.0.0:8338->8338/tcp   db_anchore-engine_1
`docker-compose ps`
       Name                      Command               State                        Ports                      
--------------------------------------------------------------------------------------------------------------
db_anchore-db_1       docker-entrypoint.sh postgres    Exit 1                                                  
db_anchore-engine_1   /bin/sh -c /usr/bin/anchor ...   Up       0.0.0.0:8228->8228/tcp, 0.0.0.0:8338->8338/tcp `


OUTPUT OF LOGS:
` docker logs "ID"`
"could not connect to db, retrying in 10 seconds - exception: could not create/re-create DB tables - exception: (pg8000.core.InterfaceError) ('communication error', gaierror(-2, 'Name or service not known'))"
"could not connect to db, retrying in 10 seconds - exception: could not create/re-create DB tables - exception: (pg8000.core.InterfaceError) ('communication error', gaierror(-2, 'Name or service not known'))"
"could not connect to db, retrying in 10 seconds - exception: could not create/re-create DB tables - exception: (pg8000.core.InterfaceError) ('communication error', gaierror(-2, 'Name or service not known'))"

**Comment by s-rohil** [comment]
the docker-compose.yaml file has its PGDATA environment variable set to /var/lib/postgresql/data/pgdata/ but i have set my PGDATA to $HOME/homebrew/var/postgres/ . 
I have made the change in docker-compose.yaml but the same error as above persist.

note: I do not have admin privilege. so, i had a separate homebrew installation folder.

**Comment by nurmi** [comment]
hi s-rohil,

it looks like youre postgres container is failing to start when you run docker-compose up - you mentioned that you changed PGDATA, but keep in mind that the value set there is local to the container filesystem (not the outer host filesystem), so the default should be fine.  to change where that directory is located on your host, you would instead alter the ‘volumes’ configuration for the postgres instance:

/root/aevolume/db/:/var/lib/postgresql/data/pgata:Z

you would change ‘/root/aevolume/db/‘ to your desired location (that line maps the first path before the colon on the host fs to the second path inside the postgres container)

if everything lines up, then ‘docker compose up -d’ will pull and start both the postgres and anchore-engine containers.

in summary, to run using the default configs, but with a location for config and db storage not in /root, you should only need to adjust lines in docker-compose.yaml that start with /root to instead point to another location that you have rw access to.

**Comment by zhill** [comment]
@s-rohil, the docker-compose config will start a postgres container, so you don't need to install postgres locally via homebrew, or at all. Just create a directory for the data to go in and, as @nurmi said, specify that in the docker-compose.yaml. You can test just the postgres part using:
`docker-compose up anchore-db` and it will run only the postgres container with output to the screen so you can verify it works. Example:
```
ZACHs-MacBook-Pro-3:docker-compose zhill$ docker-compose up anchore-db
Creating network "dockercompose_default" with the default driver
Creating dockercompose_anchore-db_1 ...
Creating dockercompose_anchore-db_1 ... done
Attaching to dockercompose_anchore-db_1
anchore-db_1      | LOG:  database system was shut down at 2017-10-14 00:14:06 UTC
anchore-db_1      | LOG:  MultiXact member wraparound protections are now enabled
anchore-db_1      | LOG:  autovacuum launcher started
anchore-db_1      | LOG:  database system is ready to accept connections
```

Hit Ctl-C to stop the container. Once that is coming up and looks correct you can use `docker-compose up -d` to start the anchore-engine service as well. You can view the logs with `docker-compose logs --follow`.

**Comment by s-rohil** [comment]
Running with the default configs now.

`docker images`


REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
postgres                 latest              b106d5a0dc75        3 days ago          287MB
anchore/anchore-engine   latest              e0b8b72be9f9        4 days ago          376MB


`docker-compose up -d`
Creating db_anchore-db_1 ... 
Creating db_anchore-db_1 ... done
Creating db_anchore-engine_1 ... 
Creating db_anchore-engine_1 ... done


`docker ps`

CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                            NAMES
0ea00391350b        anchore/anchore-engine:latest   "/bin/sh -c /usr/b..."   4 seconds ago       Up 3 seconds        0.0.0.0:8228->8228/tcp, 0.0.0.0:8338->8338/tcp   db_anchore-engine_1

`docker-compose ps`

       Name                      Command               State                        Ports                      
--------------------------------------------------------------------------------------------------------------
db_anchore-db_1       docker-entrypoint.sh postgres    Exit 1                                                  
db_anchore-engine_1   /bin/sh -c /usr/bin/anchor ...   Up       0.0.0.0:8228->8228/tcp, 0.0.0.0:8338->8338/tcp 


`docker-compose images`

     Container              Repository          Tag       Image Id      Size  
-----------------------------------------------------------------------------
db_anchore-db_1       postgres                 latest   b106d5a0dc75   274 MB 
db_anchore-engine_1   anchore/anchore-engine   latest   e0b8b72be9f9   358 MB 


`docker-compose up anchore-db`

`Starting db_anchore-db_1 ... 
Starting db_anchore-db_1 ... done
Attaching to db_anchore-db_1
anchore-db_1      | The files belonging to this database system will be owned by user "postgres".
anchore-db_1      | This user must also own the server process.
anchore-db_1      | 
anchore-db_1      | The database cluster will be initialized with locale "en_US.utf8".
anchore-db_1      | The default database encoding has accordingly been set to "UTF8".
anchore-db_1      | The default text search configuration will be set to "english".
anchore-db_1      | 
anchore-db_1      | Data page checksums are disabled.
anchore-db_1      | 
anchore-db_1      | initdb: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
anchore-db_1      | If you want to create a new database system, either remove or empty
anchore-db_1      | the directory "/var/lib/postgresql/data/pgdata" or run initdb
anchore-db_1      | with an argument other than "/var/lib/postgresql/data/pgdata".
db_anchore-db_1 exited with code 1`

**Comment by s-rohil** [comment]
any updates would be helpful

**Comment by acathrow** [comment]
Rohil,
Would you be able to join our community slack channel so we can talk in
real time and help out
If you email slack@anchore.com then we can send you a slack invitation.





On Tue, Oct 17, 2017 at 9:44 AM, Rohil Subramanian <notifications@github.com

**Comment by acathrow** [comment]
cleared the docker-compose file from the db directory running correctly now.

**Comment by sivamad** [comment]
Hi, i have a external postgres, i have change the postgres DB in config.yaml and updated DB password in  docker-compose.yaml
am getting below error.[bootstrap] [WARNING] no webhooks defined in configuration file - notifications will be disabled
[service:catalog] 2018-03-06 17:46:13+0000 [-] [bootstrap] [INFO] initializing database
"could not connect to db, retrying in 10 seconds - exception: could not create/re-create DB tables - exception: (pg8000.core.InterfaceError) ('communication error', gaierror(-2, 'Name or service not known'))"

**Comment by sivamad** [comment]
Hi ,
1. Postgress is up running.. its in AWS.
2. Its running on same port and username is "anchore_user" same was defined in config.yaml
3. DNS name for DB ?? yes its resolving.
4. no network ACLs in place.

**Comment by jeffgrunewald** [comment]
I am also experiencing this issue:
1. Postgres is running v 9.6.6 in RDS
2. Running the helm chart and deploying to EKS
3. I am able to exec into the running core _and_ worker pods and manually connect to the database via psql with the correct username, password, port, and RDS endpoint URL being fed to the helm chart, so ACLs/security groups are not a factor.

I receive the exact same error message causing the worker pod to continually fail to connect to the DB with "exception: test connection failed - exception: (pg8000.core.InterfaceError) ('communication error', gaierror(-2, 'Name or service not known'))"

**Comment by cjmakwana** [comment]
Hello,

For a demo setup I want to use Anchore for container vulnerability testing. However, I am not able to run the Anchore CLI with the error: 

DEBUG:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
Error: could not access anchore service (user=admin url=http://localhost:8228/v1/): HTTPConnectionPool(host='localhost', port=8228): Max retries exceeded with url: /v1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585bcc61f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Please note that I am able to browse the APIs, however:

http://localhost:8228/v1
http://localhost:8228/v1/images/list

Though I don't find any image, at least I can run the API service successfully.

Kindly let me know if I am missing anything.
