### ISSUE TITLE
Feature Request: Add a flag to disable metrics endpoint authentication

### ISSUE THREAD

**Issue by pgdagenais** [anchore/anchore-engine#206]
Hello all,

We have been using Anchore for some time on kubernetes and we wanted to activate the metrics endpoint on all of the anchore service. But currently the `/metrics` endpoint needs to be scraped with basic auth.

Using the provided example on the anchore blog: https://anchore.com/operational-awareness-and-performance-tuning-for-anchore-part-1-architecture-and-metrics/

I added the scrape-config to my prometheus configuration. All of the pods gets correctly scraped but the analyzer. The problem is that the given configuration scrape statics target (kubernetes services resource) and the analyzer doesn't have a one.

What I would like to use is the prometheus `kubernetes-pods` scrape configuration https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod which needs only 3 annotations added to the deployment/pod.

```YAML
prometheus.io/scrape: "true"
prometheus.io/path: "/metrics"
prometheus.io/port: "8084"
```
This is currently not possible to do because you cannot configure the basic auth configuration and use the prometheus annotations to scrape the pods.

What I would to be added to the anchore-engine is a flag that disable the basic authentication on the `/metrics` endpoint.

**Comment by zhill** [comment]
thanks @pgdagenais
