### ISSUE TITLE
no metrics exposed

### ISSUE THREAD

**Issue by armstrongli** [anchore/anchore-engine#21]
Anchore engine doesn't have any metrics exposed. It means that it's hard to know
* whether the service is running or not
* what's the performance of components(serve core rest APIs, do image scan on image size, etc.)

**Comment by zhill** [comment]
There are a few checks that exist already that address some of these requirements.

Assuming the api service is running on port 8228:
_host:8228/health_ is a health check ping that returns 200 if the api service is running and responding. It does not hit the DB so should be performant independently of db load.

_host:8228/v1/system/status_ reports an overall system status of the services in the system. If a specific service is down or unresponsive the status is updated. The raw json output also indicates queue lengths for task queues.

Aside from a API metrics, here are some initial thoughts:

Rates of work:
* What is the work queue average wait time (time before an analysis is started)
* Images queued
* Images analyzed
* Images analyses failed
* What is the average analysis throughput for the worker pool (GB/s of image analyzed)
* Image download throughput per worker (Mbps)
* Tag updates checked per hour (perhaps 15 or 30 minute windows are better) (may want to group by registry and repository to isolate performance upstream)
* Policy evaluations processed over the last time interval (1, 5, 15, 30 minutes?)

Resource totals:
* Image total count
* Unique tags count
* Repositories count
* Registries count

These would probably be exposed as Prometheus metrics via an HTTP endpoint.

This is something we are planning to do. Will update this issue with progress.

**Comment by nurmi** [comment]
anchore-engine 0.2.X exposes prometheus metrics for a variety of system events and behaviors.  A good starting point is to look at the docker-compose example that is provided https://github.com/anchore/anchore-engine/tree/master/scripts/docker-compose/ where metrics are enabled in 'config.yaml', and the docker-compose.yaml has a section that can be uncommented for running the prometheus aggregator (along with an example anchore-prometheus.yaml configuration file example).

The metrics gathered include system-level resources (DB test r/w/rw, disk space in anchore-engine workspace volumes, histograms of response times for most API routes), anchore-engine internal resources (queue lengths, catalog monitor process runtimes, policy evaluation timings), and analysis timings (successful image analysis timings, failed image analysis timings).  This is in addition to the regular prometheus python metrics (file descriptiors, process CPU/memory probes, versions, etc).
