### ISSUE TITLE
policy add should only import full policy bundles 

### ISSUE THREAD

**Issue by acathrow** [anchore/anchore-engine#22]
User downloaded policy item from anchore.io and added to engine through the cli (policy add)

The policy item only had the policy check no mappings etc.
This should not import but instead return an error.

**Comment by zhill** [comment]
Was it an incomplete bundle, or just a policy object itself?

**Comment by acathrow** [comment]
policy object only.

**Comment by nurmi** [comment]
The reason this is happening is that the current bundle schema is only requiring fields that are also present in an individual policy document - solution will be to either add more requirements, or add exclusions to the schema (where any field that is *not* part of a valid bundle would trigger the schema check to fail).
