### ISSUE TITLE
Add Vulnerability feed for Alpine 3.10

### ISSUE THREAD

**Issue by okirmis** [anchore/anchore-engine#230]
**Is this a request for help?**:
No

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**:
 * anchore-cli, version 0.4.1
 * Name: anchore-engine, Version: 0.4.1, [...]

**What happened**:
Alpine 3.10 has been released. Using it as an base image leads to the following message when scanning with anchore: `Feed data unavailable, cannot perform CVE scan for distro: alpine:3.10.0`. That is correct when I check the feed status using `anchore-cli system feeds list`.

**What did you expect to happen**:
The vulnerability database from https://github.com/alpinelinux/alpine-secdb?tree/master/v3.10 is available in the feed list so the Alpine 3.10 images can be scanned properly.

**Any relevant log output from /var/log/anchore**:
No.

**What docker images are you using**:
`alpine:3.10`

**How to reproduce the issue**:
```
> anchore-cli image add alpine:3.10
> anchore-cli image wait alpine:3.10 --timeout 300
> anchore-cli evaluate check alpine:3.10 --detail
```

**Anything else we need to know**:
I don't think so.

**Comment by zhill** [comment]
Vulnerability data should be updated automatically once it is available in the alpine secdb. I have confirmed that it is not present in the anchore feeds but is present in the alpinesedb.

**Comment by okirmis** [comment]
@zhill So ideally I don't have to do anything to fix this except for waiting?

**Comment by okirmis** [comment]
The feed has appeared in the feed list now. However, it seems suspicious, that alpine 3.1 and alpine 3.10 have excactly the same amount of records in the database. Checking it in the database directly makes that even more suspicious:

```sql
postgres=# select id, severity, link, metadata_json, cvss2_vectors, cvss2_score from feed_data_vulnerabilities where namespace_name = 'alpine:3.10' EXCEPT (select id, severity, link, metadata_json, cvss2_vectors, cvss2_score from feed_data_vulnerabilities where namespace_name = 'alpine:3.1');
 id | severity | link | metadata_json | cvss2_vectors | cvss2_score
----+----------+------+---------------+---------------+-------------
(0 rows)
postgres=# select id, severity, link, metadata_json, cvss2_vectors, cvss2_score from feed_data_vulnerabilities where namespace_name = 'alpine:3.1' EXCEPT (select id, severity, link, metadata_json, cvss2_vectors, cvss2_score from feed_data_vulnerabilities where namespace_name = 'alpine:3.10');
 id | severity | link | metadata_json | cvss2_vectors | cvss2_score
----+----------+------+---------------+---------------+-------------
(0 rows)
```

**Therefore, the list of vulnerabilities for 3.1 and 3.10 seems to be exactly the same.** Comparing any other two versions of alpine (e.g. 3.1 to 3.9 or 3.9 to 3.10) gives a non-empty result (as one would expect). 

Maybe somewhere in the whole process of processing alpines database, 3.1 and 3.10 are handled as the same version (e.g. float compare of 3.1 and 3.10) or something like that.

**Comment by Pablo-CC** [comment]
This is funny... I don't think alpine:3.1 feeds exists at all!

https://github.com/alpinelinux/alpine-secdb?tree/master

I think what it looks like alpine3.1 in Anchore is in fact alpine3.10.

**Comment by okirmis** [comment]
@Pablo-CC Good point! :)
For completeness, the output of `anchore-cli system feeds list` contains:
```
vulnerabilities        alpine:3.1             2019-07-12T08:56:11.273043        1370
vulnerabilities        alpine:3.10            2019-07-12T08:56:19.251510        1370
```

**Comment by zhill** [comment]
tl;dr; The feed service is fixed and your installations will properly, and automatically, sync the 3.10 data. No rescans or updates to your systems are needed.

Detail:
As you can see from those outputs, we've fixed the feed service side to properly present the 3.10 vulnerabilities from Alpine's secdb. The original bug caused the 3.10 to be presented to clients as 3.1. There is no 3.1 release section of the alpine secdb repo, it starts at 3.3, so those 3.1 items you see are actually the 3.10 data. Now that 3.10 is available you should see matching for those distro images automatically--no rescans necessary for those images you've already analyzed.

For the 3.1 data, you can ignore/delete that data. We'll be adding a command in the service API and CLI to flush feed data in the next release so my recommendation is to wait for that before removing that data from your db. We'll be removing the 3.1 data from the service side, so it will no longer sync there and won't be present in new installs/syncs.

**Comment by okirmis** [comment]
So in my opinion, this issue is resolved and can therefore be closed. If I missed something, it should be reopened, of course.
