### ISSUE TITLE
Feature Request: Add the ability to save a user inputted name with a registry

### ISSUE THREAD

**Issue by KnoxAnderson** [anchore/anchore-engine#232]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
Feature Request

We often add credentials for multiple registries with very similar paths to the anchore engine.

Ie multiple gcr.io registries or registries that have long IP addresses and aren't easily identifiable. 

We'd like the ability to add a user inputted name to easily split this out ie 

GCR Dev
GCR Staging
Openshift Staging, etc

**Comment by nurmi** [comment]
Thanks @KnoxAnderson - this is a good enhancement and we can discuss a bit more here.  I'd make the following proposal:

- Name should be length limited to something short (32?) characters
- Storing the name is an optional parameter when adding a registry credential (POST), and is also supported with update (PUT)
- If the name is not set on add, then the registry name itself is used (copied) as the name
- The new name is added to the response registry credential record, and displayed in (anchore-cli) alongside the existing fields)

questions for discussion:

- Can the new 'name' be used as an identifier for API calls, in addition to the (existing) 'registry' as the primary ID?  In my opinion the answer should be 'no', as our API design largely relies on the use of unique resource identifiers (that cannot be updated) in the API/resource model whenever possible
    - if so - names must be unique, so more checking needs to be done when use is adding or updating a registry record (currently, 'registry' is the primary id and is not updatable, so the check only needs to happen on add for uniqueness)

**Comment by zhill** [comment]
Closing since released in v0.5.0. Further updates can be in a new FR or bug/issue as needed.
