### ISSUE TITLE
Unable to add image from private registry to anchore-engine

### ISSUE THREAD

**Issue by dforouhari** [anchore/anchore-engine#241]
**Is this a request for help?**:
Yes.
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT (possibly)

**Version of Anchore Engine and Anchore CLI if applicable**:
I run anchor-cli via enginer-api container, i.e., 
$ /usr/local/bin/docker-compose exec engine-api anchore-cli --version
**anchore-cli, version 0.4.1**

$ docker exec aevolume_engine-api_1 sh -c "pip show anchore-engine"
**sh: pip: command not found**, **BUT** see below
$ docker-compose exec engine-api anchore-cli system status
Service policy_engine (anchore-quickstart, http://engine-policy-engine:8228): up
Service analyzer (anchore-quickstart, http://engine-analyzer:8228): up
Service simplequeue (anchore-quickstart, http://engine-simpleq:8228): up
Service catalog (anchore-quickstart, http://engine-catalog:8228): up
Service apiext (anchore-quickstart, http://engine-api:8228): up

Engine DB Version: 0.0.10
**Engine Code Version: 0.4.1**

Some more info of interest: 
$ cat /etc/system-release
**CentOS Linux release 7.4.1708 (Core)**

$ docker --version
**Docker version 18.03.0-ce, build 0520e24**

$ docker-compose --version
**docker-compose version 1.24.1, build 4667896b**

$ docker-compose ps
             Name                            Command                  State               Ports
--------------------------------------------------------------------------------------------------------
aevolume_anchore-db_1             docker-entrypoint.sh postgres    Up             5432/tcp
aevolume_engine-analyzer_1        /docker-entrypoint.sh anch ...   Up (healthy)   8228/tcp
aevolume_engine-api_1             /docker-entrypoint.sh anch ...   Up (healthy)   0.0.0.0:8228->8228/tcp
aevolume_engine-catalog_1         /docker-entrypoint.sh anch ...   Up (healthy)   8228/tcp
aevolume_engine-policy-engine_1   /docker-entrypoint.sh anch ...   Up (healthy)   8228/tcp
aevolume_engine-simpleq_1         /docker-entrypoint.sh anch ...   Up (healthy)   8228/tcp

$ docker container ls
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                 PORTS                    NAMES
c83191c1c432        registry:2                      "/entrypoint.sh /etc…"   2 days ago          Up 2 days              0.0.0.0:5000->5000/tcp   registry
e904ee43b996        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   2 days ago          Up 3 hours (healthy)   8228/tcp                 aevolume_engine-analyzer_1
65d63530da57        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   2 days ago          Up 3 hours (healthy)   8228/tcp                 aevolume_engine-policy-engine_1
c5ccae40540f        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   2 days ago          Up 3 hours (healthy)   8228/tcp                 aevolume_engine-simpleq_1
a3b9c35206f7        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   2 days ago          Up 3 hours (healthy)   0.0.0.0:8228->8228/tcp   aevolume_engine-api_1
9da4b63d9623        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   2 days ago          Up 3 hours (healthy)   8228/tcp                 aevolume_engine-catalog_1
74e47293a9c7        postgres:9                      "docker-entrypoint.s…"   2 days ago          Up 3 hours             5432/tcp                 aevolume_anchore-db_1

(More diagnostic info at the bottom)

**What happened**:
 I followed the instructions: https://anchore.freshdesk.com/support/solutions/articles/36000098085-enterprise-quickstart  (perhaps i should had used some other installation document. If this is cause of problems, pls point me to the right document)
Per the document, I was able to do **steps 1-4 successfully.**
The problem started when I tried to execute step 5 and add a private img into anchore-engine for analysis. Needless to say, I had to create a private registry (only being accessed from the same machine) and ran a few other commands before trying to add the image from my registry into anchor, when trying to add a an image I get the following debug/info/error msgs on stdout/err:
====== /usr/local/bin/docker-compose exec engine-api anchore-cli --debug --json --insecure image add localhost.localdomain:5000/my_first_image:latest
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:POST url=http://localhost:8228/images?autosubscribe=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "POST /images?autosubscribe=True HTTP/1.1" 400 640
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 400
{
    "detail": {
        "error_codes": [
            "REGISTRY_NOT_ACCESSIBLE"
        ],
        "raw_exception_message": "Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=                    false --creds \"${SKOPUSER}\":\"${SKOPPASS}\" docker://localhost.localdomain:5000/my_first_image:latest, rc=1, stdout=None,                     stderr=b'time=\"2019-07-26T02:01:12Z\" level=fatal msg=\"pinging docker registry returned: Get http://localhost.localdomain:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused\" \\n', **error_code=REGISTRY_NOT_ACCESSIBLE"**
    },
    **"httpcode": 400,
    "message": "cannot fetch image digest/manifest from registry"**
}

**Please see the bottom of this positing for more diagnostic info**

**What did you expect to happen**:
I was hoping that the image would be loaded into anchore-engine for analysis.

**Any relevant log output from /var/log/anchore**:
No. For some reason there is no such a log file.

**What docker images are you using**:
a simple (shell script) docker image

**How to reproduce the issue**:
Install  docker & docker-compose on CentOS 7
Create a simple docker image (hello world) using 'docker build ...'
Create local/private registry...
Follow steps/instructions 1-5 in the mentioned Quickstart document. Step 5 should not succeed.

**Anything else we need to know**:
I used option --insecure for all the relevant commands.

Below is the output of various related commands. Hope it helps:
====== sudo cat /etc/docker/daemon.json
{
        "insecure-registries" : [
                                 "localhost.localdomain:5000",
                                 "127.0.0.1:5000",
                                 "localhost:5000"
                                ]
}

======= docker ps | grep registry
c83191c1c432        registry:2       "/entrypoint.sh ..."   2 days ago    Up 2 days     0.0.0.0:5000->5000/tcp   registry

====== docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
e4bfbb50cdb2        aevolume_default    bridge              local
38ceba37b687        bridge              bridge              local
be52774de52e        host                host                local
5f7f165864dd        none                null                local

====== /usr/local/bin/docker-compose exec engine-api anchore-cli --debug registry get
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/registries/localhost.localdomain%3A5000
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /registries/localhost.localdomain%3A5000 HTTP/1.1" 200 265
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
Registry: localhost.localdomain:5000
User: MY_ID
Type: docker_v2
Verify TLS: False
Created: 2019-07-24T23:43:18Z
Updated: 2019-07-24T23:43:18Z

====== /usr/local/bin/docker-compose exec engine-api anchore-cli --debug registry list
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/registries
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /registries HTTP/1.1" 200 265
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
Registry                          Type             User
localhost.localdomain:5000        docker_v2        MY_ID

====== /usr/local/bin/docker-compose exec engine-api anchore-cli --debug --json --insecure image list
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
INFO:anchorecli.clients.apiexternal:Base = http://localhost:8228
INFO:anchorecli.clients.apiexternal:Url = http://localhost:8228/images
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/images
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /images HTTP/1.1" 200 3
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[]

===== curl localhost.localdomain:5000/v2/_catalog
{"repositories":["my_first_image","myfirstimage"]}

====== /usr/local/bin/docker-compose exec engine-api anchore-cli --debug --json --insecure image add localhost.localdomain:5000/my_first_image:latest
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:POST url=http://localhost:8228/images?autosubscribe=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "POST /images?autosubscribe=True HTTP/1.1" 400 640
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 400
{
    "detail": {
        "error_codes": [
            "REGISTRY_NOT_ACCESSIBLE"
        ],
        "raw_exception_message": "Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false --creds \"${SKOPUSER}\":\"${SKOPPASS}\" docker://localhost.localdomain:5000/my_first_image:latest, rc=1, stdout=None, stderr=b'time=\"2019-07-26T02:19:10Z\" level=fatal msg=\"pinging docker registry returned: Get http://localhost.localdomain:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused\" \\n', error_code=REGISTRY_NOT_ACCESSIBLE"
    },
    "httpcode": 400,
    "message": "cannot fetch image digest/manifest from registry"
}

**Comment by blang9238** [comment]
Hi @dforouhari,

There seem to be a couple things that could be going on here.

The Anchore Engine runs a client from within it’s container (engine-api) to access specified images or registries.  Because it’s operating from within the container, ‘localhost’ will point to the container itself and since the registry isn’t running in the same container, nothing bound to port 5000 resulting in ‘connection refused’.

There are a few ways that you can work around this.

- You could set up your registry so that can be accessed by clients on your network with it’s own stable IP/hostname.
- Connect your Docker services (both the engine-api and registry) together using Docker’s networking.

Keep in mind, Anchore Engine expects registries to have TLS/SSL enabled; the --insecure flag tells it to ignore self-signed certificates or certificates signed by untrusted CAs.

For local only testing, it might be convenient to add your registry to the docker-compose file for Anchore’s services.  Once you create the cert and key for your registry, you could add something like the following to your ~/aevolume/docker-compose.yaml and relaunch with `docker-compose up -d`

```yaml
  registry:
    image: "registry:latest"
    ports:
    - 5000:5000
    restart: always
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.cert.pem
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key.pem
    volumes:
    - registry-volume:/var/lib/registry
    - ./certs:/certs
```

You should then be able to successfully add your image using the --insecure flag:

```bash
$ docker-compose exec engine-api anchore-cli --debug --json --insecure image add registry:5000/registry:5000
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:POST url=http://localhost:8228/images?autosubscribe=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "POST /images?autosubscribe=True HTTP/1.1" 200 2283
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[
    {
        "analysis_status": "analyzed",
        "analyzed_at": "2019-07-29T23:17:20Z",
        "annotations": {},
        "created_at": "2019-07-29T23:17:09Z",
        "imageDigest": "sha256:b1165286043f2745f45ea637873d61939bff6d9a59f76539d6228abf79f87774",
        "image_content": {
            "metadata": {
                "arch": "amd64",
                "distro": "alpine",
                "distro_version": "3.8.4",
                "dockerfile_mode": "Guessed",
                "image_size": 27289600,
                "layer_count": 5
            }
        },
[...]
```

**Comment by dforouhari** [comment]
@blang9238 ,
Thank you very much for spending time addressing my problem. I'll give it a try at the earliest available time and will update the this tkt accordingly.

Best regards,
dforouhari

**Comment by blang9238** [comment]
@dforouhari,

Not a problem.  Feel free to reach back out with questions here or via our community Slack channel [here](https://anchore.com/slack).

Also, here's a link to some relevant [docs](https://docs.anchore.com/current/docs/engine/usage/cli_usage/registries/configuring_registries/#adding-a-registry) about adding a registry.

**Comment by dforouhari** [comment]
@blang9238
Hi Ben.
A brief update & couple of questions:
Sorry for being dense, but I just want to mk sure I do the (minimum) required set up to get this done.
Question:
With regard to your advice, i.e.
**_There are a few ways that you can work around this.

You could set up your registry so that can be accessed by clients on your network with it’s own stable IP/hostname.

Connect your Docker services (both the engine-api and registry) together using Docker’s networking._**

Does it mean that I can address/solve my issue with doing **either** of the two mentioned steps?
If this is the case, I had already done the 'Connect your Docker services....', i.e.
docker network connect aevolume_default registry
(See my original comment, whereby I listed the output of 'docker network ls').

So, it seems that I still need to create a cert for the registry and do what you have suggested. Correct?

Finally,  FYI i never restart docker service after doing all the mentioned steps in my original comment.  I  don't think it should matter. Pls correct me if i am wrong.

Thanks for your support.

**Comment by blang9238** [comment]
@dforouhari 
Correct that either can resolve your issue, however the common factor is that the Anchore Engine client (anchore-cli) won't be able to resolve localhost.localdomain for your registry.  In both approaches, the registry needs to be accessed by some other name.  In the example I posted using docker-compose, the network created by compose up refers to the registry as 'registry' so any container in that network can access it by 'registry:5000'.  

If you’re using the aevolume_default network you would have to manually add your separate registry container to that network:

```bash
$ docker run -d -p 5000:5000 -v ~/aevolume/certs:/certs --name registry docker.io/registry:latest
 
$ docker network connect aevolume_default registry

$ docker tag registry:5000/registry:latest docker.io/registry:latest

$ docker push registry:5000/registry:latest

$ docker-compose exec engine-api anchore-cli --debug --json --insecure image add registry:5000/registry:latest
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:POST url=http://localhost:8228/images?autosubscribe=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "POST /images?autosubscribe=True HTTP/1.1" 200 2275
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[
    {
        "analysis_status": "analyzed",
        "analyzed_at": "2019-07-30T19:33:12Z",
        "annotations": {},
        "created_at": "2019-07-30T19:32:57Z",
        "imageDigest": "sha256:b1165286043f2745f45ea637873d61939bff6d9a59f76539d6228abf79f87774",
        "image_content": {
            "metadata": {
                "arch": "amd64",
                "distro": "alpine",
                "distro_version": "3.8.4",
                "dockerfile_mode": "Guessed",
                "image_size": 27289600,
                "layer_count": 5
            }
        },
[...]
```

You will still have to create certs and mount them to make the registry TLS/SSL enabled.

Finally, you shouldn’t need to restart the docker service, and you shouldn’t even need to restart the aevolume compose stack, just add your standalone registry to the aevolume_default network and reference your registry with the name that corresponds with the name in the aevolume_default network:

```bash
$ docker network inspect aevolume_default
[
    {
        "Name": "aevolume_default",
        "Id": "b0dedc533930f8b95f77c119ada2431c7cbd3859345599375f6e409fddbf3bc4",
        "Created": "2019-07-30T15:30:28.517383413-04:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Containers": {
            "39538b40921d73396de116e6b4244a21534e3909e1503d01120d152051c9a36f": {
                "Name": "registry",
                "EndpointID": "0faf43118e075eaac672523adbac7eee3704aa5a8a2f4a04e972d6baa321f4ef",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
[...]
```

Does that help clarify?

**Comment by dforouhari** [comment]
@blang9238,
Thanks again for taking time  and providing detailed information.

1. It seems to me that the root of the problem has to the cert stuff (or lack of) for the registry, when I as i didn't hv certs setup, when I ran the following command previously:
   $ docker run -d -p 5000:5000  --name registry docker.io/registry:2
instead of
   $ docker run -d -p 5000:5000 -v **~/aevolume/certs:/certs** --name registry docker.io/registry:latest

(As a note, I had executed all the commands that you have listed previously).   

2. FYI, here is the output of 'docker network inspect ...' for my system: Note 'registry' in the container section:
]$ docker network inspect aevolume_default
[
    {
        "Name": "aevolume_default",
        "Id": "e4bfbb50cdb202cc75cee7d559a50426cd6d0c9bb8b253ce59ba3aefd8ee7250"                                    ,
        "Created": "2019-07-23T13:07:59.331069552-07:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "65d63530da577cda35457cbb52e4291ea9dfcbe0dbb05bb6bf56ddfd6431eee5":                                     {
                "Name": "aevolume_engine-policy-engine_1",
                "EndpointID": "3935db7a634a5804246f61135c98778829607b338feea4dda                                    49641a546083179",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "74e47293a9c79f7f14e99389fc307bc4ad73c633b5c7213765ab13e6598bbfcd":                                     {
                "Name": "aevolume_anchore-db_1",
                "EndpointID": "8fd6f9469b1e3bead5c9b26913257e09590b1bff34b991aa2                                    58588ed0a5c418b",
                "MacAddress": "02:42:ac:12:00:07",
                "IPv4Address": "172.18.0.7/16",
                "IPv6Address": ""
            },
            "9da4b63d96234cbfeedc6e838f5f44f9c73fd168d42c5d6f2589522a2eb2a45e":                                     {
                "Name": "aevolume_engine-catalog_1",
                "EndpointID": "5ecf20b89f121884ac48122bb85f727ff7cd235640faad7f9                                    75b57e4607b6537",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "a3b9c35206f730bd7f45d843a0ec0502481801677dc7e926844cde4d97654666":                                     {
                "Name": "aevolume_engine-api_1",
                "EndpointID": "3d6dfae8ebc1aca9a883af418fa178be6fabb73af5806fb39                                    373c808f0dba572",
                "MacAddress": "02:42:ac:12:00:06",
                "IPv4Address": "172.18.0.6/16",
                "IPv6Address": ""
            },
            "c5ccae40540ffd3221100ff55363ed72d199b6bcaa3c458b655eb3d2763e8c3f":                                     {
                "Name": "aevolume_engine-simpleq_1",
                "EndpointID": "b15e88f8747c39af239503f285aad17af9dd1e39c26a18271                                    0b49fc43919df17",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "c83191c1c432163010d24357145cda3f85d9786347752426420fc993ecfd8d53":                                     {
                "**Name": "registry",
                "EndpointID": "d6f5fbded48fa25a5bfc7cbd28883e90ba1bc8168f0fcf05a                                    4bb98bcf75173eb",
                "MacAddress": "02:42:ac:12:00:08",
                "IPv4Address": "172.18.0.8/16",
                "IPv6Address": ""**
            },
            "e904ee43b996db966e87f1ffebf7cf23b161e9980c81dcfdd4393cfaa1092efb":                                     {
                "Name": "aevolume_engine-analyzer_1",
                "EndpointID": "df7de7056bb988e1ee36fbe3c2cd268dc0ec59e60aaaec69b                                    98ef15b019b70a1",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "aevolume",
            "com.docker.compose.version": "1.24.1"
        }
    }
]

3. No need to take any more of your precious time...until i set up the cert for the registry.

Much obliged.
Danesh

**Comment by blang9238** [comment]
@dforouhari 

Not a problem Danesh, I've found this [link](https://www.sslshopper.com/article-most-common-openssl-commands.html) helpful in using OpenSSL to generate certs without have to go through setting up your own CA and generating a CSR.

Let me know if you have any further questions!

**Comment by dforouhari** [comment]
@blang9238
Thanks again for your help. I was about to follow the instructions in https://medium.com/@ManagedKube/docker-registry-2-setup-with-tls-basic-auth-and-persistent-data-8b98a2a73eec when I saw your latest comment.

What do u think?

Thanks
Danesh

**Comment by blang9238** [comment]
@dforouhari 
Yep that looks like a good link to follow.  The cert/key generation happens with:

```bash
$ openssl req -newkey rsa:2048 -nodes -keyout registry_auth.key -x509 -days 365 -out registry_auth.crt
```
Just make sure to put the registry_auth.key and registry_auth.cert in the volume you mount under /certs in the container and set the REGISTRY_HTTP_TLS_CERTIFICATE and REGISTRY_HTTP_TLS_KEY environment variables to /cert/registry_auth.crt and /cert/registry_auth.key respectively.

**Comment by dforouhari** [comment]
@blang9238,
Hi Ben. 
Thanks again for your help. I managed to get my issue resolved. There are 3 things that I would like to share with you:
**1.** After creating the cert and making sure that it was in the correct directory and 'docker run' was pointing to the correct directory for the -v, ...i was still getting the same/original error code and message.
Out of desperation, instead of using **localhost.localdomain:5000**, I used **127.0.0.1:5000**, i.e.
#docker tag hello_loop 127.0.0.1:5000/my_first_image
#docker push 127.0.0.1:5000/my_first_image.
No other change was made. It is not clear why the change would make things work. 
FWIIW,
a) /etc/hosts has the following entry:
127.0.0.1  localhost localhost.localdomain localhost4 localhost4.localdomain4
b) cat /etc/docker/daemon.json
{
        "insecure-registries" : [
                                 "localhost.localdomain:5000",
                                 "127.0.0.1:5000",
                                 "localhost:5000"
                                ]
}

**2. The image size reported by anchore-engine is not correct (it is not the same as the actual file size and/or size reported by docker inspect**

a) Size reported by anchore-engine:
Image ID: ee603cc938cc6097cee34a051c20383f9ec3a19123c17eee0894b7ba0c0d0bff
Dockerfile Mode: Guessed
Distro: alpine
Distro Version: 3.9.2
**Size: 20428800**
Architecture: amd64
Layer Count: 5

b) Size reported by 'docker inspect...'
$ docker inspect ee603cc938cc6097cee34a051c20383f9ec3a19123c17eee0894b7ba0c0d0bff --format='{{.Size}}'
**14708264**    **This is the correct size**

**3. A comment/suggestion:**
The word 'registry' is some what overloaded  in the given examples. It would be better to use a word such as 'my_registry' where appropriate

I won't close the tkt, so you can add your comment, if you choose. 

Best regards,
Danesh

**Comment by LukaszGalNok** [comment]
This is not work for me.
I thinks I can't put this solution tohether. Also the command with tag is wrong created i think, should be:
docker tag docker.io/registry:latest registry:5000/registry:latest

But, I created my repo with crt
[root@localhost aevolume]# docker-compose exec anchore-engine anchore-cli --u admin --p foobar registry list
Registry                Type             User         
my-registry:5000        docker_v2        admin 

But when I am trying to push I get this:
[root@localhost aevolume]# docker push my-registry:5000/cpro-centos-mini:latest
The push refers to repository [my-registry:5000/cpro-centos-mini]
Get https://my-registry:5000/v2/: dial tcp: lookup my-registry on 62.179.1.63:53: no such host

**Comment by akshay-1994** [comment]
Hi, I have a similar kind of issue. I can docker pull the same image from a private registry but when I try to add using the anchore-cli , I get 400 Bad request error. I checked the code, if docker pull is working for my private regsitry, then I should be able to add the docekr registry using image add?
