### ISSUE TITLE
The Anchore Engine CLI container image link in the readme 404s

### ISSUE THREAD

**Issue by MichaelSimons** [anchore/anchore-engine#242]
In the [repo's readme](https://github.com/anchore/anchore-engine/blob/master/README.md) as well as the [readme on Docker Hub](https://hub.docker.com/r/anchore/anchore-engine/), there is a link to the `Anchore Engine CLI container image` that 404's.

```
The Anchore CLI can be installed using the Python pip command, or by running the CLI from the [Anchore Engine CLI](https://cloud.docker.com/u/anchore/repository/docker/anchore/engine-cli) container image.  See the [Anchore CLI](https://github.com/anchore/anchore-cli) project on github for code and more installation options and usage.
```

Should the link be changed from `https://cloud.docker.com/u/anchore/repository/docker/anchore/engine-cli` to `https://hub.docker.com/r/anchore/engine-cli`?

**Comment by blang9238** [comment]
Hi @MichaelSimons,

Thanks for bringing this to our attention!  I will get the link updated.

As a side note, all of our documentation is open-source and the community is absolutely encouraged to contribute!  Just fork the enterprise-docs repo and submit a PR with a signed-off commit.  Here's a link to the [docs](https://github.com/anchore/enterprise-docs) and the instructions for [contributing](https://github.com/anchore/enterprise-docs/blob/master/CONTRIBUTING.rst).

**Comment by MichaelSimons** [comment]
@blang9238 - FYI - I had already created and linked a PR for where I thought the source of the documentation was.

**Comment by blang9238** [comment]
@MichaelSimons you're right, sorry about that!
