### ISSUE TITLE
Issue with adding image from a filesystem

### ISSUE THREAD

**Issue by navzen2000** [anchore/anchore-engine#245]
My image is located in the filesystem and not docker registry. Is it possible to add the same to anchore engine for analysis. I see below error:-

root:~/aevolume# docker-compose exec engine-api anchore-cli image add image_file --dockerfile=/root/images/myproduct/Dockerfile
Usage: anchore-cli image add [OPTIONS] INPUT_IMAGE
Try "anchore-cli image add --help" for help.

Error: Invalid value for "--dockerfile": Path "/root/images/myproduct/Dockerfile" does not exist.

**Comment by zhill** [comment]
The engine does not currently support adding images from a local host, though that feature is currently in development. An alternative approach is our inline scanner that will execute a scan locally and return reports/results but not add the image to a stateful anchore engine installation.

To use the inline scan: https://docs.anchore.com/current/docs/using/integration/ci_cd/inline_scanning

The ability to add a local image to a stateful deployment of the service is in development and testing now and should be part of the 0.5.0 engine release with an associated script similar to the inline scan that will analyze the image locally and submit the result to a remote anchore deployment (that you manage/host).

**Comment by zhill** [comment]
Closing this out due to inactivity. If there are any follow ups or question about the docs for inline scans, please file an issue in that repo: github.com/anchore/ci-tools or re-open this issue.
