### ISSUE TITLE
Image Add - Registry permission denied

### ISSUE THREAD

**Issue by ammonjerro** [anchore/anchore-engine#248]
Hi, I have such problem: I was asked to find a tool to scan the vulnerabilities of the  web service which runs on Docker, there are like 10 containers (Tomcat, Jenkins, Nginx etc. ) The Anchore Engines are working fine, but once I try to add an image to anchore with: 
`docker-compose exec engine-api anchore-cli --u admin --p foobar --url http://localhost:8228/v1 image add smw-zpwd/sm-alfresco:v4` 

I get the error:

```
Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {'error_codes': ['REGISTRY_PERMISSION_DENIED'], 'raw_exception_message': 'Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://docker.io/smw-zpwd/sm-tomcat:v95, rc=1, stdout=None, stderr=b\'time="2019-08-06T11:37:11Z" level=fatal msg="Error reading manifest v95 in docker.io/smw-zpwd/sm-tomcat: errors:\\ndenied: requested access to the resource is denied\\nunauthorized: authentication required\\n" \\n\', error_code=REGISTRY_PERMISSION_DENIED'}

```
I am totally new to Docker, and don't now how to operate with it. Does it mean that I need login and password to the account from which these containers were run to scan them with "vuln"?

I've read many topics here but they seem very complicated for me and I'd be grateful If somebody helped me to solve this issue.  Thanks in advance.

**Comment by blang9238** [comment]
Hi @ammonjerro,

Usually you'll see the permission denied error when a login is required to pull the image.

```bash
$ docker login
Username: username
Password: ******
Login Succeeded.
```

After you run 'docker login', are you able to pull it using Docker itself?

```bash
$ docker pull smw-zpwd/sm-alfresco:v4
```

You may also need to be given permission to that repository to be able to pull any of the images.  It failed when I attempted but that could mean two things; either I don't have permission to pull that image or the image doesn't exist.

**Comment by ammonjerro** [comment]
Thank you @blang9238 for your answer!
I learned from a person, who manages this Docker, that there is no repository, no registry, and everything was run from local dockerfiles, images etc. So now my question is: can I somehow add these local images to registry, or to Anchore, or should I build images from dockerfiles, or create some docker repository? What would you recommend?

**Comment by blang9238** [comment]
@ammonjerro it really depends on what fits your use case and architecture.

Here are a few options that could help you but discuss it with your team to see what makes the most sense for you.

- Create your own internal registry that you push your local images to (keep in mind that Anchore needs to be able to access it externally, meaning you'll need to deploy it with TLS/SSL)
  - Here's some guidance on deploying an externally accessible registry: https://docs.docker.com/registry/deploying/#run-an-externally-accessible-registry
  - Here's how you can configure Anchore to work with that repository: https://docs.anchore.com/current/docs/using/cli_usage/registries/configuring_registries/

Anchore also offers in-line scanning, where you can build locally and run scans on your local images:
- https://docs.anchore.com/current/docs/engine/usage/integration/ci_cd/inline_scanning/
 
Hopefully that can give you some things to build upon.  Let me know if you have any further questions!

**Comment by ammonjerro** [comment]
Thank you @blang9238!

Anchore in-line scanning worked perfectly! Thank you for your advices, issue closed!

**Comment by van34** [comment]
I have configured jenkins to build a docker image and scan it through anchore before pushing it to the Repository.after the image build anchor-images file is not picking the docker image for scan.

![anch jenkins slack](https://user-images.githubusercontent.com/47215676/74830586-7aff1480-5339-11ea-952e-34df009175ac.JPG)
