### ISSUE TITLE
Analysis of  a ( large)  docker image completes with ""status": "fail" and no details

### ISSUE THREAD

**Issue by dforouhari** [anchore/anchore-engine#250]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT  potential bug

**Version of Anchore Engine and Anchore CLI if applicable**:
I run anchor-cli via engine-api container, i.e.,
$ /usr/local/bin/docker-compose exec engine-api anchore-cli --version
anchore-cli, version 0.4.1

$ docker-compose exec engine-api anchore-cli system status
Service policy_engine (anchore-quickstart, http://engine-policy-engine:8228): up
Service analyzer (anchore-quickstart, http://engine-analyzer:8228): up
Service simplequeue (anchore-quickstart, http://engine-simpleq:8228): up
Service catalog (anchore-quickstart, http://engine-catalog:8228): up
Service apiext (anchore-quickstart, http://engine-api:8228): up

Engine DB Version: 0.0.10
Engine Code Version: 0.4.1

Some more info of interest:
$ cat /etc/system-release
CentOS Linux release 7.4.1708 (Core)

$ docker --version
Docker version 18.03.0-ce, build 0520e24

$ docker-compose --version
docker-compose version 1.24.1, build 4667896b
 
**What happened**:
The analysis of large docker image complete with no error (  **"analysis_status": "analyzed",** )but with application's analysis status set to "status": "fail"

**What did you expect to happen**:
The analysis completes with no error with "status": "fail". It is not clear to as of how to interpret this.
If "status": "fail" means that the docker image had some vulnerability, I could not see any details in the output regarding which  vulnerability, i.e.
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[
    {
        "sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704": {
            "localhost.localdomain:5000/my_third_image:latest": [
                {
                    **"detail": {},**
                    "last_evaluation": "2019-08-07T19:27:03Z",
                    "policyId": "2c53a13c-1765-11e8-82ef-23527761d060",
                    "**status": "fail"**
                }
            ]

**Any relevant log output from /var/log/anchore**:
N/A

**What docker images are you using**:
 An Ubuntu-16.04+Python+Bash complex program. It executes correctly

**How to reproduce the issue**:
The problem could be due to the size of image (1.67GB). So it might be possible to reproduce the issue using a Large Ubuntu-16.04 Python image.

I can reproduce it every time with the same result.

**Anything else we need to know**:
See the output below. Note that the analysis took a relatively long time, i.e. i saw **many** instances of the following two lines:

**Status: analyzing
Waiting 5.0 seconds for next retry.**

============================
DEBUG:anchorecli.cli.image:discovery from input: tag : localhost.localdomain:5000/my_third_image:latest
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /swagger.json HTTP/1.1" 200 99400
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/images
DEBUG:anchorecli.clients.apiexternal:GET params={'fulltag': 'localhost.localdomain:5000/my_third_image:latest', 'history': 'false'}
DEBUG:anchorecli.clients.apiexternal:Use get body because detected api version (0, 1, 11) < (0, 1, 6)? False
DEBUG:anchorecli.clients.apiexternal:GET insecure=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /images?fulltag=localhost.localdomain%3A5000%2Fmy_third_image%3Alatest&history=false HTTP/1.1" 200 4654
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[
    {
        **"analysis_status": "analyzed",**
        "analyzed_at": "2019-08-07T19:26:52Z",
        "annotations": {},
        "created_at": "2019-08-07T19:19:51Z",
        "imageDigest": "sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704",
        "image_content": {
            "metadata": {
                "arch": "amd64",
                "distro": "ubuntu",
                "distro_version": "16.04",
                "dockerfile_mode": "Guessed",
                "image_size": 1672960000,
                "layer_count": 8
            }
        },
        "image_detail": [
            {
                "created_at": "2019-08-07T19:19:51Z",
                "digest": "sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704",
                "dockerfile": "RlJPTSBzY3JhdGNoCkFERCBmaWxlOjkxNmE0NTAzMGRlZTg4MWJiYzhiYmFiZjhiY2ZjYzg4MjhjMjljZTFjMzE4MDAwOTUwYmJlODRjNTdmOWRmNzMgaW4gLyAKUlVOIC9iaW4vc2ggLWMgc2V0IC14ZSAJCSYmIGVjaG8gJyMhL2Jpbi9zaCcgPiAvdXNyL3NiaW4vcG9saWN5LXJjLmQgCSYmIGVjaG8gJ2V4aXQgMTAxJyA+PiAvdXNyL3NiaW4vcG9saWN5LXJjLmQgCSYmIGNobW9kICt4IC91c3Ivc2Jpbi9wb2xpY3ktcmMuZCAJCSYmIGRwa2ctZGl2ZXJ0IC0tbG9jYWwgLS1yZW5hbWUgLS1hZGQgL3NiaW4vaW5pdGN0bCAJJiYgY3AgLWEgL3Vzci9zYmluL3BvbGljeS1yYy5kIC9zYmluL2luaXRjdGwgCSYmIHNlZCAtaSAncy9eZXhpdC4qL2V4aXQgMC8nIC9zYmluL2luaXRjdGwgCQkmJiBlY2hvICdmb3JjZS11bnNhZmUtaW8nID4gL2V0Yy9kcGtnL2Rwa2cuY2ZnLmQvZG9ja2VyLWFwdC1zcGVlZHVwIAkJJiYgZWNobyAnRFBrZzo6UG9zdC1JbnZva2UgeyAicm0gLWYgL3Zhci9jYWNoZS9hcHQvYXJjaGl2ZXMvKi5kZWIgL3Zhci9jYWNoZS9hcHQvYXJjaGl2ZXMvcGFydGlhbC8qLmRlYiAvdmFyL2NhY2hlL2FwdC8qLmJpbiB8fCB0cnVlIjsgfTsnID4gL2V0Yy9hcHQvYXB0LmNvbmYuZC9kb2NrZXItY2xlYW4gCSYmIGVjaG8gJ0FQVDo6VXBkYXRlOjpQb3N0LUludm9rZSB7ICJybSAtZiAvdmFyL2NhY2hlL2FwdC9hcmNoaXZlcy8qLmRlYiAvdmFyL2NhY2hlL2FwdC9hcmNoaXZlcy9wYXJ0aWFsLyouZGViIC92YXIvY2FjaGUvYXB0LyouYmluIHx8IHRydWUiOyB9OycgPj4gL2V0Yy9hcHQvYXB0LmNvbmYuZC9kb2NrZXItY2xlYW4gCSYmIGVjaG8gJ0Rpcjo6Q2FjaGU6OnBrZ2NhY2hlICIiOyBEaXI6OkNhY2hlOjpzcmNwa2djYWNoZSAiIjsnID4+IC9ldGMvYXB0L2FwdC5jb25mLmQvZG9ja2VyLWNsZWFuIAkJJiYgZWNobyAnQWNxdWlyZTo6TGFuZ3VhZ2VzICJub25lIjsnID4gL2V0Yy9hcHQvYXB0LmNvbmYuZC9kb2NrZXItbm8tbGFuZ3VhZ2VzIAkJJiYgZWNobyAnQWNxdWlyZTo6R3ppcEluZGV4ZXMgInRydWUiOyBBY3F1aXJlOjpDb21wcmVzc2lvblR5cGVzOjpPcmRlcjo6ICJneiI7JyA+IC9ldGMvYXB0L2FwdC5jb25mLmQvZG9ja2VyLWd6aXAtaW5kZXhlcyAJCSYmIGVjaG8gJ0FwdDo6QXV0b1JlbW92ZTo6U3VnZ2VzdHNJbXBvcnRhbnQgImZhbHNlIjsnID4gL2V0Yy9hcHQvYXB0LmNvbmYuZC9kb2NrZXItYXV0b3JlbW92ZS1zdWdnZXN0cwpSVU4gL2Jpbi9zaCAtYyBybSAtcmYgL3Zhci9saWIvYXB0L2xpc3RzLyoKUlVOIC9iaW4vc2ggLWMgbWtkaXIgLXAgL3J1bi9zeXN0ZW1kICYmIGVjaG8gJ2RvY2tlcicgPiAvcnVuL3N5c3RlbWQvY29udGFpbmVyCkNNRCBbIi9iaW4vYmFzaCJdCkFSRyB1aWQ9Z3NreWRlbW8KQVJHIHB3PWc1a3lEM20wCkFSRyBob21lPS9pbWdfZGVtby8KUlVOIHwzIGhvbWU9L2ltZ19kZW1vLyBwdz1nNWt5RDNtMCB1aWQ9Z3NreWRlbW8gL2Jpbi9zaCAtYyBhcHQtZ2V0IHVwZGF0ZSAgICAgJiYgYXB0LWdldCBpbnN0YWxsIC15IHNvZnR3YXJlLXByb3BlcnRpZXMtY29tbW9uICAgICAgICBzdWRvICAgICAgICBzc2hwYXNzICAgICAgICBweXRob24tcGlwICAgICAgICB6aXAgICAgICYmIGFwdC1nZXQgYXV0b3JlbW92ZSAgICAgJiYgcGlwIGluc3RhbGwgbnVtcHkgICAgICYmIHBpcCBpbnN0YWxsIHRlbnNvcmZsb3cKUlVOIHwzIGhvbWU9L2ltZ19kZW1vLyBwdz1nNWt5RDNtMCB1aWQ9Z3NreWRlbW8gL2Jpbi9zaCAtYyBwaXAgaW5zdGFsbCAtLXVwZ3JhZGUgcGlwClJVTiB8MyBob21lPS9pbWdfZGVtby8gcHc9ZzVreUQzbTAgdWlkPWdza3lkZW1vIC9iaW4vc2ggLWMgcGlwIGluc3RhbGwgaW11dGlscyAgICAgJiYgcGlwIGluc3RhbGwgc2Npa2l0LWltYWdlICAgICAmJiBhcHQtZ2V0IGluc3RhbGwgLXkgcHl0aG9uLW9wZW5jdiAgICAgJiYgc3VkbyB1c2VyYWRkIC1tIC1kICR7aG9tZX0gLXMgL2Jpbi9iYXNoIC1wICQob3BlbnNzbCBwYXNzd2QgIC0xICR7cHd9KSAtdSAzMTQxICR7dWlkfSAgICAgJiYgZWNobyAke3B3fSA+ICR7aG9tZX0vLnB3ICAgICAmJiBhcHQtZ2V0IGF1dG9yZW1vdmUgICAgICYmIHJtIC1yZiAvdmFyL2xpYi9hcHQvbGlzdHMvKgpBUkcgdWlkPWdza3lkZW1vCkFSRyBwdz1nNWt5RDNtMApBUkcgaG9tZT0vaW1nX2RlbW8vCldPUktESVIgL2ltZ19kZW1vLwpBREQgbXVsdGk6Nzk3ZmU1YzNmMmQ3MmMxMGZiZWYzN2NiN2JiODdlZjllYzA4NGRkNmVjYzcyMTRjN2MwOTFmYTJiODNlZTA4YyBpbiAvaW1nX2RlbW8vIApVU0VSIGdza3lkZW1vCkNNRCBbImJhc2giICItYyIgIi4vaW1nX2RlbW8gMiA1IDEwLjMuMi42MyJdCg==",
                "fulldigest": "localhost.localdomain:5000/my_third_image@sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704",
                "fulltag": "localhost.localdomain:5000/my_third_image:latest",
                "imageDigest": "sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704",
                "imageId": "752f8eea14330275ff2c3e1611f7db98cc13cfa9c9cc635b6970a7afb0f113e3",
                "last_updated": "2019-08-07T19:26:52Z",
                "registry": "localhost.localdomain:5000",
                "repo": "my_third_image",
                "tag": "latest",
                "tag_detected_at": "2019-08-07T19:19:51Z",
                "userId": "admin"
            }
        ],
        "image_status": "active",
        "image_type": "docker",
        "last_updated": "2019-08-07T19:26:52Z",
        "parentDigest": "sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704",
        "userId": "admin"
    }
]
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /swagger.json HTTP/1.1" 200 99400
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/images
DEBUG:anchorecli.clients.apiexternal:GET params={'fulltag': 'localhost.localdomain:5000/my_third_image:latest', 'history': 'false'}
DEBUG:anchorecli.clients.apiexternal:Use get body because detected api version (0, 1, 11) < (0, 1, 6)? False
DEBUG:anchorecli.clients.apiexternal:GET insecure=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /images?fulltag=localhost.localdomain%3A5000%2Fmy_third_image%3Alatest&history=false HTTP/1.1" 200 4654
DEBUG:anchorecli.cli.image:discovery from input: tag : localhost.localdomain:5000/my_third_image:latest : sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/images/sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704/content
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /images/sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704/content HTTP/1.1" 200 62
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[
    "os",
    "files",
    "npm",
    "gem",
    "python",
    "java"
]
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /swagger.json HTTP/1.1" 200 99400
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/images
DEBUG:anchorecli.clients.apiexternal:GET params={'fulltag': 'localhost.localdomain:5000/my_third_image:latest', 'history': 'false'}
DEBUG:anchorecli.clients.apiexternal:Use get body because detected api version (0, 1, 11) < (0, 1, 6)? False
DEBUG:anchorecli.clients.apiexternal:GET insecure=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /images?fulltag=localhost.localdomain%3A5000%2Fmy_third_image%3Alatest&history=false HTTP/1.1" 200 4654
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/images/sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704/vuln?vendor_only=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /images/sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704/vuln?vendor_only=True HTTP/1.1" 200 32
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[
    "os",
    "non-os",
    "all"
]
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET / HTTP/1.1" 200 5
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /swagger.json HTTP/1.1" 200 99400
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/images
DEBUG:anchorecli.clients.apiexternal:GET params={'fulltag': 'localhost.localdomain:5000/my_third_image:latest', 'history': 'false'}
DEBUG:anchorecli.clients.apiexternal:Use get body because detected api version (0, 1, 11) < (0, 1, 6)? False
DEBUG:anchorecli.clients.apiexternal:GET insecure=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /images?fulltag=localhost.localdomain%3A5000%2Fmy_third_image%3Alatest&history=false HTTP/1.1" 200 4654
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/images/sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704/check?history=false&detail=false&tag=localhost.localdomain:5000/my_third_image:latest
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8228
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /images/sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704/check?history=false&detail=false&tag=localhost.localdomain:5000/my_third_image:latest HTTP/1.1" 200 353
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[
    {
        "sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704": {
            "localhost.localdomain:5000/my_third_image:latest": [
                {
                    **"detail": {},**
                    "last_evaluation": "2019-08-07T19:27:03Z",
                    "policyId": "2c53a13c-1765-11e8-82ef-23527761d060",
                    "**status": "fail"**
                }
            ]
        }
    }
]

**Comment by nurmi** [comment]
hi @dforouhari 

Couple of clarifications: 

1) anchore has two main 'phases' of handling images, the first is 'analysis' where the image is downloaded, and its contents are inspected/categorized.  No scans or evals happen at this point, but rather the image is 'analyzed' so that the higher level applications (vuln scan, policy eval, content reports, etc) then be used.  The second phase is running said applications, which require an image to have been successfully 'analyzed'.

2) if you see an image failing to analyze, as per the info in 1), it won't be due to any 'application' issues like vulnerability scans/policy evals, etc, but rather that the image could not be downloaded/analyzed/contents categorized correctly by anchore for some reason.  To find out why, you can investigate the events, and further look into the analyzer (worker) logfiles for lots of detail on what has happened to prevent successful image analysis.

There are some links here that describe these topics and troubleshooting in more detail!

https://docs.anchore.com/current/docs/troubleshooting/
https://docs.anchore.com/current/docs/overview/concepts/images/analysis/

Let us know what you find using the troubleshooting techniiques to investigate further!

**Comment by dforouhari** [comment]
@nurmi 
Hello Dan. Thanks for your detailed follow up (and help).
Two things:
**1.** After getting the list of events in the system, below is the list of all events relevant to the this issue. Below is the list:
{
    "item_count": 100,
    "next_page": true,
    "page": 1,
    "results": [
        {
            "created_at": "2019-08-07T20:35:35.557160Z",
            "event": {
                "details": {
                    "sync_feed_types": [
                        "vulnerabilities"
                    ]
                },
                "level": "INFO",
                "message": "Feed sync completed",
                "resource": {
                    "type": "feeds",
                    "user_id": "admin"
                },
                "source": {
                    "base_url": "http://engine-policy-engine:8228",
                    "hostid": "anchore-quickstart",
                    "servicename": "policy_engine"
                },
                "timestamp": "2019-08-07T20:35:35.507985Z",
                "type": "feed_sync_complete"
            },
            "generated_uuid": "4b6f069399124a58b9a428665b8139ba"
        },
        {
            "created_at": "2019-08-07T20:35:06.816272Z",
            "event": {
                "details": {
                    "sync_feed_types": [
                        "vulnerabilities"
                    ]
                },
                "level": "INFO",
                "message": "Feed sync started",
                "resource": {
                    "type": "feeds",
                    "user_id": "admin"
                },
                "source": {
                    "base_url": "http://engine-policy-engine:8228",
                    "hostid": "anchore-quickstart",
                    "servicename": "policy_engine"
                },
                "timestamp": "2019-08-07T20:35:06.769926Z",
                "type": "feed_sync_start"
            },
            "generated_uuid": "ab9114c8b5f2456e8b3dc2235ae95c6b"
        },

I don't see any sign of trouble, based on above info.
**Question:  Does  'level' in **"level": "INFO"**,  has to do with the log-level setting which could be set to something else to provide more data, or the 'level' would had turned to, say ERROR, if an error was encountered?**

**2. For whatever reason, there are no log files in /var/log/anchore.**  Would u plz let me know what needs to be done in order to have logging enable. Note that I used 'Quickstart' document for installing anchore-engine. Is there some other document that I should has used?
Pls advise.
Thanks

**Comment by nurmi** [comment]
Thanks @dforouhari 

Not all failure events will register in the event log (but some do, which is why it is always good to check there).  The logfiles will be next - since anchore is running in containers, you'll need to look in the container(s) themselves, for each anchore service, where you'll find the logs in /var/log/anchore.  You can also use regular docker logging commands to view the logs (e.g. docker logs <containerId>), as anchore uses regular docker logging facilities also!

The logs you're looking for will be in the analyzer service container - (look for 'engine-analyzer' as the substring in the name of the container to get its id, etc).

**Comment by dforouhari** [comment]
@nurmi
Hi Dan.
1. Sorry for  forgetting that my anchore-engine components run in containers.

2. Below is the relevant log lines from engine-analyzer's anchore-worker.log file. I did not see any log entries would indicate any sort of errors/failures/... Pls see below.
$ docker exec aevolume_engine-analyzer_1 /bin/bash -c "ls /var/log/anchore"
anchore-worker.log

$ docker exec aevolume_engine-analyzer_1 /bin/bash -c "grep -v 'GET' /var/log/anchore/anchore-worker.log | grep '^2019-08-07'" ...

2019-08-07 19:19:54+0000 [-] [Thread-146831] [anchore_engine.services.analyzer/process_analyzer_job()] [INFO] image dequeued for analysis: admin : sha256:ddc044b3f5
34a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704
2019-08-07 19:19:54+0000 [-] [Thread-146831] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image: ['admin', 'localhost
.localdomain:5000/my_third_image@sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704', 'localhost.localdomain:5000/my_third_image:latest']
2019-08-07 19:25:45+0000 [-] [Thread-146831] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image complete: localhost.l
ocaldomain:5000/my_third_image@sha256:ddc044b3f534a633c899ec1f620b0cd866b70c88a35382925e133b7e9543b704
2019-08-07 19:25:54+0000 [-] [Thread-146831] [anchore_engine.services.analyzer/process_analyzer_job()] [INFO] Loading image into policy engine: admin 752f8eea143302
75ff2c3e1611f7db98cc13cfa9c9cc635b6970a7afb0f113e3
2019-08-07 19:26:52+0000 [-] [Thread-146831] [anchore_engine.services.analyzer/process_analyzer_job()] [INFO] analysis complete: admin : sha256:ddc044b3f534a633c899
ec1f620b0cd866b70c88a35382925e133b7e9543b704

**Comment by nurmi** [comment]
@dforouhari - my apologies, I think that I had misinterpreted your above report - I had read that your image had failed 'analysis' but from the output we can see that analysis completed successfully (i.e. the image went to 'analyzed').  What you're displaying is that the policy evaluation is reporting that the policy check itself has executed successfully, but determined that, based on the policy checks in place, the 'result' of the policy evaluation is 'fail'.  You can get more detail by adding '--detail' to the 'anchore-cli evaluate check' command, so see all of the checks that are triggering.

It looks like everything in anchore is working properly, it is expected that policy evaluations can result in a 'fail' status, when images do not pass the policy checks that you are running.

There is a good overview of policies and the concepts at our docs site:

https://docs.anchore.com/current/docs/overview/concepts/policy/

Let us know if you have more questions about anchore usage, but I believe that this ticket could be  closed (if you agree!) as we're not seeing any system bug/failures in the shared output

**Comment by dforouhari** [comment]
> @dforouhari <https://github.com/dforouhari> - my apologies, I think that
> I had misinterpreted your above report
>
DF yup. See  "analysis_status": "analyzed", in the original/first bug
report.

> - I had read that your image had failed 'analysis' but from the output we
> can see that analysis completed successfully (i.e. the image went to
> 'analyzed'). What you're displaying is that the policy evaluation is
> reporting that the policy check itself has executed successfully, but
> determined that, based on the policy checks in place, the 'result' of the
> policy evaluation is 'fail'. You can get more detail by adding '--detail'
> to the 'anchore-cli evaluate check' command, so see all of the checks that
> are triggering.
>
DF OK. I'l turn on the --detail flag on and see what I get.
As I had listed in my original comment, we have
 {
*"detail": {},*
"last_evaluation": "2019-08-07T19:27:03Z",
"policyId": "2c53a13c-1765-11e8-82ef-23527761d060",
"status": "fail"
}
Question/suggestion: Why not provide some info in the  "detail": {} field
regarding the nature of the failure?

Thank you.
Danesh

**Comment by nurmi** [comment]
Hi @dforouhari 

Indeed!  If you supply the '--detail' flag, you'll see details in that field with a lot of information.

**Comment by dforouhari** [comment]
@nurmi 
Thanks for the help & guidance. I will close the tkt shortly.
I still believe providing zero details (or what to do) when "status": fail is less than desirable. God knows how long would had taken for me to find out that I should run 'anchor-cli evaluate check --detail ..." to find the cause of these failure. If there is a FAQ that would list what to do in this case, then I take full-responsibility for not having read it, and my apologies. 

Danesh
