### ISSUE TITLE
Anchore engine add registry failed for private registry

### ISSUE THREAD

**Issue by navzen2000** [anchore/anchore-engine#252]
root@kali:~/aevolume# docker-compose exec engine-api anchore-cli registry add --insecure **registry-server.com:5000** admin password
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://registry-server.com:5000,admin) - exception: HTTPSConnectionPool(host='registry-server.com', port=5000): Max retries exceeded with url: /v2/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fffe71fdc50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTP Code: 406
Detail: {'error_codes': []}

Anchore engine is unable to add private registry set up using self-signed certificate. registry-server is defined in /etc/hosts
root@kali:~/aevolume# cat /etc/hosts
127.0.0.1	localhost www.dvwa.com www.xvwa.com
127.0.1.1	kali
**192.168.56.102  registry-server.com**
192.168.56.101  registry-client.com

Curl works fine in getting the docker repo from registry-server.com
root@kali:~/aevolume# curl -u admin:password -X GET **https://registry-server.com:5000**/v2/_catalog
{"repositories":["testimage"]}

**Comment by blang9238** [comment]
Hi @navzen2000,

It appears as though your engine-api container is not able to resolve the registry fqdn (registry-server.com).  Bear in mind that while the entry may be in your /etc/hosts file and you can resolve it from the instance itself, Docker containers don't natively inherit the networking from the host, meaning the container can't see your hosts /etc/hosts file.  You can see from this output that it's not able to recognize the registry name:

```bash
Failed to establish a new connection: [Errno -2] Name or service not known
```

There are a couple options you can do to get docker to recognize the registry-server.com fqdn:

- Set up DNS so that registry-server.com resolves to the 192.168.56.102 address from anywhere within your network (recommended for production environments, but not necessary for testing purposes)
- Add an 'extra_hosts' section in your docker-compose.yaml to the relevant services (in this case engine-api):
  - ```yaml
     extra_hosts:
       - "registry-server.com:192.168.56.102"
     ```
Here's some Docker docs on the extra_hosts option for compose:
https://docs.docker.com/compose/compose-file/#extra_hosts

Let me know how that works for you!

**Comment by navzen2000** [comment]
Hi @blang9238 ,
Tried to follow the suggestion, bit it did not work
docker-compose.yaml
services:
  # The primary API endpoint service
  engine-api:
    image: anchore/anchore-engine:v0.4.1
    depends_on:
    - anchore-db
    - engine-catalog
    ports:
    - "8228:8228"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
    - ANCHORE_ENDPOINT_HOSTNAME=engine-api
    - ANCHORE_DB_HOST=anchore-db
    - ANCHORE_DB_PASSWORD=mysecretpassword
    command: ["anchore-manager", "service", "start", "apiext"]
    extra_hosts:
    - "registry-server.com:192.168.56.102"

Same error is seen:
root@kali:~/aevolume# docker-compose exec engine-api anchore-cli registry add --insecure registry-server.com:5000 admin password
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://registry-server.com:5000,admin) - exception: HTTPSConnectionPool(host='registry-server.com', port=5000): Max retries exceeded with url: /v2/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fffe722deb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTP Code: 406
Detail: {'error_codes': []}

**Comment by blang9238** [comment]
Hi @navzen2000,

Let's dig a little further into this.  Make sure the entry is added to the /etc/hosts file within the container.  To make the output a little more verbose so we can further narrow the issue, try adding the --debug and --json options to the "registry add --insecure" command. 

Can you post the output of the following command run on the engine-api.

```bash
# docker-compose exec engine-api bash -c "cat /etc/hosts"
```

Also, let's make sure the registry is accessible from the engine-api container:

```bash
# docker-compose exec engine-api bash -c "curl registry-server.com:5000"
```

**Comment by navzen2000** [comment]
Hi @blang9238 ,

I have followed your guideline and have included the registry server in all the containers.

`root@kali:~/aevolume# docker-compose exec anchore-db bash -c "cat /etc/hosts"`
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.56.102	registry-server.com
172.19.0.2	eea80c63b80c

`root@kali:~/aevolume# docker-compose exec engine-analyzer bash -c "cat /etc/hosts"`
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.56.102	registry-server.com
172.19.0.7	292b22b2c9c6

`root@kali:~/aevolume# docker-compose exec engine-api bash -c "cat /etc/hosts"`
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.56.102	registry-server.com
172.19.0.6	460cd12f2ee1

`root@kali:~/aevolume# docker-compose exec engine-catalog bash -c "cat /etc/hosts"`
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.56.102	registry-server.com
172.19.0.3	3b0d5823b055

`root@kali:~/aevolume# docker-compose exec engine-policy-engine bash -c "cat /etc/hosts"`
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.56.102	registry-server.com
172.19.0.5	e1efeb36eef9

`root@kali:~/aevolume# docker-compose exec engine-simpleq bash -c "cat /etc/hosts"`
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.56.102	registry-server.com
172.19.0.4	327b047b5683

The output of curl command is empty 

`root@kali:~/aevolume#  docker-compose exec engine-api bash -c "curl registry-server.com:5000"`

root@kali:~/aevolume# 

Also the registry add command did not accept --debug and --json parameters for verbose logging

`root@kali:~/aevolume# docker-compose exec engine-api anchore-cli registry add --insecure --debug --json registry-server.com:5000 admin password `
Usage: anchore-cli registry add [OPTIONS] REGISTRY REGISTRY_USER REGISTRY_PASS
Try "anchore-cli registry add --help" for help.

Error: no such option: --debug

However, after making the changes for all the container as above, the add command worked like a charm

`root@kali:~/aevolume# docker-compose exec engine-api anchore-cli registry add --insecure registry-server.com:5000 admin password`
Registry: registry-server.com:5000
User: admin
Type: docker_v2
Verify TLS: False
Created: 2019-08-13T05:12:35Z
Updated: 2019-08-13T05:12:35Z

Thank you :)

**Comment by zhill** [comment]
Closing this as resolved. Please re-open if follow-up is needed.
