### ISSUE TITLE
Regression for ECR access with IAM Role: "external_id referenced before assignment"

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#259]
Affects version: v0.5.0 only

If accessing an ECR registry via an IAM role added via:
`anchore-cli registry add <ecr url> _iam_role arn:aws:...`

there is a regression introduced in the addition of external_id support that causes an error:

Error: cannot refresh credentials for supplied registry, with supplied credentials - exception: local variable ‘external_id’ referenced before assignment

Workaround: re-add the role with a trailing semicolon
```
anchore-cli registry add <ecr url> _iam_role 'arn:aws:...;'
```

Note the surrounding single quote to ensure the semi-colon is passed to the api call properly.

**Comment by zhill** [comment]
It is already merged into the 0.5 maintenance branch and will be in the 0.5.1 release. This ticket won't get auto-closed until the fix is merged into master for the 0.6.0 release Typically we push a maint release every month or so. Note the above described workaround that resolved the error if you have it in production now. The fix will not cause that workaround to break so it is safe to apply.

**Comment by zhill** [comment]
Anchore already has support for external_id and assuming roles to interact with ECR, but I think the docs are lacking. @pklanka are you asking about that support in general, or just this specific bug fix?

**Comment by pklanka** [comment]
I was talking about this specific bug fix. Our iam role integrations are down. Do you know what is the release date for 0.5.1.

**Comment by zhill** [comment]
Likely end of Sept or early Oct. However, we auto-build containers with dev code, so you can try the anchore/anchore-engine:v0.5-dev container (I'd get the digest for the current build and lock it if I were you), and try that as a test. if that works you can use that specific container (locked by digest) until the release is ready and there is a v0.5.1 container to swap out.

**Comment by zhill** [comment]
However, I highly recommend the workaround for now: re-add the registry credential record with a trailing semicolon on the arn: example: "arn:aws::<account>:/role/<roleName>;" that will fix the problem until the fix is released
