### ISSUE TITLE
image analysis fails

### ISSUE THREAD

**Issue by vchan2002** [anchore/anchore-engine#26]
The image analysis fails at this particular point... I have debug turned on... here's the specific error....
`
.2018-01-19 12:53:55+0000 [-] [Thread-74] [anchore_engine.services.analyzer/process_analyzer_job()] [DEBUG] policy engine request: {'fetch_url': 'catalog://admin/analysis_data/sha256:b5611db8560bb3a95294191613c4ea428342ae857ecf02e9b670194e795c636a',
	 'image_id': u'b0dbdee9315add8d7b2ee9730a6a9d5f6f0f4cfdbae5a0c0863cc6064cf27761',
	 'user_id': u'admin'}
2018-01-19 12:53:55+0000 [-] Traceback (most recent call last):
2018-01-19 12:53:55+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 325, in process_analyzer_job
2018-01-19 12:53:55+0000 [-]     raise Exception("adding image to policy-engine failed - exception: " + str(err))
2018-01-19 12:53:55+0000 [-] Exception: adding image to policy-engine failed - exception: HTTPConnectionPool(host=u'localhost', port=8087): Max retries exceeded with url: /v1/images (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb888368cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-19 12:53:55+0000 [-] [Thread-74] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: adding image to policy-engine failed - exception: HTTPConnectionPool(host=u'localhost', port=8087): Max retries exceeded with url: /v1/images (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb888368cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

**Comment by nurmi** [comment]
Hi @vchan2002 

The error is indicating that the analyzer worker service cannot contact the policy engine service, after the image has been analyzed, with a 'connection refused' (indicating that the policy engine service is not contactable/reachable by the worker process) - if you could share a few more pieces of information,  we can see if we can find out why the worker cannot contact the policy engine on port localhost:8087

a) are you running a single container, or is your worker separate from the core services?
b) can you verify that the policy-engine service is up and running?
    - run: 'anchore-cli system status' or 
    - inspect: /var/log/anchore/anchore-policy-engine.log on the core service container
c) can you share your config.yaml(s) for us to take a look at?

with the above, we should be able to determine the nature of the problem (i.e. why the worker cannot contact localhost:8087)

Best,
-Dan

**Comment by vchan2002** [comment]
a)  I am using the docker-compose file that is provided in github.
b)  anchore-cli system status shows that all services, including policy_engine, is up and running.
c) config.yaml is unmodified from the default except for changing the log level to DEBUG and tmp_dir.

**Comment by nurmi** [comment]
@vchan2002 

Thanks for the info - that helps eliminate some possibilities - so we need dto determine why the worker process in the container is getting a connection refused from the policy-engine process which should be running in the same container - can you share some snippets from your other log files (anchore-policy-engine.log, anchore-catalog.log specifically)?  

Another test is to try and hit the policy  engine status URL from within your container to make sure that host:port are accessible:

```
docker exec -t -i <your_anchore_container> curl -u admin:<pw> http://localhost:8087/v1/status
```

Regards,
-Dan

**Comment by vchan2002** [comment]
Okay... here's what's interesting... not only does the curl not work.... I don't even see anchore-policy-engine.log... this indicates that the service does not even start up.....  I see this as a WARNING in anchore-catalog.log, but that's it....

2018-01-19 13:57:09+0000 [-] [Thread-695] [anchore_engine.services.common/check_services_ready()] [WARN] required service (policy_engine) is not (yet) available - will not queue analysis tasks this cycle

**Comment by acathrow** [comment]
does your engine have internet access - the policy engine starts by trying to download CVE/Security feed data?

**Comment by nurmi** [comment]
@vchan2002 

Good progress - that is indicating that the policy engine is not yet made it past the initial feed sync (which requires access to the internet, in order to download public vulnerability data records)

If the policy-engine it is performing its initial feed sync, which can take some time
    - this *should* result in the output of 'anchore-cli system status' showing 'down' for the policy engine, since the same check is made for that as is made for showing that log WARN 
    - looking at the container stdout/stderr log will help detemine this as well - here is a good command to try and get a sense for whether we're in this mode: 

```docker logs <anchore_container> | grep -v 'service:' | grep -v 'checking'```

Best
-Dan

**Comment by vchan2002** [comment]
Okay, it looks like the policy_engine_bootstrap is failing....

What is it trying to connect to, at this time?

2018-01-19 14:24:13,798 INFO policy_engine_bootstrap - Checking feeds client credentials
2018-01-19 14:24:13,800 DEBUG policy_engine_bootstrap - Initializing a feeds client
2018-01-19 14:24:13,824 DEBUG policy_engine_bootstrap - init values: [None, None, None, (), None, None]
2018-01-19 14:24:13,957 ERROR policy_engine_bootstrap - Preflight checks failed with error: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",). Aborting service startup

**Comment by acathrow** [comment]
Does it have internet access? Do you have a MITM stripping TLS and reencrypting?

**Comment by vchan2002** [comment]
None of those that I know of.....Just to be sure that it's not an issue with Docker on my Mac, I ran this on a linux box that doesn't have that... but the same error persists.....

**Comment by nurmi** [comment]
The anchore-engine does reach out to https://ancho.re for the feed sync - it does look like something on the net between your client and the server is interfering with that client -> server SSL connection - a quick test is to try to curl a feed service route from your network to see if we can learn whats happening (note that the below output (unauthorized) is expected for this test, its just verifying that the end-to-end host to server and back over SSL is all okay, empirically)

```
# curl https://ancho.re/v1/service/feeds
{
    "message": "Unauthorized request: no authentication given",
    "code": 401,
    "name": "unauthorized_request"
}
```

**Comment by acathrow** [comment]
And it'd be best to run curl from inside the container because we know that
the trust store in the container hasn't been changed.

**Comment by acathrow** [comment]
Just in case if we do need to debug TLS certificates then this would be an interesting command to run on your mac or Linux machine 

echo | openssl s_client -showcerts -servername ancho.re -connect anch.re:443 2>/dev/null | openssl x509 -inform pem -noout -text

We could see which certificate is being used to see if it's the one we expect.
This could be run in the container also, after yum install openssl

**Comment by vchan2002** [comment]
Interesting.......  I ran the curl command.... while my Mac that is running docker is fine with the 401, running it inside the Docker container yields the following:

[root@8f95952c69d2 anchore]# curl https://ancho.re/v1/service/feeds
curl: (60) Peer's Certificate has expired.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by acathrow** [comment]
It's possible that your Mac has a different CA bundle. Can you try that command from my previous comment?

thanks.

**Comment by vchan2002** [comment]
Here's what I get.... from the result of the command


unable to load certificate
140735860802440:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/pem/pem_lib.c:704:Expecting: TRUSTED CERTIFICATE

**Comment by acathrow** [comment]
@vchan2002 I just realized ...  I was missing an o in ancho.re 

echo | openssl s_client -showcerts -servername ancho.re -connect anch.re:443 2>/dev/null | openssl x509 -inform pem -noout -text

**Comment by vchan2002** [comment]
Okay... I should have seen that... here's the validity of the cert.. still not sure why my Mac doesn't respect it though... strange...

  Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=GB, ST=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO ECC Domain Validation Secure Server CA 2
        Validity
            Not Before: Jan 21 00:00:00 2018 GMT
            Not After : Jul 30 23:59:59 2018 GMT
        Subject: OU=Domain Control Validated, OU=PositiveSSL Multi-Domain, CN=sni189579.cloudflaressl.com
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey

**Comment by acathrow** [comment]
Thanks for running that test.
So that is indeed the right CA, I had hoped/expected to see an in-house CA cert from a SSL inspection appliance, but that doesn't appear to be the case.
The error here : Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",). Aborting service startup is odd.
Would it be possible to exec into the container and see if you can curl that URL again
https://ancho.re/v1/service/feeds
and see that the error is.

In a previous comment you had this "Peer's Certificate has expired."  I Suppose there's no chance that your date is off is there?

**Comment by mkloveyy** [comment]
Hello, I face this problem, too. I wish you can help me to solve this. My problem are as follows:
[root@localhost anchore-engine]# anchore-cli image list
Full Tag                               Image ID                                                                Analysis Status
docker.io/library/debian:latest        8626492fecd368469e92258dfcafe055f636cb9cbc321a5865a98a0a6c99b8dd        analyzed
docker.io/nginx:latest                 ae513a47849c895a155ddfb868d6ba247f60240ec8495482eca74c4a2c13a881        analysis_failed

As you can see that one image has been analyzed but another one can not be analyzed.

I try to check if policy engine is up and it shows:
[root@localhost anchore-engine]# anchore-cli system status
Service simplequeue (dockerhostid-anchore-engine, http://anchore-engine:8083): up
Service catalog (dockerhostid-anchore-engine, http://anchore-engine:8082): up
Service policy_engine (dockerhostid-anchore-engine, http://anchore-engine:8087): up
Service kubernetes_webhook (dockerhostid-anchore-engine, http://anchore-engine:8338): up
Service apiext (dockerhostid-anchore-engine, http://anchore-engine:8228): up
Service analyzer (dockerhostid-anchore-engine, http://anchore-engine:8084): up

It seems ok. So, I try to use the command:

```
docker exec -t -i <your_anchore_container> curl -u admin:<pw> http://localhost:8087/v1/status
```

And it returns:

```
{
  "available": true,
  "busy": false,
  "db_version": "0.0.6",
  "detail": {
    "service_state": "available"
  },
  "message": "all good",
  "up": true,
  "version": "0.2.1"
}
```

It still seems ok. So then, I try this:

```
docker logs <anchore_container> | grep -v 'service:' | grep -v 'checking'
```

This time, it returns:
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
/1.1" 200 143 "-" "python-requests/2.17.3"
service process exited at (Sat May 12 09:56:05 2018): process exited: 1
exiting service thread
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
service process exited at (Sat May 12 09:56:07 2018): process exited: 1
exiting service thread
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
e:simplequeue] 2018-05-12 09:56:08+0000 [-] "172.21.0.3" - - [12/May/2018:09:56:07 +0000] "GET /v1/leases/analyzer_queue HTTP/1.1" 200 89 "-" "python-requests/2.17.3"
service process exited at (Sat May 12 09:56:10 2018): process exited: 1
exiting service thread
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
- - [12/May/2018:09:56:11 +0000] "GET /v1/leases/analyzer_queue/acquire/?client_id=9924cbb3cdaa:17:140490428364544:&ttl=60 HTTP/1.1" 200 143 "-" "python-requests/2.17.3"
service process exited at (Sat May 12 09:56:13 2018): process exited: 1
exiting service thread
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
service process exited at (Sat May 12 09:56:15 2018): process exited: 1
exiting service thread
asks/?wait_max_seconds=30&visibility_timeout=0 HTTP/1.1" 200 465 "-" "python-requests/2.17.3"
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
service process exited at (Sat May 12 09:56:18 2018): process exited: 1
exiting service thread
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
2018:09:56:19 +0000] "GET /v1/queues/watcher_tasks/?wait_max_seconds=30&visibility_timeout=0 HTTP/1.1" 200 465 "-" "python-requests/2.17.3"
service process exited at (Sat May 12 09:56:22 2018): process exited: 1
exiting service thread
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
+0000] "GET /v1/queues/watcher_tasks/?wait_max_seconds=30&visibility_timeout=0 HTTP/1.1" 200 465 "-" "python-requests/2.17.3"
equests/2.17.3"
service process exited at (Sat May 12 09:56:26 2018): process exited: 1
exiting service thread
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
service process exited at (Sat May 12 09:56:29 2018): process exited: 1
exiting service thread
.1" 200 465 "-" "python-requests/2.17.3"
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
service process exited at (Sat May 12 09:56:32 2018): process exited: 1
exiting service thread
restarting service anchore-policy-engine
	 /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-policy-engine.pid -n anchore-policy-engine --config /config
18:09:56:33 +0000] "POST /v1/queues/watcher_tasks/?qcount=0&forcefirst=False HTTP/1.1" 200 5 "-" "python-requests/2.17.3"
service process exited at (Sat May 12 09:56:35 2018): process exited: 1
exiting service thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1

I think problem might be here but I can not explain it. Can you help me? Thanks a lot!

**Comment by nurmi** [comment]
hi @mkloveyy ,

I wanted to check in to see if there are still any pending issues/questions on this topic, or if the issues have been resolved in your setup?
