### ISSUE TITLE
Error Private Registry

### ISSUE THREAD

**Issue by Kaitsh** [anchore/anchore-engine#27]
Hi Anchore Team,
I try to analyze images from a private registry.  I added it to anchore using 
```bash
anchore-cli registry add myregistry:443 foo bar --insecure
```

But still I get an error that anchore cannot get the image and the analysis fails:

```
[service:worker] 2018-02-07 15:04:00+0000 [-] [Thread-1605] [anchore_engine.auth.docker_registry/get_authenticated_cli()] [DEBUG] DOCKER CLI: making new auth CLI for user/registry: foo / myregistry:443
[service:worker] 2018-02-07 15:04:00+0000 [-] [Thread-1605] [anchore_engine.auth.docker_registry/get_authenticated_cli()] [DEBUG] DOCKER CLI: making auth CLI
[service:worker] 2018-02-07 15:04:00+0000 [-] [Thread-1605] [anchore_engine.auth.docker_registry/get_authenticated_cli()] [ERROR] DOCKER CLI auth err: 500 Server Error: Internal Server Error ("{"message":"Get https://myregistry:443/v1/users/: x509: certificate signed by unknown authority"}")
[service:worker] 2018-02-07 15:04:00+0000 [-] [Thread-1605] [anchore_engine.auth.docker_registry/get_authenticated_cli()] [ERROR] DOCKER CLI: unable to get docker cli - exception: 500 Server Error: Internal Server Error ("{"message":"Get https://myregistry:443/v1/users/: x509: certificate signed by unknown authority"}")
[service:worker] 2018-02-07 15:04:00+0000 [-] [Thread-1605] [anchore_engine.services.analyzer/perform_analyze_localanchore()] [ERROR] error on pull: 500 Server Error: Internal Server Error ("{"message":"Get https://myregistry:443/v1/users/: x509: certificate signed by unknown authority"}")
[service:worker] 2018-02-07 15:04:00+0000 [-] Traceback (most recent call last):
[service:worker] 2018-02-07 15:04:00+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 257, in process_analyzer_job
[service:worker] 2018-02-07 15:04:00+0000 [-]     image_data = perform_analyze(userId, manifest, image_record, registry_creds)
[service:worker] 2018-02-07 15:04:00+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 105, in perform_analyze
[service:worker] 2018-02-07 15:04:00+0000 [-]     return(perform_analyze_localanchore(userId, manifest, image_record, registry_creds))
[service:worker] 2018-02-07 15:04:00+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 179, in perform_analyze_localanchore
[service:worker] 2018-02-07 15:04:00+0000 [-]     raise err
[service:worker] 2018-02-07 15:04:00+0000 [-] APIError: 500 Server Error: Internal Server Error ("{"message":"Get https://myregistry:443/v1/users/: x509: certificate signed by unknown authority"}")
[service:worker] 2018-02-07 15:04:00+0000 [-] [Thread-1605] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: 500 Server Error: Internal Server Error ("{"message":"Get https://myregistry:443/v1/users/: x509: certificate signed by unknown authority"}")
```

How do I fix this?

**Comment by zhill** [comment]
Hi @Kaitsh, it looks like there is an issue with respecting the '--insecure' option when the worker makes the handoff to the docker client to actually pull the image. We'll make the necessary code fix, but in the meantime if you want a workaround you can use the 'nodocker' driver if you're using a newer version of anchore-engine (0.1.5+). In _config.yaml_ you can set the _services.analyzer.analyzer_driver_ value to _nodocker_ and it will both respect the insecure flag as well as no longer requiring access to the local docker daemon for image operations.

We'll keep this issue open to track the fix for the 'localdocker' driver (the one you are currently using).

**Comment by nurmi** [comment]
hi @kaitsh

that error implies that the docker engine itself (which is running on the same host where the engine container is running) is not configured to allow pulls from the supplied registry.  anchore uses the insecure flag to access the registry for getting the image manifest, but the pull of the image data goes through docker , which also needs to be configured independently to allow insecure registry pulls.

here is the link i’ve used for testing insecure registries w docker:

https://docs.docker.com/registry/insecure/

as soon as you can sucessfully run a ‘docker pull <your-registry>:5000/<somerepo>:<sometag> on the host that is running the anchore-engine container, then anchore-engine should also be able to pull the same image!

note: as of anchore-engine 0.1.5, we also now support a ‘nodocker’ analyzer driver, which removes the requirement of having docker installed/exposed to anchore - see the ‘analyzer’ section of our example config.yaml to see how to enable the ‘nodocker’ driver, if that is preferable!

**Comment by Kaitsh** [comment]
Thanks! I found the issue and it was on my side. But nevertheless I will also try the 'nodocker' option. Keep up the great work! 👍
