### ISSUE TITLE
repository api

### ISSUE THREAD

**Issue by CodingJzy** [anchore/anchore-engine#271]
hello，I found that the tool's command line supports repo operations, such as adding the entire repoistory and deleting a repoistory to get the specified repo. watchand unwatchrepo. But the api has not been exposed. Api I only found the add operation

**Comment by nightfurys** [comment]
Hello @CodingJzy, fyi `anchore-cli repo del` removes a repository from the watch list. It does not delete already analyzed images. Subscription APIs are used for watching, un-watching and removing the repository from the watch list https://app.swaggerhub.com/apis/anchore/anchore-engine/0.1.10#/Subscriptions

**Comment by CodingJzy** [comment]
为什么不删除已分析的镜像呢？该仓库下的已分析的镜像没有存在意义了吧，，，

**Comment by nightfurys** [comment]
To delete an image, you can use `anchore-cli image del <image-id/digest/tag>` or the [images API](https://app.swaggerhub.com/apis/anchore/anchore-engine/0.1.10#/Images/delete_image). There is  a difference between deleting a repository and deleting an image. The former instructs anchore engine to stop scanning/watching a repository for new tags, existing image analyses are left untouched. The latter actually removes image analysis artifacts from anchore engine which is an irreversible action. We are aware that usage of `del` in repository context is a bit perplexing

**Comment by CodingJzy** [comment]
thank you
