### ISSUE TITLE
Cannot add password-protected registry

### ISSUE THREAD

**Issue by 0xDEC0DE** [anchore/anchore-engine#275]
Attempting to add a password-protected registry to Anchore yields a 406 `NOT ACCEPTABLE` error.

# Steps to Reproduce

```
$ anchore-cli --debug registry add devhub-docker.cisco.com multicloudesuite.gen $PW
```

# Expected Results

The registry is added and yields a 200 `OK`, 204 `NO CONTENT`, etc.

# Actual Behavior
```
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): anchore-nisimond.staging.ci.ciscolabs.com:443
DEBUG:urllib3.connectionpool:https://anchore-nisimond.staging.ci.ciscolabs.com:443 "GET / HTTP/1.1" 200 5
INFO:anchorecli.clients.apiexternal:As Account = None
DEBUG:anchorecli.clients.apiexternal:POST url=https://anchore-nisimond.staging.ci.ciscolabs.com/registries?validate=True
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): anchore-nisimond.staging.ci.ciscolabs.com:443
DEBUG:urllib3.connectionpool:https://anchore-nisimond.staging.ci.ciscolabs.com:443 "POST /registries?validate=True HTTP/1.1" 406 296
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 406
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://devhub-docker.cisco.com,multicloudesuite.gen) - exception: not enough values to unpack (expected 2, got 1)
HTTP Code: 406
Detail: {'error_codes': []}
```

> anchore-cli, version 0.4.0

> ```
> Name: anchore-engine
> Version: 0.5.0
> Summary: Anchore Engine
> Home-page: http://www.anchore.com
> Author: Anchore Inc.
> Author-email: dev@anchore.com
> License: Apache License 2.0
> Location: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages
> Requires: urllib3, yosai, connexion, retrying, passlib, PyYAML, prettytable, semantic-version, > jsonschema, pathlib, jmespath, botocore, zope.interface, pytz, zope.component, idna, > Authlib, swagger-spec-validator, six, chardet, toastedmarshmallow, prometheus-flask-exporter, typing, requests, Flask, Werkzeug, docutils, click, clickclick, boto3, psutil, python-keystoneclient, MarkupSafe, prometheus-client, python-swiftclient, watchdog, inflection, certifi, pg8000, Jinja2, SQLAlchemy, psycopg2-binary, itsdangerous, python-dateutil, Twisted, s3transfer
```

**Comment by zhill** [comment]
I've looked into this a bit and there is an issue with the auth request/response flow during the ping process. A workaround is to try with the registry add with `--skip-validate`. It should work for the actual image fetch/analyze operations but please reply here if it does not.

The fix for the credential check on the registry add operation is different code and the fix for that will be investigated.

**Comment by 0xDEC0DE** [comment]
That appears to work, and the registry shows up in `anchore-cli registry list` now.

We'll continue poking at it and let you know if there are any other problems that we can see.
