### ISSUE TITLE
preflight checks fail

### ISSUE THREAD

**Issue by tellmejeff** [anchore/anchore-engine#28]
I'm not having luck with the engine starting up because it hits a preflight check that fails:

anchore-engine_1  | 2018-02-16 19:49:36,145 ERROR policy_engine_bootstrap - Preflight checks failed with error: ("bad handshake: SysCallError(104, 'ECONNRESET')",). Aborting service startup
anchore-engine_1  | Traceback (most recent call last):
anchore-engine_1  |   File "/usr/bin/anchore-engine", line 128, in startup_service
anchore-engine_1  |     raise Exception("process exited: " + str(rc))
anchore-engine_1  | Exception: process exited: 1

This certainly smells like a network issue, but I don't see how to debug it from outside the container.

**Comment by tellmejeff** [comment]
There is a little more detail if I turn on debug logging, but not much:

anchore-engine_1  | 2018-02-16 20:08:50,107 INFO policy_engine_bootstrap - Registration complete.
anchore-engine_1  | 2018-02-16 20:08:50,112 INFO policy_engine_bootstrap - Checking feeds client credentials
anchore-engine_1  | 2018-02-16 20:08:50,114 DEBUG policy_engine_bootstrap - Initializing a feeds client
anchore-engine_1  | 2018-02-16 20:08:50,146 DEBUG policy_engine_bootstrap - init values: [None, None, None, (), None, None]
anchore-engine_1  | 2018-02-16 20:08:50,243 ERROR policy_engine_bootstrap - Preflight checks failed with error: ("bad handshake: SysCallError(104, 'ECONNRESET')",). Aborting service startup
anchore-engine_1  | Traceback (most recent call last):
anchore-engine_1  |   File "/usr/bin/anchore-engine", line 128, in startup_service
anchore-engine_1  |     raise Exception("process exited: " + str(rc))

**Comment by tellmejeff** [comment]
[config.yaml.txt](https://github.com/anchore/anchore-engine/files/1732676/config.yaml.txt)
[docker-compose.yaml.txt](https://github.com/anchore/anchore-engine/files/1732677/docker-compose.yaml.txt)

**Comment by tellmejeff** [comment]
[config.yaml.txt](https://github.com/anchore/anchore-engine/files/1732685/config.yaml.txt)
[docker-compose.yaml.txt](https://github.com/anchore/anchore-engine/files/1732686/docker-compose.yaml.txt)

**Comment by acathrow** [comment]
@tellmejeff does the engine have access to the network to download it's feed data?

**Comment by tellmejeff** [comment]
It's running as a privileged container. The instructions didn't explicitly state to configure a Docker network, but I suppose I could try that also.

**Comment by acathrow** [comment]
The engine will try and download feed data (CVEs, etc) if the default network blocks access then it'll fail.

**Comment by tellmejeff** [comment]
it would be helpful if I knew which sites it was trying to connect to, as I might be having issues with a firewall blocking certain domains.

**Comment by acathrow** [comment]
only to one:
ancho.re on port 443

**Comment by acathrow** [comment]
would a proxy help?

**Comment by tellmejeff** [comment]
hm... I can confirm that I can hit that directly with telnet.

**Comment by acathrow** [comment]
and there's no funny business with SSL interception etc?
By the way would slack be easier?

**Comment by tellmejeff** [comment]
no. I just ran a shell inside the container, and I can confirm that it can reach ancho.re:

[root@e8e1177c82b1 /]# ping ancho.re
PING ancho.re (104.28.12.5) 56(84) bytes of data.
64 bytes from 104.28.12.5 (104.28.12.5): icmp_seq=1 ttl=55 time=16.1 ms
64 bytes from 104.28.12.5 (104.28.12.5): icmp_seq=2 ttl=55 time=16.6 ms

but doing a curl shows the connection reset:

[root@e8e1177c82b1 /]# curl https://ancho.re
curl: (35) TCP connection reset by peer

Curl outside the container shows that it actually responds:

starkiller ~ # curl https://ancho.re
{
    "jse_shortmsg": "/ does not exist",
    "jse_info": {},
    "message": "/ does not exist",
    "statusCode": 404,
    "body": {
        "code": "ResourceNotFound",
        "message": "/ does not exist"
    },
    "restCode": "ResourceNotFound"
}

I can do slack, certainly.

**Comment by acathrow** [comment]
can you send me an email and I'll add you to slack :  andrewc@anchore.com

**Comment by tellmejeff** [comment]
I'm going to go ahead and close this issue since I now understand it and have a workaround.
