### ISSUE TITLE
Anchore Engine unable to pull docker image from private registry for scan

### ISSUE THREAD

**Issue by rohitri-90** [anchore/anchore-engine#282]
Hi

We are facing some issue with anchore engine and it's not able to pull the images from a  Jfrog docker registry in-spite of giving correct credentials during scan .
I have attached the error logs
[anchore-error.txt](https://github.com/anchore/anchore-engine/files/3730362/anchore-error.txt)

Please let me know if you need any other info

**Comment by zhill** [comment]
To see the full error message, please include the logs from the analyzer worker (pod anchore-anchore-engine-analyzer-7976c8d8fb-jlprb). That should include non-truncated error information.

**Comment by rohitri-90** [comment]
Hi @zhill 

This is the error log which is generated from analyzer worker:

[service:worker] 2019-10-15 11:06:47+0000 [-] [Thread-15341] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image: ['analyzer', 'dockerhub.<companyname>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d', 'dockerhub.<companyname>.com/cx-platform-docker/syslogms:1.0.0']
[service:worker] 2019-10-15 11:06:58+0000 [-] [Thread-15341] [anchore_engine.clients.skopeo_wrapper/download_image()] [ERROR] command failed with exception - Error encountered in skopeo operation. cmd=/bin/sh -c skopeo copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}" docker://dockerhub.<companyname>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d oci:/scratch/373967b5-87a3-478e-81b5-8398ae9cf158/raw:image, rc=1, stdout=None, stderr=b'time="2019-10-15T11:06:58Z" level=fatal msg="Error determining manifest MIME type for docker://dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d: Get https://dockerhub.<company-name>.com/v2/token?account=sopdcicd.gen&scope=repository%3Acx-platform-docker%2Fsyslogms%3Apull&service=dockerhub.<company-name>.com: dial tcp: lookup dockerhub.<companyname>.com on 10.211.0.2:53: read udp 10.233.76.57:43300->10.211.0.2:53: i/o timeout" \n'
[service:worker] 2019-10-15 11:06:58+0000 [-] anchore_engine.clients.skopeo_wrapper.SkopeoError: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}" docker://dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d oci:/scratch/373967b5-87a3-478e-81b5-8398ae9cf158/raw:image, rc=1, stdout=None, stderr=b'time="2019-10-15T11:06:58Z" level=fatal msg="Error determining manifest MIME type for docker://dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d: Get https://dockerhub.<company-name>.com/v2/token?account=sopdcicd.gen&scope=repository%3Acx-platform-docker%2Fsyslogms%3Apull&service=dockerhub.<company-name>.com: dial tcp: lookup dockerhub.<company-name>.com on 10.211.0.2:53: read udp 10.233.76.57:43300->10.211.0.2:53: i/o timeout" \n'
[service:worker] 2019-10-15 11:06:58+0000 [-] anchore_engine.clients.localanchore_standalone.ImagePullError: Failed to pull image (dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d) - exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}" docker://dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d oci:/scratch/373967b5-87a3-478e-81b5-8398ae9cf158/raw:image, rc=1, stdout=None, stderr=b'time="2019-10-15T11:06:58Z" level=fatal msg="Error determining manifest MIME type for docker://dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d: Get https://dockerhub.<company-name>.com/v2/token?account=sopdcicd.gen&scope=repository%3Acx-platform-docker%2Fsyslogms%3Apull&service=dockerhub.<company-name>.com: dial tcp: lookup dockerhub.<company-name>.com on 10.211.0.2:53: read udp 10.233.76.57:43300->10.211.0.2:53: i/o timeout" \n'
[service:worker] 2019-10-15 11:06:58+0000 [-] [Thread-15341] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: Failed to pull image (dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d) - exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}" docker://dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d oci:/scratch/373967b5-87a3-478e-81b5-8398ae9cf158/raw:image, rc=1, stdout=None, stderr=b'time="2019-10-15T11:06:58Z" level=fatal msg="Error determining manifest MIME type for docker://dockerhub.<company-name>.com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d: Get https://dockerhub.<company-name>.com/v2/token?account=sopdcicd.gen&scope=repository%3Acx-platform-docker%2Fsyslogms%3Apull&service=dockerhub.<company-name>.com: dial tcp: lookup dockerhub.<company-name>.com on 10.211.0.2:53: read udp 10.233.76.57:43300->10.211.0.2:53: i/o timeout" \n'

Thanks
Rohit

**Comment by prakashettigar** [comment]
Hi zhill
Any update on the above issue

**Comment by prakashettigar** [comment]
@zhill any update on above issue

**Comment by zhill** [comment]
Looks like core issue is:
```
[service:worker] 2019-10-15 11:06:58+0000 [-] anchore_engine.clients.skopeo_wrapper.SkopeoError: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}" docker://dockerhub..com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d oci:/scratch/373967b5-87a3-478e-81b5-8398ae9cf158/raw:image, rc=1, stdout=None, stderr=b'time="2019-10-15T11:06:58Z" level=fatal msg="Error determining manifest MIME type for docker://dockerhub..com/cx-platform-docker/syslogms@sha256:9145beacb4cf2a39de4457a14fa84afc43765ba53825454621a665947e7c180d: Get https://dockerhub..com/v2/token?account=sopdcicd.gen&scope=repository%3Acx-platform-docker%2Fsyslogms%3Apull&service=dockerhub..com: dial tcp: lookup dockerhub..com on 10.211.0.2:53: read udp 10.233.76.57:43300->10.211.0.2:53: i/o timeout" \n'
```

That looks like a failure getting a token for the account and there may be a typo in the name. I see two periods in the hostname `dockerhub..com`. Can you verify that value in your registry setting `anchore-cli registry list`. This may also just be a log copy-paste/Markdown issue but want to check.

**Comment by zebrastack** [comment]
any news on issue?

**Comment by zhill** [comment]
I am closing this out as stale. Please re-open or create a new issue if you still have issues pulling an image.
