### ISSUE TITLE
how to scaling anchore engine ?

### ISSUE THREAD

**Issue by lovewinxp** [anchore/anchore-engine#285]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
NO

**What happened**:
I see how to scaling anchore engine here, but there are no detailed steps. Can you tell me how to do it?edit config.yaml?
ps:I are installed anchore using docker compose

https://anchore.com/operational-awareness-and-performance-tuning-for-anchore-part-2-performance-tuning-tips/
![image](https://user-images.githubusercontent.com/29372171/67081367-94e0ed00-f1c9-11e9-83da-4f81a9368dbf.png)

**Comment by zhill** [comment]
`docker-compose up -d --scale analyzers=4` will run 4 analyzers. You don't need to do a `down` prior, just run the`up` command and set the service counts as needed.
