### ISSUE TITLE
Resource requests seems a bit high

### ISSUE THREAD

**Issue by jakubigla** [anchore/anchore-engine#305]
I deployed Anchore Engine with helm chart 1.2.0.
It's running 5 Anchore deployments + postgres deployment.

All of the Anchore resource requests are like 3GB of memory.
If I'm not using engine extensively, does it still need like 15GB all together?

**Comment by zhill** [comment]
We're constantly looking at memory usage and some is related to how Python3 does GC in combination with the wsgi framework we're using (twistd + flask), so often it won't immediately free the memory after its done with it.

Generally, the memory usage comes from processing large json documents in things like vulnerability feed updates and image analysis processing. We're aware this is less than ideal, and are working to address this need over time.

**Comment by zhill** [comment]
Memory usage by the policy engine during feed sync is something we're actively looking at. I'm going to close this question as answered, but please re-open if needed. Thanks! I'll reference this in the issue tracking the feed sync memory using work as well.

**Comment by frittentheke** [comment]
@zhill I just observed the same issue - extreme spikes in memory usage. Let me share what I got ...

This is the memory usage of the Kubernetes pod running the policy-engine. As you can see it runs into OOM with 8 GB [sic!] of memory limit

![anchore_policy_OOM](https://user-images.githubusercontent.com/13763987/72909707-bbb63e80-3d37-11ea-9a93-c2b2563b9e01.png)


Those were the last lines of log before the container ran OOM and was killed / restarted:

> [service:policy-engine] 2020-01-22 09:39:18+0000 [-] [Thread-8] [anchore_engine.services.policy_engine/handle_feed_sync_trigger()] [INFO] Feed Sync task creator complete
> [service:policy-engine] 2020-01-22 10:39:18+0000 [-] [Thread-8] [anchore_engine.services.policy_engine/handle_feed_sync_trigger()] [INFO] Feed Sync task creator activated
> [service:policy-engine] 2020-01-22 10:39:18+0000 [-] [Thread-8] [anchore_engine.services.policy_engine/handle_feed_sync_trigger()] [INFO] Feed Sync Trigger done, waiting for next cycle.
> [service:policy-engine] 2020-01-22 10:39:18+0000 [-] [Thread-8] [anchore_engine.services.policy_engine/handle_feed_sync_trigger()] [INFO] Feed Sync task creator complete
> [service:policy-engine] 2020-01-22 10:39:49+0000 [-] [Thread-9] [anchore_engine.services.policy_engine/handle_feed_sync()] [INFO] Feed sync task executor activated
> [service:policy-engine] 2020-01-22 10:39:49+0000 [-] [Thread-14441] [anchore_engine.services.policy_engine/do_feed_sync()] [INFO] FIRING: feed syncer
> [service:policy-engine] 2020-01-22 10:39:49+0000 [-] [Thread-14441] [anchore_engine.services.policy_engine/do_feed_sync()] [INFO] Syncing configured feeds: ['vulnerabilities', 'nvdv2', 'snyk']
> [service:policy-engine] 2020-01-22 10:39:49+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Starting feed update
> [service:policy-engine] 2020-01-22 10:39:49+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Performing feed sync of feeds: ['vulnerabilities', 'nvdv2', 'snyk']
> [service:policy-engine] 2020-01-22 10:39:49+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group metadata for vulnerabilities feed
> [service:policy-engine] 2020-01-22 10:39:51+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group metadata for nvdv2 feed
> [service:policy-engine] 2020-01-22 10:39:53+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group metadata for snyk feed
> [service:policy-engine] 2020-01-22 10:39:55+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/warn()] [WARN] Cannot sync group metadata for snyk feed, may not be available in the feed source
> [service:policy-engine] 2020-01-22 10:39:55+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing vulnerability feed
> [service:policy-engine] 2020-01-22 10:39:56+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: alpine:3.9
> [service:policy-engine] 2020-01-22 10:39:57+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.6393108367919922 sec
> [service:policy-engine] 2020-01-22 10:39:57+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ol:6
> [service:policy-engine] 2020-01-22 10:40:00+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 2.744598865509033 sec
> [service:policy-engine] 2020-01-22 10:40:00+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:16.10
> [service:policy-engine] 2020-01-22 10:40:00+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.2706761360168457 sec
> [service:policy-engine] 2020-01-22 10:40:00+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: centos:8
> [service:policy-engine] 2020-01-22 10:40:00+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.2621152400970459 sec
> [service:policy-engine] 2020-01-22 10:40:00+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: alpine:3.4
> [service:policy-engine] 2020-01-22 10:40:01+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.24825215339660645 sec
> [service:policy-engine] 2020-01-22 10:40:01+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: alpine:3.5
> [service:policy-engine] 2020-01-22 10:40:01+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.26726555824279785 sec
> [service:policy-engine] 2020-01-22 10:40:01+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: centos:5
> [service:policy-engine] 2020-01-22 10:40:01+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.38320040702819824 sec
> [service:policy-engine] 2020-01-22 10:40:01+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: alpine:3.6
> [service:policy-engine] 2020-01-22 10:40:02+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.3306751251220703 sec
> [service:policy-engine] 2020-01-22 10:40:02+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:15.10
> [service:policy-engine] 2020-01-22 10:40:02+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.3642735481262207 sec
> [service:policy-engine] 2020-01-22 10:40:02+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:18.04
> [service:policy-engine] 2020-01-22 10:40:03+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.7543947696685791 sec
> [service:policy-engine] 2020-01-22 10:40:03+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: alpine:3.3
> [service:policy-engine] 2020-01-22 10:40:03+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.45960402488708496 sec
> [service:policy-engine] 2020-01-22 10:40:03+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:12.04
> [service:policy-engine] 2020-01-22 10:40:04+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.28583550453186035 sec
> [service:policy-engine] 2020-01-22 10:40:04+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:12.10
> [service:policy-engine] 2020-01-22 10:40:04+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.2608659267425537 sec
> [service:policy-engine] 2020-01-22 10:40:04+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:13.04
> [service:policy-engine] 2020-01-22 10:40:04+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.30280089378356934 sec
> [service:policy-engine] 2020-01-22 10:40:04+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:16.04
> [service:policy-engine] 2020-01-22 10:40:04+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.29491114616394043 sec
> [service:policy-engine] 2020-01-22 10:40:04+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: alpine:3.8
> [service:policy-engine] 2020-01-22 10:40:05+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.2529006004333496 sec
> [service:policy-engine] 2020-01-22 10:40:05+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:17.10
> [service:policy-engine] 2020-01-22 10:40:05+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.4795491695404053 sec
> [service:policy-engine] 2020-01-22 10:40:05+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: debian:7
> [service:policy-engine] 2020-01-22 10:40:05+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.27602338790893555 sec
> [service:policy-engine] 2020-01-22 10:40:05+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ol:8
> [service:policy-engine] 2020-01-22 10:40:06+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.4478950500488281 sec
> [service:policy-engine] 2020-01-22 10:40:06+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:14.04
> [service:policy-engine] 2020-01-22 10:40:06+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.36255407333374023 sec
> [service:policy-engine] 2020-01-22 10:40:06+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: centos:6
> [service:policy-engine] 2020-01-22 10:40:08+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 1.5805583000183105 sec
> [service:policy-engine] 2020-01-22 10:40:08+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: alpine:3.7
> [service:policy-engine] 2020-01-22 10:40:08+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.251664400100708 sec
> [service:policy-engine] 2020-01-22 10:40:08+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ol:7
> [service:policy-engine] 2020-01-22 10:40:08+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.29665207862854004 sec
> [service:policy-engine] 2020-01-22 10:40:08+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: debian:9
> [service:policy-engine] 2020-01-22 10:40:09+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.6565611362457275 sec
> [service:policy-engine] 2020-01-22 10:40:09+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:17.04
> [service:policy-engine] 2020-01-22 10:40:10+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.3638138771057129 sec
> [service:policy-engine] 2020-01-22 10:40:10+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:15.04
> [service:policy-engine] 2020-01-22 10:40:10+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.2732689380645752 sec
> [service:policy-engine] 2020-01-22 10:40:10+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:19.10
> [service:policy-engine] 2020-01-22 10:40:10+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.2678353786468506 sec
> [service:policy-engine] 2020-01-22 10:40:10+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:19.04
> [service:policy-engine] 2020-01-22 10:40:10+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.2581801414489746 sec
> [service:policy-engine] 2020-01-22 10:40:10+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: amzn:2
> [service:policy-engine] 2020-01-22 10:41:11+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 60.53187298774719 sec
> [service:policy-engine] 2020-01-22 10:41:11+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: debian:8
> [service:policy-engine] 2020-01-22 10:41:11+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.5770089626312256 sec
> [service:policy-engine] 2020-01-22 10:41:11+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: alpine:3.10
> [service:policy-engine] 2020-01-22 10:41:12+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.4422295093536377 sec
> [service:policy-engine] 2020-01-22 10:41:12+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: debian:unstable
> [service:policy-engine] 2020-01-22 10:41:12+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.46239256858825684 sec
> [service:policy-engine] 2020-01-22 10:41:12+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:18.10
> [service:policy-engine] 2020-01-22 10:41:13+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.4321897029876709 sec
> [service:policy-engine] 2020-01-22 10:41:13+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ubuntu:14.10
> [service:policy-engine] 2020-01-22 10:41:13+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.4583005905151367 sec
> [service:policy-engine] 2020-01-22 10:41:13+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: ol:5
> [service:policy-engine] 2020-01-22 10:41:14+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.4472782611846924 sec
> [service:policy-engine] 2020-01-22 10:41:14+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: debian:11
> [service:policy-engine] 2020-01-22 10:41:16+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 1.9241089820861816 sec
> [service:policy-engine] 2020-01-22 10:41:16+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: debian:10
> [service:policy-engine] 2020-01-22 10:41:16+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.5213606357574463 sec
> [service:policy-engine] 2020-01-22 10:41:16+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: centos:7
> [service:policy-engine] 2020-01-22 10:41:17+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 0.42244601249694824 sec
> [service:policy-engine] 2020-01-22 10:41:17+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing nvdv2 feed
> [service:policy-engine] 2020-01-22 10:41:17+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: nvdv2:cves
> [service:policy-engine] 2020-01-22 10:49:08+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Group data fetch took 470.70880341529846 sec
> [service:policy-engine] 2020-01-22 10:49:08+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Merging 5000 records from group nvdv2:cves
> [service:policy-engine] 2020-01-22 11:33:43+0000 [-] [Thread-14442] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Db merge took 2675.396125793457 sec
>

**Comment by frittentheke** [comment]
@zhill could you kindly reopen this and label it a bug / issue, it's really not a question.

**Comment by zuehlke-dea** [comment]
Are there any news about this issue? We see the same behaviour.
