### ISSUE TITLE
Centos/RHEL RPM vulnerabilities not being discovered

### ISSUE THREAD

**Issue by nodanero** [anchore/anchore-engine#308]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
cli: 0.4.0
engine: 0.5.2
 
**What happened**:
Recent changes in in anchore or anchore feeds around November 14th seem to have reduced the number of detected vulnerabilities at OS layer. Noticed in RPMs for Centos/RHEL.

**What did you expect to happen**:
The vulnerability scanner should match a high number of vulnerabilities.

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:
https://hub.docker.com/r/anchore/anchore-engine/
anchore-engine:v0.5.2

**How to reproduce the issue**:
- Install anchore with Helm
- Wait for the feeds to sync
- Scan a Centos/RHEL container image with vulnerabilities at in the RPMs.

**Anything else we need to know**:
The vulnerabilities detection changed around November 14th in our environment, from detection RHSA java issues to only CVEs. A redeployment of Anchore with a new version reported the same level of vulnerabilities.

**Comment by nightfurys** [comment]
@nodanero, thank you for bringing this to our attention! We found that RHSA data went through a major update on the 13th of November 2019. This has caused issues in our upstream service (ancho.re) that maintains vulnerability data for RHEL/centos. We are currently working on a fix and I'll post updates to this ticket when its done

**Comment by nightfurys** [comment]
Hello @nodanero, we have fixed our upstream service to work with RHSA data updates. If you have anchore engine running, the periodic feed sync will pull down the updates and you should be able to see vulnerability matches similar to what you've seen before the issue. Please let us if that's the case and I'll close the issue

**Comment by nodanero** [comment]
Seems to be working now. Thanks!
