### ISSUE TITLE
 How to scale up analyzer in anchore engine

### ISSUE THREAD

**Issue by praneethr** [anchore/anchore-engine#31]
We started using anchore for scanning images, when we trigger 10 jobs for scanning images, it going to 30 mins or more. Documentation say it is possible can you let us know how to scale up the analyzer.
https://anchore.freshdesk.com/support/solutions/articles/36000020643-analyzing-images

**Comment by acathrow** [comment]
What platform are you running Anchore on?
We have a deployment repository here: https://github.com/anchore/anchore_deployment that covers simple and scale out deployments on Kubernetes.
If you are using Helm then we have a helm chart that can build a simple or scalable depoyment:
https://anchore.com/blog/installing-anchore-single-command-using-helm/

We are working on an ECS cloudformation template now.

**Comment by praneethr** [comment]
@acathrow , We are installed anchore using docker compose .. https://github.com/anchore/anchore-engine/wiki/Installation#running-anchore-engine-using-docker-compose

**Comment by nurmi** [comment]
@praneethr - we wanted to check in to see if you're still encountering an issue with image analysis timing or have already scaled up the worker pool to increase analysis throughput - let us know if we can help!

**Comment by praneethr** [comment]
@nurmi We are not able to get it working with Kubernetes on scaling up with worker pool using helm, we are using custom DB that is only the change. But we are seeing below errors in the logs

Analyzer (Worker pod logs): 

construct service base_url - please check service configuration for hostname/port settings
[service:analyzer] 2018-06-13 18:29:39+0000 [-] [bootstrap] [ERROR] cannot start service (see above for information)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_engine/services/common.py", line 366, in makeService
    rc = smodule.registerService(sname, localconfig)
  File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 112, in registerService
    rc = anchore_engine.services.common.registerService(sname, config, enforce_unique=False)
  File "/usr/lib/python2.7/site-packages/anchore_engine/services/common.py", line 197, in registerService
    raise Exception("could not construct service base_url - please check service configuration for hostname/port settings")
Exception: could not construct service base_url - please check service configuration for hostname/port settings
Traceback (most recent call last):
  File "/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==17.5.0', 'console_scripts', 'twistd')()
Worker Config is default one.

**Comment by nurmi** [comment]
Hi @praneethr ,

It's likely that one of the new constraints in the 0.2.X code is preventing the startup of the analyzer - we now require that endpoint_hostname, list, and port are set for all services (including the analyzer), in your config.yaml.  Our example install config for the docker-compose installation reflects this update as well (to see a default example) - https://raw.githubusercontent.com/anchore/anchore-engine/master/scripts/docker-compose/config.yaml

Note that although you now need to enable endpoint_hostname/listen/port for the analyzer (like all the other services), you do not need to expose that port, unless you intend to enable prometheus metrics or other health checks based on directly pinging the services.

Let us know if that resolves your issue!

**Comment by praneethr** [comment]
Hi @nurmi , Thanks for the help now i updated worker config and redeployed helm chart, Analzer cann't locate Simple Queue.

Below is the error:
[service:worker] 2018-06-14 16:59:44+0000 [-] [Thread-7] [anchore_engine.services.analyzer/handle_image_analyzer()] [ERROR] could not find valid endpoint for service (simplequeue) - exception: cannot locate registered and available service in config/DB: simplequeue
[service:worker] 2018-06-14 17:01:55+0000 [-] Traceback (most recent call last):
[service:worker] 2018-06-14 17:01:55+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 563, in handle_image_analyzer
[service:worker] 2018-06-14 17:01:55+0000 [-]     qobj = simplequeue.dequeue(system_user_auth, queuename)
[service:worker] 2018-06-14 17:01:55+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/simplequeue.py", line 151, in dequeue
[service:worker] 2018-06-14 17:01:55+0000 [-]     ret = http.anchy_aa(http.anchy_get, base_urls, url_postfix, auth=auth, headers=headers, verify=verify)
[service:worker] 2018-06-14 17:01:55+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/http.py", line 329, in anchy_aa
[service:worker] 2018-06-14 17:01:55+0000 [-]     raise last_exc

Below is the snipped of updated worker configmap:

        db_connect_args:
          timeout: 120
          ssl: {{ .Values.globalConfig.dbConfig.ssl }}
        db_pool_size: {{ .Values.globalConfig.dbConfig.connectionPoolSize }}
        db_pool_max_overflow: {{ .Values.globalConfig.dbConfig.connectionPoolSize }}
    services:
      analyzer:
        enabled: true
        cycle_timer_seconds: {{ .Values.workerConfig.cycleTimerSeconds }}
        max_threads: {{ .Values.workerConfig.concurrentTasksPerWorker }}
        analyzer_driver: {{ .Values.workerConfig.analyzerMode }}
        ssl_cert: {{ .Values.workerConfig.ssl.certDir -}}/{{- .Values.workerConfig.ssl.certSecretCertName }}
        ssl_key: {{ .Values.workerConfig.ssl.certDir -}}/{{ .Values.workerConfig.ssl.certSecretKeyName }}
        ssl_enable: {{ .Values.globalConfig.internalServicesSslEnabled }}
        endpoint_hostname:  {{ template "fullname" . }}
        listen: '0.0.0.0'
        port: 8084

**Comment by nurmi** [comment]
hi @praneethr

the analyzer will attempt to contact the simplequeue service to get work, and the error is indicating that the simplequeue service is either failing to come up, or is not yet available- does that error continue to display after a couple of minutes?  if so, the next thing to check is the core service container, to revoew the status of the simplequeue service (look at the logs for the core service container)

**Comment by praneethr** [comment]
Hi @nurmi 

Thanks for suggestion on looking in deep i found out that worker and core startup looks like service are taking previous  fullname as service. 

[service:catalog] 2018-06-15 11:19:44+0000 [-] [Thread-13] [anchore_engine.services.catalog/handle_service_watcher()] [WARN] no service heartbeat within max allowed time period ([u'c0991c5c-25d0-4322-968a-5bef9c6112c3', u'http://loopy-dolphin-anchore-engine:8084'] - orphaning service
[service:catalog] 2018-06-15 11:19:44+0000 [-] [Thread-13] [anchore_engine.services.catalog/handle_service_watcher()] [WARN] no service heartbeat within max allowed time period ([u'218ce747-7c45-4d0c-ba82-ece37d561de2', u'http://mothy-wolf-anchore-engine:8084'] - orphaning service


---
[service:catalog] 2018-06-15 11:20:18+0000 [-] [Thread-98] [anchore_engine.services.catalog/schedule_watcher()] [WARN] failed to enqueue watcher task: failed post url=http://vocal-blackbird-anchore-engine-k8s:8083/v1/queues/watcher_tasks/is_inqueue

but running was vocal-blackbird and old once (mothy-wolf and loopy-dolphin) were deleted.

**Comment by praneethr** [comment]
Hi @nurmi , We found the issue, Simple queue is not able to access in Core Pod because of hairpin-mode, we are azure CNI as network and it is not allowing traffic where source and destination pod are same.
So can we have all services (Core services and Analyser) running on pod and can i replicate the Pod as load?

**Comment by nurmi** [comment]
hi @praneethr,

I'd like to ask what the current status is of your deployment and this issue in particular?  If I read correctly, the original issue was resolved but there may be some pending related questions so I wanted to check back in.

**Comment by nurmi** [comment]
hi @praneethr - some time has passed and I'll close this issue - please re-open if you would like to discuss the issue further or provide an update / new issue if there is an issue we can help resolve!

**Comment by praneethr** [comment]
@nurmi , Sorry for delayed response. I created seperate Pods and servcies to get anchore working on Azure Kubernetes Service. Thanks for the help, you may close the case.

**Comment by nurmi** [comment]
Great to hear @praneethr !  Thank you

**Comment by Manish789** [comment]
Hi @acathrow . You mentioned that you were working on ECS cloudformation template. 
Any update on that. 

The reason of asking is that I have setup anchore on ECS, but it seems to be unstable in giving results.
