### ISSUE TITLE
The license field needs better individual license delimiting

### ISSUE THREAD

**Issue by juledwar** [anchore/anchore-engine#313]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
FEATURE REQUEST

The license field today is a single string field of space-separated licenses. This would be fine except in the case where a license itself has spaces in it.

I would request that the license field be a pure JSON list field instead so it's easier for API clients to parse.

**Comment by nurmi** [comment]
Thanks @juledwar for the suggestion - I agree that the value for this field should be a proper list.  The change would be pretty straightforward but we'll need to consider API compatibility a bit carefully (RFC @zhill ), we'll post status and updates here.

**Comment by juledwar** [comment]
Yep, backwards compat is important. I'd be fine with a new field, say `licenses` instead of just `license`.
________________________________

**Comment by zhill** [comment]
Agreed, a new field and an indication that the old one will be deprecated is needed. A JSON array is the right type.

**Comment by zhill** [comment]
https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/apiext/swagger/swagger.yaml#L3176
