### ISSUE TITLE
Security issue - passwords in database

### ISSUE THREAD

**Issue by m1ch41** [anchore/anchore-engine#314]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT
 
Password to authenticating with Anchore-engine is stored plain text, in database.
Please use salt in database for passwords.
 anchore/anchore-engine:v0.5.2
**Version of Anchore Engine and Anchore CLI if applicable**:

**Comment by nurmi** [comment]
Hi @m1ch41 

Anchore supports a few authentication methods as well as credential storage modes - to configure anchore to store hashed credentials, the best place to go is on our docs site which describes how to configure these modes! 

https://docs.anchore.com/current/docs/engine/engine_installation/configuration/user_credential_storage/

I'll close out the ticket, feel free to re-open a new ticket or this one if the docs/modes don't satisfy your requirements.
