### ISSUE TITLE
cve2 database can't be bootstrapped

### ISSUE THREAD

**Issue by aquator** [anchore/anchore-engine#317]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**: 0.5.2

 
**What happened**: Can't sync cve2 database for the first time, after a while merge times get over 1000 sec, then the policy engine container dies with a http timeout coming from a python request (60 sec timeout, probably some check, stacktrace was not really useful)

**What did you expect to happen**: Expect to be able to download full cve2 db with 8gigs of ram (4 is required accoording to docs)

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**: used compose from 0.5.2 tag, and also tried latest

**How to reproduce the issue**: follow the documentation, turn on the cve2 in config, and restart.... it will die within a couple of hours, tested in multiple machines and vms

**Anything else we need to know**:
My hunch is merging can't handle the amount of records. I've patched the python code to do commit after each merge instead of at the end of the full synch, so I could see records appearing, a light check indicated all the CVEs are downloaded, at least it went till the very end, 9.95 million records were added.

Then I pathced the last synch date in both tables (why redundant??) so it can live now, and also confirmed to download some new patches since.

I'd like to mention that the method of checking what needs to be downloaded is really bad: my last update indicates what needs to be downloaded. The proper way would be checking/storing the latest found CVE in the db, and query anything newer then that. In that case the DB could be kept up-to-date from a partial initial sync state.

**Comment by zhill** [comment]
The timeout is from the upstream data fetch to the feed service. If you're still seeing that please let us know. In the new release (coming out in the next day or so) we've added retries to avoid that causing the sync to fail.

Re the merge: see #284, that is planned work.

**Comment by aquator** [comment]
Looks great, thanks. I’ll check the new release from scratch early next week then and get back to you.

**Comment by aquator** [comment]
0.6.0 works like a charm, I suspect you already do some prepared db for this? I mean this was lightning fast this time (though the engine-api logs looked spooky first not being able to connect to the database)

Thanks for the fix & update!
