### ISSUE TITLE
list returned from checks contains duplicates

### ISSUE THREAD

**Issue by aquator** [anchore/anchore-engine#318]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**: 0.5.2

 
**What happened**:
listing the found vulnerabilities contains multiple indentical lines in the output. That is not at all useful, also causes the jenkins plugin to create entries for the same issue over and over again.

**What did you expect to happen**:
The same vulnerability should not appear multiple times in the output, unless there is something makes them unique. It has no point showing the same lines 8-10 times.

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**: from compose, as described in docs (open source)

**How to reproduce the issue**: run a scan against an image with cve2 on an image has some issues, it works with openjdk jre 11.0.5 for example 

**Anything else we need to know**:

**Comment by zhill** [comment]
The diff in these entries is typically the path of the package. For things like java jars, they can be in multiple places on the FS so you'll get multiple matches. The field in the API response is the package_path that varies in that case. This may just be an issue in the jenkins plugin.

**Comment by aquator** [comment]
Ah, that makes sense! However, the default cli text output does not show any difference. I’ll check the docs on different output formats, but the default is still confusing this way, used sort -u to make it less bloat. 

Maybe the plugin uses the same text output too, have too dig into that.

**Comment by aquator** [comment]
okay, so the thing is:
` anchore-cli image vuln <image> all | wc -l` retuns 319
while
`anchore-cli image vuln <image> all | sort -u | wc -l` returns 148

That means half of the data returned is unnecessary. Accoording to vuln --help, there is no way to get any detailed data, or other format.

**Comment by zhill** [comment]
To see the full response data use `anchore-cli --json image vuln...`

We'll look at adding a column or a '--full' option to the cli to show more info.

**Comment by aquator** [comment]
Great, thank you!

**Comment by zhill** [comment]
Related to: anchore/anchore-cli#43

**Comment by zhill** [comment]
Closing this issue and will track the update in the CLI issue referenced above.
