### ISSUE TITLE
Read-only file system: '/config/host_id.json' in anchore-engine-core on kubernetes 1.8 and 1.8 GKE

### ISSUE THREAD

**Issue by rawlingsj** [anchore/anchore-engine#32]
I've been trying to run anchore via it's 0.1.4 helm chart https://hub.kubeapps.com/charts/stable/anchore-engine/0.1.4 on GKE with kubernetes v1.8 and v1.9. 
 `anchore-engine-worker` and `postgresql` pods start fine but `anchore-engine-core` pod fails to be `ready`

My guess is it's related to https://github.com/kubernetes/kubernetes/pull/58720

In the logs I can see:
```
[service:catalog] 2018-03-21 23:51:48+0000 [-] [bootstrap] [ERROR] cannot load configuration: exception - [Errno 30] Read-only file system: '/config/host_id.json'
Traceback (most recent call last):
  File "/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==17.5.0', 'console_scripts', 'twistd')()
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 440, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/usr/lib/python2.7/site-packages/twisted/plugins/anchore_catalog.py", line 76, in makeService
    r = anchore_engine.services.common.makeService(slist, options, bootstrap_db=True, bootstrap_users=True)
  File "/usr/lib/python2.7/site-packages/anchore_engine/services/common.py", line 315, in makeService
    raise err
IOError: [Errno 30] Read-only file system: '/config/host_id.json'
Traceback (most recent call last):
  File "/usr/bin/anchore-engine", line 128, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
```

**Comment by nurmi** [comment]
Greeting @rawlingsj - really appreciate the reference to the recent k8s patch, I agree at first look that it is likely related, as anchore-engine does write some small files to the local configuration volume on first startup.  We'll investigate and follow up on this ticket!

Note that, if 'host_id' is explicitly set in the anchore-engine config.yaml, it will skip writing out to /config/host_id.json.  However there are some other files that will be copied over there as well, so while this could get past the first instance if the issue, there will be a few more after this point in the anchore-engine bootstrap.

**Comment by rawlingsj** [comment]
Ok thanks for the fast response - I've got it building locally so can try to debug further configs, add them to the configmap and see if we can get further.  Will post my findings back.

**Comment by zhill** [comment]
Hi @rawlingsj , yes I see what you're saying and have reproduced the issue. The issue you referenced is indeed the cause, so it will only be seen on new k8s releases.

The core issue is the default files copied into that location. The chart statically sets the host_id in the configmap itself using an environment variable but it looks like that substitution is done after the config is loaded and host_id.json dropped to the FS during initial bootstrap script.

This will result in an anchore code update, but I'll see if I can find a helm/k8s workaround for now to get you unblocked without requiring a new release of the anchore container. Updates to follow.

**Comment by rawlingsj** [comment]
OK sounds great @zhill!  FWIW I've got anchore-engine building locally as well as building the docker image so I can hack any code changes to test stuff out if that's easier.  I don't know python but with a bit of guidance or a fork to clone I can test out changes too.  No rush though, whatever is easiest for you.

**Comment by nurmi** [comment]
Hi all,

Upon further investigation, we've determined that the existing anchore-engine chart can be run with a parameter that will set the 'service_dir' in config.yaml to a non-config volume location, which is the crux of the issue.  To do this, the command would be

```
helm install stable/anchore-engine --set globalConfig.configDir=/path/to/writable/directory
e.g.
helm install stable/anchore-engine --set globalConfig.configDir=/anchore_service_dir
```

anchore-engine will create and then use that directory, so it should be set to something that either exists and is empty (and writable), or doesn't exist but can be created (and written to).

Moving forward, we'll be changing the default setting for that parameter in the helm chart with something similiar to /anchore_service_dir, at which point it won't be necessary any longer to specify on helm install (though it would still work if one did!)

We'll keep this ticket open until the helm chart update is done, but the above should get things going against k8s 1.8/1.9/1.10!

Best
_Dan

**Comment by rawlingsj** [comment]
That worked great! Many thanks @nurmi!

**Comment by nurmi** [comment]
Update on this issue - the anchore-engine helm chart has been updated to set the service directory location by default (though the manual approach as defined here will also continue to work!).
