### ISSUE TITLE
Error: image cannot be found/fetched from registry

### ISSUE THREAD

**Issue by dawaj71** [anchore/anchore-engine#33]
Hello :-),

I use anchore engine for two days now and when i want to add an image on my machine (in local) i have this error : Error: image cannot be found/fetched from registry. I didn't create a registry, my images are stored on my machine.

I  can add images that I have pulled from dockerhub, but It doesn't work from images that I have created / pulled from my private registry.

docker logs (anchore container)

> [service:catalog] 2018-03-27 10:03:39+0000 [_GenericHTTPChannelProtocol,4,127.0.0.1] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.skopeo_wrapper/get_image_manifest_skopeo()] [ERROR] command failed with exception - command failed: cmd=/bin/sh -c skopeo inspect --raw --tls-verify=false  docker://docker.io/library/planningdatabase:latest exitcode=1 stdout= stderr=time="2018-03-27T10:03:39Z" level=fatal msg="errors:
[service:catalog]       denied: requested access to the resource is denied
[service:catalog]       unauthorized: authentication required
[service:catalog]       "
[service:catalog] 2018-03-27 10:03:39+0000 [_GenericHTTPChannelProtocol,4,127.0.0.1] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.skopeo_wrapper/get_image_manifest_skopeo()] [WARN] CMD failed - exception: command failed: cmd=/bin/sh -c skopeo inspect --raw --tls-verify=false  docker://docker.io/library/planningdatabase:latest exitcode=1 stdout= stderr=time="2018-03-27T10:03:39Z" level=fatal msg="errors:
[service:catalog]       denied: requested access to the resource is denied
[service:catalog]       unauthorized: authentication required
[service:catalog]       "
[service:catalog] 2018-03-27 10:03:39+0000 [_GenericHTTPChannelProtocol,4,127.0.0.1] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.docker_registry/get_image_manifest()] [ERROR] could not fetch manifest/digest: no digest/manifest from skopeo
[service:catalog] 2018-03-27 10:03:39+0000 [_GenericHTTPChannelProtocol,4,127.0.0.1] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.docker_registry/get_image_manifest()] [ERROR] could not get manifest/digest for image using any auth method: (latest):
[service:catalog] 2018-03-27 10:03:39+0000 [-] "127.0.0.1" - - [27/Mar/2018:10:03:39 +0000] "POST /v1/image?tag=planningdatabase:latest HTTP/1.1" 404 192 "-" "python-requests/2.17.3"

my docker compose: 

> version: '2'
services:
  anchore-engine:
    #image: "anchore-engine"
    image: docker.io/anchore/anchore-engine:latest
    privileged: true
    environment:
      - http_proxy=http://myproxy
      - https_proxy=http://myproxy
      - no_proxy=/var/run/docker.sock,,localhost,127.0.0.1
    depends_on:
     - anchore-db
    ports:
     - "8228:8228"
     - "8338:8338"
    volumes:
     - /root/aevolume/config:/config/:Z
     #- /var/run/docker.sock:/var/run/docker.sock
    logging:
     driver: "json-file"
     options:
      max-size: 100m
  anchore-db:
    image: "postgres:9"
    environment:
      - http_proxy=http://myproxy
      - https_proxy=http://myproxy
      - no_proxy=/var/run/docker.sock,,localhost,127.0.0.1
    volumes:
     - /root/aevolume/db/:/var/lib/postgresql/data/pgdata/:Z
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata/
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    #uncomment to expose a port to allow direct/external access to the DB, for debugging
    #ports:
    # - "2345:5432"

if someone can help me ^^

**Comment by acathrow** [comment]
Looking at the error message I see: "docker.io/library/planningdatabase:latest"
You didn't mention the command you ran, but I'd presume it was `anchore-cli image add planningdatabase`

If you don't specify a registry we'll presume docker.io/library so we try to pull docker.io/library/planningdatabase:latest and then get an not-authorized error from dockerhub.

The engine will try and pull the images from a registry it cannot pull from a docker daemon. It's something we have considered since there's an interesting use case there, but there will be some limitations of this feature if we add it.
In the mean time can you push the images to a local registry that we can pull from?

By the way we also have a slack channel where there are other community members who can help.
If you'd like an invitation you can email slack@anchore.com

**Comment by acathrow** [comment]
This issue was resolved by creating a registry that the image could be pulled from.

**Comment by dawaj71** [comment]
here the docker-compose if someone want it:

> version: '2'
services:
  anchore-engine:
    #image: "anchore-engine"
    image: docker.io/anchore/anchore-engine:latest
    privileged: true
    depends_on:
     - anchore-db
    environment:
      - http_proxy=myproxy
      - https_proxy=myproxy
      - no_proxy=localhost,
    ports:
     - "8228:8228"
     - "8338:8338"
    volumes:
     - /root/aevolume/config:/config/:Z
     #- /var/run/docker.sock:/var/run/docker.sock
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    networks:
      - my_network
  anchore-db:
    image: "postgres:9"
    volumes:
     - /root/aevolume/db/:/var/lib/postgresql/data/pgdata/:Z
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata/
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    #uncomment to expose a port to allow direct/external access to the DB, for debugging
    #ports:
    # - "2345:5432"
    networks:
      - my_network
  registry.com:
    privileged: true
    image: "registry:2"
    volumes:
     - /opt/docker-registry/auth:/auth
     - /opt/docker-registry/data:/var/lib/registry
     - /opt/docker-registry/certs:/certs
    ports:
     - "5000:5000"
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry_auth.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry_auth.key
    networks:
      - my_network
networks:
  my_network:
