### ISSUE TITLE
RFE: Add vendor_only data to vuln records

### ISSUE THREAD

**Issue by cburgess** [anchore/anchore-engine#333]
**Is this a request for help?**:

No
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

Feature Request

The GET /images/{imageDigest}/vuln/{vtype} call has a vendor_only flag today that controls if anchore will return vulnerability for an image that the vendor has marked as "won't fix". Today is only applies to vulnerabilities found in the Debian feeds that have been marked with no-dsa in the Debian bug tracker (see https://security-team.debian.org/security_tracker.html for details).

Anchore does not presently expose this fact in the record returned by the GET /images/{imageDigest}/vuln/{vtype} or the GET /query/vulnerabilities call. As a result if you want to know if a particular vulnerability matches this criteria you have to make a call to GET /images/{imageDigest}/vuln/{vtype} with the flag set and another call without the flag set and compare the results.

Anchore should provide an attribute in the response to both GET /images/{imageDigest}/vuln/{vtype} and GET /query/vulnerabilities that indicate if a specific vulnerability matches this vendor_only criteria or not. The field should always be present and probably be a boolean to align with how the flag to the API call works.

**Comment by anchoresupport** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [vendor_only data in vuln query](https://trello.com/c/fnA4zyuh/148-vendoronly-data-in-vuln-query)

**Comment by Toure** [comment]
@cburgess Thanks for bringing this RFE to our attention, this issue has been addressed in the new release of Engine v0.10.1.
