### ISSUE TITLE
Ability to apply Regexes on ARG and ENV

### ISSUE THREAD

**Issue by madchap** [anchore/anchore-engine#355]
**Is this a request for help?**:
No.

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
FEATURE REQUEST

It would be great to be able to use regexes on ARG and ENV for Dockerfile checks, which AFAIK is not possible today.

**Comment by zhill** [comment]
The 'like' and 'not_like' operators for the dockerfile.instruction trigger does an re.match() check. Can you see if that achieves what you're looking for?

**Comment by madchap** [comment]
Actually, it should :) Sorry for the noise.
