### ISSUE TITLE
API documentation missing?

### ISSUE THREAD

**Issue by Sh4d1** [anchore/anchore-engine#38]
**Is this a request for help?**:

Question. I wanted to write a go API for anchore-engine but I cannot find any API documentation. Is there one somewhere or should I juste read the CLI code?

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
Feature request

**Comment by acathrow** [comment]
https://anchore.freshdesk.com/support/solutions/articles/36000003455-accessing-the-anchore-engine-api

The API is documented using the OpenAPI Specification (AKA Swagger), which
you can access from the engine itself which publishes both the swagger spec
that you can import into many tools to generate stubs, or you can use the
graphical API browser which documents the API and allows you to test it.

**Comment by Sh4d1** [comment]
Okay thanks! So I guess there is no need for a go API client then :smile:

**Comment by acathrow** [comment]
@Sh4d1 please let us know if you think this is enough or if we'd need something more.
thanks
