### ISSUE TITLE
docker image tag not available

### ISSUE THREAD

**Issue by AjayKumaraj** [anchore/anchore-engine#390]
** BUG REPORT **:
**What happened**:
tried pulling anchore engine v0.7.0 as per the script , but image tag is not available in docker hub repository

**ERROR**
Error response from daemon: manifest for anchore/anchore-engine:v0.7.0 not found: manifest unknown: manifest unknown

**Comment by alfredodeza** [comment]
@AjayKumaraj can you try again? I just tried and it worked fine for me:

```
$ docker pull anchore/anchore-engine:v0.7.0
v0.7.0: Pulling from anchore/anchore-engine
Digest: sha256:fcb7b905cb97b66813dd030ce11aeb6b5fefd8fbae0875afea23d6f918aa0f86
Status: Downloaded newer image for anchore/anchore-engine:v0.7.0
docker.io/anchore/anchore-engine:v0.7.0
```

**Comment by alfredodeza** [comment]
Thanks for reporting this issue @AjayKumaraj , I'm still unable to replicate this behavior, but if you do, please feel free to re-open this issue.

**Comment by AjayKumaraj** [comment]
@alfredodeza  it's working fine now. Thanks
