### ISSUE TITLE
Helm repository deprecated in November 2020, will AnchorE chart move?

### ISSUE THREAD

**Issue by rodrigc** [anchore/anchore-engine#391]
Since the repository where the AnchorE helm chart is going to be deprecated in Nov. 2020 as per: https://github.com/helm/charts#deprecation-timeline

Does the AnchorE project have any plans to move its helm chart somewhere else, i.e. to another GitHub repo? 

See: https://github.com/helm/charts/issues/16720#issuecomment-557250945

**Comment by zhill** [comment]
Yes, see the [Anchore Charts Repo](https://github.com/anchore/anchore-charts). We will be adding charts there to replace the chart here in stable (https://github.com/anchore/anchore-charts/issues/15).

**Comment by zhill** [comment]
Closing this as answered, but please add more or re-open if additional clarification is needed. Thanks!
