### ISSUE TITLE
upgrade helm chart to anchore-engine 0.70, database is not right version

### ISSUE THREAD

**Issue by rodrigc** [anchore/anchore-engine#395]
**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

**Version of Anchore Engine and Anchore CLI if applicable**:

anchore-cli, version 0.7.0

```
Name: anchore-engine
Version: 0.7.0
Summary: Anchore Engine
Home-page: http://www.anchore.com
Author: Anchore Inc.
Author-email: dev@anchore.com
License: Apache License 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: toastedmarshmallow, python-dateutil, SQLAlchemy, Authlib, Werkzeug, yosai, prometheus-flask-exporter, Flask, Click, urllib3, prettytable, six, connexion, passlib, ijson, psycopg2-binary, psutil, zope.interface, python-keystoneclient, semantic-version, zope.component, Twisted, requests, pytz, python-swiftclient, pathlib, swagger-spec-validator, jsonschema, boto3, watchdog, typing, pg8000, prometheus-client, treelib, retrying, PyYAML
```

**What happened**:

I originally had anchore-engine 0.6.1 installed.
I upgraded the helm chart, and did:

```
helm -n anchore upgrade -f values.yaml anchore ./
```

**What did you expect to happen**:

I expected the upgrade to complete successfully.

However, I saw this:

```
kubectl -n anchore logs anchore-anchore-engine-simplequeue-7985c89749-wp4v8

[MainThread] [anchore_manager.cli.service/start()] [WARN] this version of anchore-engine requires the anchore DB version (0.0.13) but we discovered anchore DB version (0.0.12) in the running DB - it is safe to run the upgrade while seeing this message - will retry for 3485 more seconds.
[MainThread] [anchore_manager.cli.service/start()] [WARN] this version of anchore-engine requires the anchore DB version (0.0.13) but we discovered anchore DB version (0.0.12) in the running DB - it is safe to run the upgrade while seeing this message - will retry for 3480 more seconds.
```

Looks like the database did not upgrade for me.
How can I force the database to upgrade?

**Comment by rodrigc** [comment]
I read the source code to anchore-manager, and based on the environment variables that were set,
I tried this command:

```
anchore-manager db --db-connect "postgresql://$ANCHORE_DB_HOST/$ANCHORE_DB_NAME?user=$ANCHORE_DB_USER&password=$ANCHORE_DB_PASSWORD" upgrade
```

and it seemed to do the upgrade.

**Comment by rodrigc** [comment]
It would have been nice if the error message about the DB version printed out a link with this exact command to type.  I looked all over the anchore documentation, and found this page: https://docs.anchore.com/current/docs/engine/engine_installation/upgrade/

but it doesn't give you the format of the db_connect string.

**Comment by rodrigc** [comment]
I managed to fix the problem.  I had to do the following in order to fix things:

1.   `kubectl edit` the deployment for `anchore-engine-api`
2.    Disable the liveness probe
3.  `kubectl exec` into the `anchore-engine-api` pod
4.   Run: `anchore-manager db --db-connect "postgresql://$ANCHORE_DB_HOST/$ANCHORE_DB_NAME?user=$ANCHORE_DB_USER&password=$ANCHORE_DB_PASSWORD" upgrade`

That successfully upgraded the database.

**Comment by rodrigc** [comment]
I would like to request the following:

1.  The error message in the code:
```
[WARN] this version of anchore-engine requires the anchore DB version (0.0.13) but we discovered anchore DB version (0.0.12) in the running DB - it is safe to run the upgrade while seeing this message - will retry for 3485 more seconds.
```

be changed to include a link to the docs for upgrading the DB.


2.  The docs at https://docs.anchore.com/current/docs/engine/engine_installation/upgrade/ be changed to include this example invocation:

`anchore-manager db --db-connect "postgresql://$ANCHORE_DB_HOST/$ANCHORE_DB_NAME?user=$ANCHORE_DB_USER&password=$ANCHORE_DB_PASSWORD" upgrade`

**Comment by zhill** [comment]
Did the catalog pod fail? The system will upgrade the db itself and that process is driven by the catalog component/pod. While it is upgrading all the other components backoff and wait for the process to finish. I think there can be a better message indicating this condition, but I want to differentiate between an actual upgrade that didn't complete and the other components properly waiting for the upgrade to finish.

We're looking at using a different upgrade process in the helm chart (hooks + jobs most likely), but the only reason the upgrade itself would fail here is if the healthcheck on the catalog pod failed for too long due to upgrade taking a while and thus failing the process. But, the catalog will continue retrying to upgrade even on container restarts. Did you see that condition?

**Comment by rodrigc** [comment]
I'm not sure what exactly failed.   After doing a `helm upgrade` as mentioned above, when things weren't working, I tried to jump in and fix things.

**Comment by zhill** [comment]
We have made updates to the chart to run an explicit upgrade step using a post-upgrade hook. The other pods will sit and wait for the upgrade but if the probes cause them to terminate it will not terminate the upgrade itself since that is a distinct job.

**Comment by rodrigc** [comment]
That sounds like a good approach.

**Comment by woz5999** [comment]
So I've hit this issue on the last 2 most recent chart upgrades. Regression?
