### ISSUE TITLE
How to add other repos?

### ISSUE THREAD

**Issue by SquirrelAssassin** [anchore/anchore-engine#4]

**Comment by SquirrelAssassin** [comment]
Were trying to hook into an Azure container registry.  Is there a way to login to this repo and pull images from here?  If not is there a different recommend approach?

**Comment by nurmi** [comment]
Hi @SquirrelAssassin 

If you're using anchore-engine with the CLI, you should be able to add any docker registry (v2 API, which the Azure container registry supports) using the 'anchore-cli registry' operations.  Adding requires that you have the registry hostname (provided by Azure), username, and password for the azure v2 docker registry endpoint.  For example, if you are able to login with docker:

```
# docker login myazuredockerregistry.com
Username: foouser
Password: foopass
```

then the anchore-cli command would be:

```
# anchore-cli registry add myazuredockerregistry.com foouser foopass
# anchore-cli registry list
Registry                 Type             User              
mydocker.com             docker_v2        foouser
```
Once the registry is added to anchore-engine as above, the engine should be able to pull images from the added registry:

```
# anchore-cli image add myazuredockerregistry.com/myrepo:latest
...
...
```

Does this help with adding your azure registry?  

Best,
-Dan

**Comment by SquirrelAssassin** [comment]
Spot on man thanks!
