### ISSUE TITLE
GHSA alerts on python packages mis-labeled

### ISSUE THREAD

**Issue by tonkapango** [anchore/anchore-engine#400]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore/inline-scan (bc9b32b6f935 )

**What happened**:
Typical scan shows these GHSA alerts labeled as "os" packages.

**What did you expect to happen**:
That these GHSA alerts (above) be labled as "non-os" packages.

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:
latest anchore/inline-scan above

**How to reproduce the issue**:
use anchore/inline scan and scan an image with pip installed cryptography version >= 1.9.0, < 2.3

**Anything else we need to know**:

**Comment by zhill** [comment]
Thanks @tonkapango , we'll address this
