### ISSUE TITLE
PolicyEvaluation not well defined in the swagger spec

### ISSUE THREAD

**Issue by Sh4d1** [anchore/anchore-engine#41]
**Is this a BUG REPORT or a FEATURE REQUEST?**:
Bug report (depends how you look at it :smile: )

**Version of Anchore Engine and Anchore CLI if applicable**:
```
Name: anchore-engine
Version: 0.2.2.dev0
Summary: Anchore Engine
Home-page: http://www.anchore.com
Author: Anchore Inc.
Author-email: dev@anchore.com
License: Apache License 2.0
Location: /usr/lib/python2.7/site-packages
Requires: Twisted, pg8000, boto3, botocore, chardet, click, clickclick, connexion, docker-py, enum34, docutils, Flask, functools32, futures, idna, inflection, itsdangerous, Jinja2, jmespath, jsonschema, MarkupSafe, pathlib, python-dateutil, PyYAML, requests, s3transfer, six, SQLAlchemy, swagger-spec-validator, typing, urllib3, watchdog, Werkzeug, passlib, prometheus-client, prometheus-flask-exporter, python-swiftclient, python-keystoneclient, pytz, anchore, certifi
Required-by: 
```
 
**What happened**:
PolicyEvaluation is not well defined in the swagger spec:
https://github.com/anchore/anchore-engine/blob/49416a4bd09948f18df1e069297756d530c32ec1/anchore_engine/services/apiext/swagger/swagger.yaml#L1574-L1576
So the swagger generated go API will fail when unmarshaling.

**What did you expect to happen**:
For it to be defined 

Happy to do a PR but not sure of the exact fields :roll_eyes:

**Comment by nurmi** [comment]
hi @Sh4d1 - thank you, this is something we would like to dig into, to ensure generated clients are ready to go.   It would help if you could give us a complete description/CLI/tarball of the process you're using, to help us verify fixes/updates against the specific code-gen/client process that you're using - would you mind sharing your process/example client code that exhibits the issue?

**Comment by Sh4d1** [comment]
Hey @nurmi !
So I'm using Go code generated by swagger codegen (available at https://github.com/Sh4d1/go-anchore)
Here is my code:
```go
package main

import (
	"fmt"
	"os"
	"time"

	anchore "github.com/Sh4d1/go-anchore"
	"golang.org/x/net/context"
)

func main() {
	config := &anchore.Configuration{
		BasePath:      "http://localhost:8228",
		DefaultHeader: make(map[string]string),
		UserAgent:     "Swagger-Codegen/1.0.0/go",
	}

	client := anchore.NewAPIClient(config)
	auth := context.WithValue(context.Background(), anchore.ContextBasicAuth, anchore.BasicAuth{
		UserName: "admin",
		Password: "foobar",
	})

	new_image := anchore.ImageAnalysisRequest{
		Tag: "docker.io/traefik:1.5",
	}
	image, _, err := client.ImagesApi.AddImage(auth, new_image, nil)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	if len(image) > 1 {
		fmt.Println("Weird")
		return
	}
	for {
		im, _, err := client.ImagesApi.GetImage(auth, image[0].ImageDigest)
		if err != nil {
			fmt.Println(err.Error())
			return
		}
		if len(im) > 1 {
			fmt.Println("Also weird")
			return
		}
		if im[0].AnalysisStatus == "analyzed" || im[0].AnalysisStatus == "analysis_failed" {
			break
		}
		time.Sleep(1000 * time.Millisecond)
	}
	_, _, err = client.ImagesApi.GetImagePolicyCheck(auth, image[0].ImageDigest, "1.5", nil)
	if err != nil {
		fmt.Println(err.Error())
	}
}
```

And here is the output:
```
json: cannot unmarshal array into Go value of type swagger.PolicyEvaluation
```
It happens when I call `GetImagePolicyCheck`

Do you need more info? :smile:

**Comment by nurmi** [comment]
@Sh4d1 - thank you very much, that helps a lot and ensures that we're working on/validating the same thing - we'll take a look and track here with updates

**Comment by nurmi** [comment]
@Sh4d1 - update on this, we were able to reproduce the issue and I believe there are two problems that we need to address - first is that the swagger-codegen generated code isn't handling an array as an object, which is something we can resolve pretty easily by being more specific in the swagger for the PolicyEvaluation response (specify an array of PolicyEvaluations as the response type for the check route). 

However, even once that is addressed, the generated code is still not handling a generic 'object' without its form being explicitly specified (which is what the title of this issue accurately points out) - we'll need to put some time into specifying the form of PolicyEvaluation response objects explicitly in order for the generated code to function correctly.

We'll make both of these changes in future releases of anchore-engine, and will track the progress on this ticket!

**Comment by mikeklein** [comment]
Fyi, using JSONObject (and Java) I had no problems unmarshalling these types referring to Object.
