### ISSUE TITLE
will anchore-engine compatible with nexus 3 docker registry

### ISSUE THREAD

**Issue by navinprasadk** [anchore/anchore-engine#438]
**Is this a request for help?**: 
yes, It's a help

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): Feature request

**Version of Anchore Engine and Anchore CLI if applicable**:
Engine DB Version: 0.0.13
Engine Code Version: 0.7.0

**What happened**:

I'm configuring Nexus 3 as a private docker registry to store the image for my project purpose. I have to build a CI/CD pipeline which includes Anchore to scan a docker image. Here my question is whether the anchor supports nexus3 docker registry or not?

**What did you expect to happen**:
Anchore to scan the docker image from nexus3 docker registry

**What docker images are you using**:
     anchore/anchore-engine:v0.7.0

**Comment by zhill** [comment]
hi @navinprasadk , Anchore supports nearly all registries that work with `docker login` and `docker pull`, so it should be supported. Have you tried it and run into issues?

**Comment by zhill** [comment]
Closing this as stale. Engine should support Nexus 3 with proper credential configuration using `anchore-cli registry add <url> <user> <password>`, if that does not work then file an issue and we'll take a look. Thanks!
