### ISSUE TITLE
Image analysis not started.

### ISSUE THREAD

**Issue by yihyunyi** [anchore/anchore-engine#44]
**Is this a request for help?**:

--- YES

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
--- BUG or .. NOT permited for unregistered user.

 
 anchore-cli, version 0.1.8
--> anchore-engine, Version: 0.2.1
--> docker image ID of anchore engine is 6eafdab1ce30
 
**What happened**:
After add image to anchore, stayed 'not_analyzed' state for a long time. 
When I checked system status, 'policy_engine' repeated 'up' and 'down'.

**What did you expect to happen**:

**Any relevant log output from /var/log/anchore**:

anchore-engine_1  | [service:policy_engine] 2018-05-17 06:34:26+0000 [-] [bootstrap] [WARNING] no webhooks defined in configuration file - notifications will be disabled
anchore-engine_1  | [service:policy_engine] 2018-05-17 06:34:26+0000 [-] [bootstrap] [INFO] initializing database
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-engine_1  | [service:policy_engine] 2018-05-17 06:34:27+0000 [-] [bootstrap] [INFO] Registration complete.
anchore-engine_1  | [service:policy_engine] 2018-05-17 06:34:27+0000 [-] [bootstrap] [INFO] Checking feeds client credentials
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-db_1      | WARNING:  there is no transaction in progress
anchore-engine_1  | [service:policy_engine] 2018-05-17 06:34:27+0000 [-] [bootstrap] [ERROR] Preflight checks failed with error: 403 Client Error: Forbidden for url: https://ancho.re/v1/account/users/anon@ancho.re. Aborting service startup

**What docker images are you using**:
  anchore-engine:
    image: docker.io/anchore/anchore-engine:latest

 anchore-db:
    image: "postgres:9"

**How to reproduce the issue**:

**Anything else we need to know**:
In a 'Anchore Service Configuration File' notice that Anchore's feed service uses anonymous access.
Should I have a account for using feeds? or  Should I missed something?

**Comment by zhill** [comment]
Hi @yihyunyi,

The policy engine component does a check of access to the feed endpoint, which is the URL you're seeing. Anonymous access should work and is what is configured by default in the config.yaml we provided as an example for the docker-compose deployment. As long as that config.yaml's feed section isn't altered it should work without you needing to set up any accounts. We use a specific username and password for the 'anonymous' user for the feed service (which provides CVE data and is completely free), so if you've altered the config.yaml in the `feeds` section for credentials it could be failing. Have you made any changes or are you using our provided config.yaml?

**Comment by nurmi** [comment]
hi @yihyunyi - from the information in the original post (getting a 403), one explanation is that there may be something in the network that is interfering with access to the ancho.re endpoint using SSL - a quick test that you can use to verify that the ancho.re feed endpoint is accessible from your client can be performed from within the container using curl (the first is correctly showing a 401, since the anon password is not supplied, and the second is when the anon password (public, the same for all anon access to ancho.re) is supplied).  It may shed some light on the issue if you can run similiar tests to see if there is something (firewall, proxy, other network blocks) going on between your client and https://ancho.re:

```
# curl --verbose https://ancho.re/v1/account/users/anon@ancho.re
* About to connect() to ancho.re port 443 (#0)
*   Trying 104.28.13.5...
* Connected to ancho.re (104.28.13.5) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=sni189579.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
* 	start date: May 11 00:00:00 2018 GMT
* 	expire date: Nov 17 23:59:59 2018 GMT
* 	common name: sni189579.cloudflaressl.com
* 	issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /v1/account/users/anon@ancho.re HTTP/1.1
> User-Agent: curl/7.29.0
> Host: ancho.re
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Date: Mon, 21 May 2018 18:27:01 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d87acf4af86f000138adb3da49b8aa4c11526927221; expires=Tue, 21-May-19 18:27:01 GMT; path=/; domain=.ancho.re; HttpOnly
< Cache-Control: must-revalidate
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 41e9183f49d35384-LAX
< 
{
    "message": "Unauthorized request: no authentication given",
    "code": 401,
    "name": "unauthorized_request"
* Connection #0 to host ancho.re left intact
```

```
# curl --verbose -H 'x-anchore-password: pbiU2RYZ2XrmYQ' https://ancho.re/v1/account/users/anon@ancho.re
* About to connect() to ancho.re port 443 (#0)
*   Trying 104.28.12.5...
* Connected to ancho.re (104.28.12.5) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=sni189579.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
* 	start date: May 11 00:00:00 2018 GMT
* 	expire date: Nov 17 23:59:59 2018 GMT
* 	common name: sni189579.cloudflaressl.com
* 	issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /v1/account/users/anon@ancho.re HTTP/1.1
> User-Agent: curl/7.29.0
> Host: ancho.re
> Accept: */*
> x-anchore-password: pbiU2RYZ2XrmYQ
> 
< HTTP/1.1 200 OK
< Date: Mon, 21 May 2018 18:28:29 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d5164b9ec402fbce201dc9797b313dfe91526927309; expires=Tue, 21-May-19 18:28:29 GMT; path=/; domain=.ancho.re; HttpOnly
< Cache-Control: must-revalidate
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 41e91a649cd45438-LAX
< 
{
    "_id": "anon@ancho.re",
...
...
...
...
}
```

**Comment by nurmi** [comment]
Hello @yihyunyi 

I'm going to close this ticket as it hasn't been active in a while - but please let us know if you would like to continue to discussion, here!
