### ISSUE TITLE
Question: Version of installed package

### ISSUE THREAD

**Issue by remidinishanth** [anchore/anchore-engine#443]
**Is this a request for help?**:
Yes,
I have read the Anchore documentation and go to know that Anchore fetches the image content and extract it, but never execute it. So when Anchore gets the file system of my container, how does it figure out the version of the packages in it? Does Anchore have the hash of files stored in db to compare the version?
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

**Version of Anchore Engine and Anchore CLI if applicable**:

**What happened**:

**What did you expect to happen**:

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by zhill** [comment]
Anchore extracts metadata from the image content including file content (package.json, python distro info, java jar META-INF, etc), rpm, dpkg, and apk db content using binaries in the anchore install, not in the image. Engine does also hash all files in the image's FS but those are not (yet) used for version identification.

**Comment by zhill** [comment]
Closing this as answered. If you need more information, please re-open and comment for clarifiction. Thanks!
