### ISSUE TITLE
unable to change admin password as well as CLI password

### ISSUE THREAD

**Issue by swetan27** [anchore/anchore-engine#446]
**Is this a request for help?**:

---

**Is this a BUG REPORT ** (choose one):

**Version of Anchore Engine and Anchore CLI if applicable**:

Engine Code Version: 0.7.0

**What happened**:
Tried to change the default_admin_password in config.yaml file, but there is no effect.
default_admin_password :pass123
Further, i also tried to change by executing following commands:
 ANCHORE_CLI_PASS = pass123
export ANCHORE_CLI_PASS

**What did you expect to happen**:
I expected that the command anchore-cli account list would run without giving me unauthorized error

**Any relevant log output from /var/log/anchore**:
anchore-cli account list
"Unauthorized"

**What docker images are you using**:
none

**How to reproduce the issue**:
cd anchore-engine
vi config/config.yaml
default_admin_password :pass123
ANCHORE_CLI_PASS = pass123
export ANCHORE_CLI_PASS
**Anything else we need to know**:
Kindly ask if you need anything

**Comment by zhill** [comment]
Hi @swetan27 , the values in the config yaml only affect initial system bootstrap. After the system is initialized you can change credentials with the `anchore-cli accout *` commands directly.

The ANCHORE_CLI_* env vars are only used for setting the credential that the CLI will use, and have no affect on the engine identities/configuration.

**Comment by zhill** [comment]
See: https://docs.anchore.com/current/docs/engine/usage/cli_usage/accounts/ for more information on credential management with the CLI

**Comment by swetan27** [comment]
Thanks closing the issue.
