### ISSUE TITLE
docker-compose.yaml missing from v0.7.1

### ISSUE THREAD

**Issue by kumy** [anchore/anchore-engine#449]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**: v0.7.1

**What happened**: The mentionned `docker-compose.yaml` file from the documentation https://docs.anchore.com/current/docs/engine/engine_installation/docker_compose/#step-2-copy-configuration-files is missing from the latest v0.7.1 docker image. It is present in v0.7.0

**What did you expect to happen**:
Have the doc and the image matching toghether

**Any relevant log output from /var/log/anchore**: N/A

**What docker images are you using**:
* `docker.io/anchore/anchore-engine:v0.7.1` / `latest`
* `docker.io/anchore/anchore-engine:v0.7.0`

**How to reproduce the issue**:

```bash
# docker run -it --rm --name ae docker.io/anchore/anchore-engine:v0.7.1 ls /
analysis_scratch  anchore_service  boot    dev			 etc   lib    licenses	  media  opt   root  sbin  sys	usr  workspace
anchore-engine	  bin		   config  docker-entrypoint.sh  home  lib64  lost+found  mnt	 proc  run   srv   tmp	var

# docker run -it --rm --name ae docker.io/anchore/anchore-engine:v0.7.0 ls /
analysis_scratch  anchore_service  boot    dev			    docker-compose.yaml   etc	lib    licenses    media  opt	root  sbin  sys  usr  workspace
anchore-engine	  bin		   config  docker-compose-dev.yaml  docker-entrypoint.sh  home	lib64  lost+found  mnt	  proc	run   srv   tmp  var
```

**Comment by zhill** [comment]
Hi @kumy sorry for the confusion, but this is a docs issue. The docker-compose file you're looking for is in the quickstart at: https://docs.anchore.com/current/docs/engine/quickstart. I'll update the older install page to point to the quickstart. We've stopped putting the compose file in the image so that it can be updated between releases without having to build new images.

**Comment by zhill** [comment]
Closing this since the docs are updated to refer to the quickstart guide now which has the proper instructions.
