### ISSUE TITLE
package_type parameter seems to be ignored in policy evaluation

### ISSUE THREAD

**Issue by wilx** [anchore/anchore-engine#450]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?**

BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:

anchore-cli, version 0.7.0

```
Name: anchore-engine
Version: 0.7.1
Summary: Anchore Engine
Home-page: http://www.anchore.com
Author: Anchore Inc.
Author-email: dev@anchore.com
License: Apache License 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: Click, pg8000, pathlib, semantic-version, psycopg2-binary, Flask, prometheus-flask-exporter, treelib, pytz, prometheus-client, retrying, prettytable, Twisted, ijson, swagger-spec-validator, jsonschema, six, PyYAML, zope.interface, passlib, requests, python-keystoneclient, psutil, Authlib, zope.component, SQLAlchemy, boto3, watchdog, connexion, python-dateutil, toastedmarshmallow, typing, Werkzeug, yosai, python-swiftclient, urllib3
```

**What happened**:

Anchore policy evaluation shows STOP action for non-os packages vulnerabilities but policy parameter `package_type` with value `os` present.

See attached [anchore.log.json.txt](https://github.com/anchore/anchore-engine/files/4616826/anchore.log.json.txt), JSON result of policy evaluation.

**What did you expect to happen**:

Only `os` vulnerabilities to be considered when evaluating the policy.

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**: v0.7.1

**How to reproduce the issue**: See the attached result for the policy.

**Anything else we need to know**:

**Comment by zhill** [comment]
Hi @wilx , I see this only for GHSA vulnerabilities in that output. Have you seen any other matches (CVEs from NVD) in this case?

**Comment by wilx** [comment]
There are no more fixable `os` vulnerabilities in the image. There unfixable `os` vunlerabilities and also one additional `nvdv2:cves` (python) vulnerability in the results.

**Comment by zhill** [comment]
> There are no more fixable `os` vulnerabilities in the image. There unfixable `os` vunlerabilities and also one additional `nvdv2:cves` (python) vulnerability in the results.

Ack. Thanks. That confirms my analysis as well.
