### ISSUE TITLE
Add Java/Maven metadata support

### ISSUE THREAD

**Issue by jvz** [anchore/anchore-engine#48]
I was browsing through the codebase and found [this feature](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/analyzers/modules/32_java_packages.py) where `manifest.mf` files are scanned for data. Not all Java libraries add these metadata. However, any library packaged with Apache Maven tends to include a file named `pom.properties` (generally inside `META-INF/maven/groupId/artifactId/pom.properties`) which has the name and version info data. This is also generally more reliable than the manifest file due to, once again, typical build tooling usage. This can be very helpful when libraries are shaded together; the manifest files may get destroyed in the process, but all the `pom.properties` files will safely-ish combine together (other than version number conflicts, but that's also handled by shading).

**Comment by zhill** [comment]
@jvz thanks for filing this. We'll definitely take a look and update this ticket with progress. Anything that helps the fidelity of the detection process is much appreciated.

**Comment by jvz** [comment]
I'd love to help out where I can with this. I'm investigating integrating Anchore with Jenkins's Jenkins build, and if I can use the same tool for both Docker images as well as the Java libraries within, that would be fantastic. I'm not exactly sure how these data overlap with the CVE feeds, but that would be my goal at least.

**Comment by nurmi** [comment]
Hi @jvz - that is a great observation!  There are effectively two 'sides' to the anchore process, where the first is 'gather the data' and the second is 'parse, store and use' the data for policy evaluation.  The analyzer module (32_java_packages.py) represents the first phase, where I'd suggest that we would add the pom.properties file as an additional 'metadata' element, if found.  The second part is largely implemented [here in the policy engine](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/policy_engine/engine/loaders.py#L590), where candidates for the name/version are discovered from the analyzer artifacts, constructed into a set of potential CPEs, and then matched against NVD data (and used as content output when java package information is requested for an image).  

I thought I'd provide a bit more context about the two 'sides' of the process when considering adding more analysis capabilities for java packages!

**Comment by jvz** [comment]
Great, that's exactly what I was wondering about! Are there any sample unit or integration tests to go off of? Or perhaps a desired way of doing so if there aren't any already.

**Comment by zhill** [comment]
hi @jvz, there aren't really any integration tests for the analyzers, but you can run time directly outside of anchore as long as you have a rootfs to point them at. The current java analyzer is: https://github.com/anchore/anchore-engine/blob/master/anchore_engine/analyzers/modules/32_java_packages.py

You can see that it is a stand-alone script that is just given some path information on where to find the rootfs etc. Any additional metadata handling for Maven builds could be added there as part of the recursive jar inspection.

We've also got a community slack channel if you want an invite so we can discuss live. Happy to send an invite.

**Comment by jvz** [comment]
Awesome, thanks for the pointers. The slack invite would be great, email is in my profile.

Also, this might be a separate issue, but there are some more file extensions that could be supported for Java libraries. I know that Jenkins uses `.hpi` for example.

**Comment by zhill** [comment]
@jvz Invite sent. I see the PR and we'll review it shortly. Thanks!

**Comment by jvz** [comment]
Come to think of it, there is a third potential source for metadata in Java libraries: OSGi metadata. This would come from the manifest.mf file and may have more detailed information. In order to properly parse these data, though, the manifest parsing logic will need to be improved to support proper manifest files (i.e., with line wrapping implemented), and some of the OSGi metadata are encoded as LDAP filters, so a syntax parser for that could be useful in the future if the data are examined more thoroughly.
