### ISSUE TITLE
Update to skopeo 1.1.0

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#484]
Upgrade the version of skopeo to 1.1.0 or at least 0.2.0 if 1.1.0 is too big a change. Will facilitate removing the strange search tag for repo-add operations where there isn't a 'latest' tag in the repo as the new versions include a command `list-tags` that works without a known tag to inspect.

**Comment by nightfurys** [comment]
@zhill, I imagine the update is a simple change in Dockerfile, is there a test suite to verify the update does not cause any regressions?

**Comment by zhill** [comment]
> @zhill, I imagine the update is a simple change in Dockerfile, is there a test suite to verify the update does not cause any regressions?

We currently build from source in the Dockerfile, so this isn't quite just simple. This repo will have any tests for that specific path, can check there (I'm not aware of any that test it exhaustively). I think that's worth a look for this update.
