### ISSUE TITLE
Provide json schemas for webhook payloads

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#490]
Each webhook payload should have a jsonschema available in the codebase to provide documentation, validation, and guidance to developers writing consumers for the webhooks.

**Comment by dakaneye** [comment]
Reviewing the code, it seems that there's only 1 format for the webhook payload JSON.

### Subscriptions
In the [Catalog Initialization](anchore_engine/services/catalog/__init__.py) there's a scheduled task for handling notifications from the queue that both populates messages in the **queues** table, and then sends them out via [notifications](anchore_engine/subsys/notifications.py).

So the actual webhook that gets sent out appears to be something like this, which is a combination of the columns in [QueueItem](anchore_engine/db/entities/catalog.py) and what is generated from [notifications.make_notification](anchore_engine/subsys/notifications.py)

I did also notice that there are other places where a notification can get queued, but not seeing where a consumer of the queue would actually send out a webhook:
### Events
Pretty much whenever an event is generated, but the format should be pretty consistent: [add_event_json](anchore_engine/services/catalog/catalog_impl.py)

### Images
Whenever an image tag gets updated?  In the [image watcher](anchore_engine/services/catalog/__init__.py)

Are there any other areas where a possibly different schema could get generated for a webhook? And do the Events/Images notifications get sent via webhooks ever?

**Comment by dakaneye** [comment]
Hmm. After getting an **analysis_update** event to fire for a new image, got a payload like this delivered:
```json
{
   "record_state_key":"active",
   "created_at":1597085212,
   "userId":"admin",
   "tries":0,
   "last_updated":1597085212,
   "dataId":"a12dc2f2-84be-4aef-9b6a-434299c6ae74",
   "queueId":"analysis_update",
   "max_tries":1597085242,
   "data":{
      "notification_user":"admin",
      "notification_user_email":"admin@myanchore",
      "notification_type":"analysis_update",
      "notification_payload":{
         "notificationId":"a12dc2f2-84be-4aef-9b6a-434299c6ae74",
         "userId":"admin",
         "subscription_key":"docker.io/postgres:9",
         "curr_eval":{
            "analysis_status":"analyzed",
            "annotations":{

            },
            "imageDigest":"sha256:570431d9c2f68af2f1490e6de30723711a42550a6f063144b324b993d3529eef"
         },
         "last_eval":{
            "analysis_status":"analyzing",
            "annotations":{

            },
            "imageDigest":"sha256:570431d9c2f68af2f1490e6de30723711a42550a6f063144b324b993d3529eef"
         },
         "subscription_type":"analysis_update"
      }
   }
}
```

So, it seems like the **notification_payload** can vary a bit beyond the standard fields.
