### ISSUE TITLE
How to add custom anchore policy

### ISSUE THREAD

**Issue by shamimgeek** [anchore/anchore-engine#494]
Hello,

I am able to add policy from the json file  but it seems it is hard to update from json file. How do i know policy id in advance ? 

I found below lines from the [link](https://github.com/anchore/anchore-policies/blob/master/basic-policy/basic-policy) but no idea  how to convert it to anchore json policy file or is there way to update below lines to json ?  What is the best approach to create custom policy?

```
DOCKERFILECHECK:NOTAG:STOP
DOCKERFILECHECK:NOFROM:STOP
DOCKERFILECHECK:NOHEALTHCHECK:WARN
DOCKERFILECHECK:EXPOSE:STOP:DENIEDPORTS=22
SUIDDIFF:SUIDFILEDEL:GO
SUIDDIFF:SUIDMODEDIFF:STOP
SUIDDIFF:SUIDFILEADD:STOP
IMAGECHECK:BASEOUTOFDATE:WARN
PKGBLACKLIST:PKGNAMEMATCH:STOP:BLACKLIST_NAMEMATCH=openssh-server
ANCHORESEC:FEEDOUTOFDATE:STOP:MAXAGE=2
ANCHORESEC:UNSUPPORTEDDISTRO:STOP
ANCHORESEC:VULNCRITICAL:STOP
ANCHORESEC:VULNHIGH:STOP
ANCHORESEC:VULNMEDIUM:WARN
```

**Comment by zhill** [comment]
@shamimgeek good question. The [policy bundle docs](https://docs.anchore.com/current/docs/overview/concepts/policy/bundles/) should help there but there are a few things to keep in mind: the IDs in the rules and policies only need to be unique within the bundle, so you can make up names for those or use random generated IDs.

You can also use:
`anchore-cli policy describe` to view the value policy gates and their triggers and parameters for use in the policy bundle.

**Comment by zhill** [comment]
I'm closing this as answered unless you have more questions @shamimgeek
