### ISSUE TITLE
Add API to return list of tags from a repo

### ISSUE THREAD

**Issue by nightfurys** [anchore/anchore-engine#510]
Add a new route that takes a repo as a path/query (tbd) parameter and returns the list of tags. This can precede 'analyze repo' action on the client to give the end user visibility into the tags that will be added to anchore-engine for analysis. The response can also be used by the client to selectively add tags to anchore-engine instead of analyzing the entire repo which could come for large repos with only a small subset of interesting tags

**Comment by zhill** [comment]
Closed by cae59df
