### ISSUE TITLE
Auto delete tags for a image after 'X' newer versions

### ISSUE THREAD

**Issue by ykosaraju** [anchore/anchore-engine#526]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
Feature Request

Our DB of images has become so large that 
`anchore-cli image list` fails (due to ALB timeout)
Root cause is a lot of different versions of the same image rather than many different images.

The feature request is a config option to delete image tags for an image after 'X' newer tags have been scanned ('X' being configurable) and/or after 'Y' days
I would like to be able to say "Image tags older than 10 versions will be deleted after 365 days" or something in that manner

**Comment by zhill** [comment]
@ykosaraju you're in luck! We have just such a feature in Anchore Engine: the analysis archive. You can configure global rules that will transition images into an archived state automatically and then delete those archives automatically as well. See [the Analysis Archive section of the docs](https://docs.anchore.com/current/docs/overview/concepts/images/analysis_archive/) for more info. Even though that is listed in enterprise it is also available in engine OSS. If that doesn't meet your needs please let us know what else is missing and we'll take a look.

**Comment by ykosaraju** [comment]
YES.!!
Thats _exactly_ what I was asking for
The days vs tag depth, how do they get evaluated?
(we can close this out)

**Comment by zhill** [comment]
> YES.!!
> Thats _exactly_ what I was asking for
> The days vs tag depth, how do they get evaluated?
> (we can close this out)

A specific image must match both conditions for all tags that reference it. Anything that doesn't match will stay in the active set.

**Comment by ykosaraju** [comment]
aah thanks.!
