### ISSUE TITLE
TLS config not working and startup doesn't indicate issue

### ISSUE THREAD

**Issue by mikeklein** [anchore/anchore-engine#53]
BUG, Version is 0.2.1
 
**What happened**:

Setup for TLS never seems to "kick in". Following is config.yaml for this:

```
  apiext:
    enabled: True
    require_auth: True
    endpoint_hostname: '${ANCHORE_HOST_ID}'
    listen: '0.0.0.0'
    port: 8228
    ssl_enable: True
    ssl_cert: '/Users/m0k00lj/Images/nchore/aevolume/config/anchore.crt'
    ssl_key: '/Users/m0k00lj/Images/nchore/aevolume/config/anchore.key'

```
Notice that I purposely mispelled "anchore" in middle of key paths above. This isn't even recognized by anchore engine and startup occurs as usual...why? No fileNotFound exception, etc. Also when I mismatch key/cert there's no error about them not matching...it's as if entire ssl setup is somehow ignored.

In logs I see a single line: anchore-engine_1  | [service:api] 2018-06-05 20:29:04+0000 [-] Site (TLS) starting on 8228

Other than above I see no indication of issues with passing in bad keypaths or mismatched keys. This almost implies my yaml category/properties are bad.

**What did you expect to happen**:

Startup with TLS1.3 (or perhaps v1.2 cause python) protocol active.

**Any relevant log output from /var/log/anchore**:

In logs I see a single line: anchore-engine_1  | [service:api] 2018-06-05 20:29:04+0000 [-] Site (TLS) starting on 8228

Nothing other than this. I've grep'd logs for https, ssl, etc. and other than https://ancho.re references that's it.

Here is output from openssl handshake:

m-c02w20yrhtdg:config m0k00lj$ openssl s_client -showcerts -debug -msg -connect localhost:8228
CONNECTED(00000005)
write to 0x7f973241d490 [0x7f973280d000] (318 bytes => 318 (0x13E))
0000 - 16 03 01 01 39 01 00 01-35 03 03 ad a2 d2 b2 97   ....9...5.......
0010 - 11 55 3d 5a d2 92 c9 54-10 47 d5 70 88 f5 3c 58   .U=Z...T.G.p..<X
0020 - 79 73 21 32 71 75 43 87-00 76 19 00 00 98 cc 14   ys!2quC..v......
0030 - cc 13 cc 15 c0 30 c0 2c-c0 28 c0 24 c0 14 c0 0a   .....0.,.(.$....
0040 - 00 a3 00 9f 00 6b 00 6a-00 39 00 38 ff 85 00 c4   .....k.j.9.8....
0050 - 00 c3 00 88 00 87 00 81-c0 32 c0 2e c0 2a c0 26   .........2...*.&
0060 - c0 0f c0 05 00 9d 00 3d-00 35 00 c0 00 84 c0 2f   .......=.5...../
0070 - c0 2b c0 27 c0 23 c0 13-c0 09 00 a2 00 9e 00 67   .+.'.#.........g
0080 - 00 40 00 33 00 32 00 be-00 bd 00 45 00 44 c0 31   .@.3.2.....E.D.1
0090 - c0 2d c0 29 c0 25 c0 0e-c0 04 00 9c 00 3c 00 2f   .-.).%.......<./
00a0 - 00 ba 00 41 c0 11 c0 07-c0 0c c0 02 00 05 00 04   ...A............
00b0 - c0 12 c0 08 00 16 00 13-c0 0d c0 03 00 0a 00 15   ................
00c0 - 00 12 00 09 00 ff 01 00-00 74 00 0b 00 04 03 00   .........t......
00d0 - 01 02 00 0a 00 3a 00 38-00 0e 00 0d 00 19 00 1c   .....:.8........
00e0 - 00 0b 00 0c 00 1b 00 18-00 09 00 0a 00 1a 00 16   ................
00f0 - 00 17 00 08 00 06 00 07-00 14 00 15 00 04 00 05   ................
0100 - 00 12 00 13 00 01 00 02-00 03 00 0f 00 10 00 11   ................
0110 - 00 23 00 00 00 0d 00 26-00 24 06 01 06 02 06 03   .#.....&.$......
0120 - ef ef 05 01 05 02 05 03-04 01 04 02 04 03 ee ee   ................
0130 - ed ed 03 01 03 02 03 03-02 01 02 02 02 03         ..............
>>> TLS 1.2 Handshake [length 0139], ClientHello
    01 00 01 35 03 03 ad a2 d2 b2 97 11 55 3d 5a d2
    92 c9 54 10 47 d5 70 88 f5 3c 58 79 73 21 32 71
    75 43 87 00 76 19 00 00 98 cc 14 cc 13 cc 15 c0
    30 c0 2c c0 28 c0 24 c0 14 c0 0a 00 a3 00 9f 00
    6b 00 6a 00 39 00 38 ff 85 00 c4 00 c3 00 88 00
    87 00 81 c0 32 c0 2e c0 2a c0 26 c0 0f c0 05 00
    9d 00 3d 00 35 00 c0 00 84 c0 2f c0 2b c0 27 c0
    23 c0 13 c0 09 00 a2 00 9e 00 67 00 40 00 33 00
    32 00 be 00 bd 00 45 00 44 c0 31 c0 2d c0 29 c0
    25 c0 0e c0 04 00 9c 00 3c 00 2f 00 ba 00 41 c0
    11 c0 07 c0 0c c0 02 00 05 00 04 c0 12 c0 08 00
    16 00 13 c0 0d c0 03 00 0a 00 15 00 12 00 09 00
    ff 01 00 00 74 00 0b 00 04 03 00 01 02 00 0a 00
    3a 00 38 00 0e 00 0d 00 19 00 1c 00 0b 00 0c 00
    1b 00 18 00 09 00 0a 00 1a 00 16 00 17 00 08 00
    06 00 07 00 14 00 15 00 04 00 05 00 12 00 13 00
    01 00 02 00 03 00 0f 00 10 00 11 00 23 00 00 00
    0d 00 26 00 24 06 01 06 02 06 03 ef ef 05 01 05
    02 05 03 04 01 04 02 04 03 ee ee ed ed 03 01 03
    02 03 03 02 01 02 02 02 03
read from 0x7f973241d490 [0x7f9732812600] (7 bytes => 7 (0x7))
0000 - 15 03 03 00 02 02 28                              ......(
<<< TLS 1.2 Alert [length 0002], fatal handshake_failure
    02 28
140735679509384:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/ssl/s23_clnt.c:541:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 318 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---

**What docker images are you using**:

The one generated from your docker-compose file.

**How to reproduce the issue**:

Enable TLS for apiext and specify good (or bad!) filepaths.

**Anything else we need to know**:

We're using python 2.7.x on both mac and linux systems hitting this issue.

**Comment by zhill** [comment]
@mikeklein Yes, it looks like it is falling thru silently. We will take a look at this and update this ticket with progress. Expected behavior is that it should fail to bootstrap the service if the cert and key are not found but ssl_enable is set to True.

**Comment by zhill** [comment]
Also note that if, without misspelling Anchore on purpose, you are not seeing the SSL startup, then you need to provide the path that is available from within the container. The /Users/... paths are probably your volume source path, not the mount location within the container. Based on your example I expect that to be /config/anchore.key and /config/anchore.crt if you're mounting the 'aevolume' dir at /config.

**Comment by mikeklein** [comment]
Problem was with non-docker filepaths, yes. Once I fixed this I got https up for backend...thanks.
