### ISSUE TITLE
[HELP] gcr.io authenticate multiple projects

### ISSUE THREAD

**Issue by jeroenfrenken** [anchore/anchore-engine#532]
**Is this a request for help?**: YES

In our current setup we are using Anchore for scanning our images from Google Container Registry.

The problem is as followed, We have multiple projects with different authentication keys (using json keyfiles as authentication method). When adding the keys I tried the following credentials:

HOST: eu.gcr.io/PROJECT_NAME
USER: _json_key
PASS: Content of Json key file

However with this setup it is not working. It is only working with the following configuration:

HOST: eu.gcr.io
USER: _json_key
PASS: Content of Json key file

But with the following setup I am not able to add multiple projects.

I was wondering if there is a solution for this problem

Thanks in Advance

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.7.2
anchore-manager, version 0.7.2

**What happened**:

**What did you expect to happen**:

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by zhill** [comment]
hi @jeroenfrenken can you elaborate on "However with this setup it is not working"? Is the system rejecting your config when you try to add that credential, or does it not authenticate correctly? Support for multiple projects in GCP is something that we definitely want to work.

**Comment by jeroenfrenken** [comment]
Hi @zhill the following is not working. What I mean by "this setup is not working" is that when trying to add images I get the response REGISTRY_PERMISSION_DENIED. 

## I did the following to get this error:

`anchore-cli registry add eu.gcr.io/my-gcr-project-1 _json_key CONTENT_OF_JSON_KEY_FILE --registry-name my-gcr-project-1`

### When trying to add the image:

 `anchore-cli image add eu.gcr.io/my-gcr-project-1/test-image`

`Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {'error_codes': ['REGISTRY_PERMISSION_DENIED'], 'raw_exception_message': 'Error encountered in skopeo operation. cmd=/bin/sh -c skopeo   inspect --raw --tls-verify=false docker://eu.gcr.io/my-gcr-project-1/test-image:latest, rc=1, stdout=None, stderr=b\'time="2020-07-29T08:35:02Z" level=fatal msg="Error parsing image name \\\\"docker://eu.gcr.io/my-gcr-project-1/test-image:latest\\\\": Error reading manifest latest in eu.gcr.io/my-gcr-project-1/test-image: unauthorized: You don\\\'t have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication"\\n\', error_code=REGISTRY_PERMISSION_DENIED'}`

## However when doing the following

**Host is now eu.gcr.io instead of eu.gcr.io/my-gcr-project-1**
`anchore-cli registry add eu.gcr.io _json_key CONTENT_OF_JSON_KEY_FILE --registry-name my-gcr-project-1`

Now the image is added without any error. But I can not add multiple registries under the same host eu.gcr.io. So I am wondering how to add the other projects.

**Note:** eu.gcr.io/my-gcr-project-1/test-image does not exists I am using an existing one when running the commands.

**Comment by zhill** [comment]
Thanks, we'll look into it. The prefix match should work on the registry host/repo.

**Comment by jeroenfrenken** [comment]
@zhill Do you have a example on how to configure this ?

**Comment by zhill** [comment]
Hi @jeroenfrenken, our docs are lacking here, so I'll file an issue to add content here, but it will work if you use:
`anchore-cli registry add 'eu.gcr.io/my-gcr-project-1/*' _json_key CONTENT_OF_KEY --registry-name my-gcr-project-1`

You need the trailing '*' to tell the system to match the repo prefix. Be sure to quote it so the shell doesn't expand it, but otherwise it should work. You can include the last / or not, it just uses a wildcard match so you can do partial repo name matches as well if you prefer to use the same token for multiple projects (e.g.`eu.gcr.io/my-gcr-project-*`)

**Comment by zhill** [comment]
@jeroenfrenken did you get it working?

**Comment by jeroenfrenken** [comment]
@zhill The sollution is working thanks for the help
