### ISSUE TITLE
Add ability to detect and match vulnerabilities against non-os golang runtime installations

### ISSUE THREAD

**Issue by nurmi** [anchore/anchore-engine#534]
Using the 'binary' content type feature (see issue #531 ), this enhancement will add an analyzer that can detect golang runtime installations that are not installed using 'os' package (rpm, dpkg, apkg, etc) install methods.  For example, the golang:* images in dockerhub include the golang runtime that matches the tag version, installed expicitly in a location not maintained by any underlying OS package manager.

golang runtimes installed in this way will match using anchore's CPE matching, which reference NVD and other CPE based vulnerability feeds.

**Comment by ukitazume** [comment]
Hi Nurmi,

I have a question. 
Does this ability make anchore-engine get the metadata from Golang binary and find the vulnerability?

For example, go binary like, ELF, mach-o, and PE can be read the dependencies, so anchore-engine v0.8.0 can be read it as metadata and find vulnerabilities of golang?
