### ISSUE TITLE
Disable feed_sync in config.yaml

### ISSUE THREAD

**Issue by CameronLonsdale** [anchore/anchore-engine#54]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**:

latest
 
**What I want**:

I want to be able to turn off the `feed_sync` functionality but retain the rest of the features provided by the `policy_engine` service. I see in the code to do that you can change this line:
https://github.com/anchore/anchore-engine/blob/fa7d52cd09435c807ed0c9179d521437276a89e4/anchore_engine/services/policy_engine/__init__.py#L32

from `True` to `False` (untested, but in my head I think that's what should happen). Would it be possible to move this option into the config.yaml file rather than hard coded?

**Comment by zhill** [comment]
If you just want to turn off the actual feed updates you can add this to your config.yaml:
```
feeds:
  selective_sync:
    enabled: True
    feeds:
      vulnerabilities: False
      packages: False
```

That should skip the actual data syncs. Just note that if you don't have the feed sync enabled you won't get any CVE data. If you ran it once and want to turn it off (e.g. already have info in the db) then this effectively freezes the cve data so it won't update.

I'll make a note to simplify the full disable mode. Should be an easy addition to the config moving forward.

**Comment by CameronLonsdale** [comment]
Awesome! Thanks for your help @zhill :)

**Comment by nurmi** [comment]
We've added a new configuration parameter that allows feed syncs to be disabled in commit 'd61f643d3652579d105b4500e6da6bf804cbf073', which is also available in the latest unstable container build (docker.io/anchore/anchore-engine:dev), for from-scratch testing purposes.

The new parameter is called 'sync_enabled: <True|False>', inside the 'feeds' section of config.yaml.
