### ISSUE TITLE
Layer caching in 2.3

### ISSUE THREAD

**Issue by CyberHippo** [anchore/anchore-engine#556]
**Is this a request for help?:**

Yes

---

Hi,

The [docs](https://docs.anchore.com/current/docs/engine/engine_installation/storage/layer_caching/) refer to a `config.yaml` file to enable layer caching. Since this file doesn't seem to be used anymore, what is the current way to enable it ? 
I'm using docker-compose to run anchore-engine.

Thank you.

**Comment by zhill** [comment]
@CyberHippo you can always mount a config.yaml into the container. You can get the config by copying it out of the image using `docker cp <containername>:/config/config.yaml ./config.yaml`. Then modify, and volume mount the modified version to `/config/config.yaml` in the container by editing the docker-compose.yaml and it will replace the old version. You'll need to restart or recreate the containers after you modify the docker-compse.yaml. `docker-compose up -d` will usually recreate automatically on changes.

**Comment by zhill** [comment]
@CyberHippo I've created https://github.com/anchore/enterprise-docs/issues/229 in the docs to track this. I'm going to close this issue now. Please re-open if there are remaining issues and feel free to update the docs issue if I didn't capture it well.
