### ISSUE TITLE
Remove anchore-manager absolute path from scripts/anchore-engine

### ISSUE THREAD

**Issue by CameronLonsdale** [anchore/anchore-engine#56]
**Is this a request for help?**:

Yep 

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

Feature Request 

**Version of Anchore Engine and Anchore CLI if applicable**:

latest
 
**What would be nice**:

Is it necessary to have the full path of anchore-manager here?
https://github.com/anchore/anchore-engine/blob/68d30042ea30b36c2bfd3c2ebf90ef6debf72a25/scripts/anchore-engine#L11

I'm experimenting with putting anchore in different base images and this is a big pain. Can we remove /usr/bin and let PATH do its thing? Thanks!

**Comment by zhill** [comment]
Thanks @CameronLonsdale, I'm fine with updating the anchore-engine script but we may just remove it from the code base generally and make the entrypoint for the container be anchore-manager directly now that we have that tool in place. You can take a similar approach for any containers you build. There are no other dependencies on scripts/anchore-engine.

**Comment by CameronLonsdale** [comment]
Good idea! @zhill

**Comment by nurmi** [comment]
This has been updated in the 0.3.0dev (latest in master) code, where the Dockerfile is still using anchore-engine script (without full path) and the script is calling anchore-manager (also without the full path).  We'll likely remove the 'anchore-engine' script altogether before the final 0.3.0 release, having the entrypoint be anchore-manager directly, as we continue to tune the new container build process
