### ISSUE TITLE
Malware scan not triggering

### ISSUE THREAD

**Issue by igormedo** [anchore/anchore-engine#582]
I've configured malware scanning in `analyzer_config.yaml` for analyzer container according to docs.
However, malware scanning shows an empty result through `v1/images/digest/content/malware` api endpoint

Logs contain no reference for any clamav related actions. The scanned container has test EICAR file in it.

The /home/anchore/clamav/db folder is empty. If I run freshclam manually, it's able to fetch clamdb

Engine DB Version: 0.0.13
Engine Code Version: 0.8.0

**Comment by igormedo** [comment]
Closing, switching to Degda.

**Comment by zhill** [comment]
We'll be updating docs to be more clear on how to configure this with docker-compose, our recommended deployment is with helm for kubernetes, but compose should work but you'll need to re-analyze images after the config change to have the scan run. But the docs need to be updated with clear instructions. Thanks.

**Comment by igormedo** [comment]
Thank you, I've found the correct path for the config in the helm charts.
