### ISSUE TITLE
Dockerfile updates needed to support openshift dynamic UID deployment behavior

### ISSUE THREAD

**Issue by nurmi** [anchore/anchore-engine#586]
Openshift environments can default to a behavior where containers are deployed with a random/dynamic UID for the container service process, which requires some handling of directory permissions in the Dockerfile to support - see 

https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/creating_images/creating-images-guidelines#openshift-specific-guidelines

Solution is to adjust the directory ownership / permissions in the Dockerfile as well as using a numeric rather than string USER value.  The default user/group will remain unchanged, but the update will allow for a dynamic/random UID to be used when deploying into openshift environments that require this behavior.

**Comment by zhill** [comment]
Closed in 0.8.2
