### ISSUE TITLE
Add registry with anonymous pull access

### ISSUE THREAD

**Issue by srmo** [anchore/anchore-engine#632]
**Is this a request for help?**:
Question
---

**Question/ FEATURE REQUEST?**:
We run a private registry with anonymous pull access (write access is secured by login).
I want to add that registry but that fails with Missing argument "REGISTRY_USER" (and password)

How can I add that registry without passing user/password?

**Version of Anchore Engine and Anchore CLI if applicable**:
```
anchore-cli --version
anchore-cli, version 0.8.1
```

**How to reproduce the issue**:
Call `anchore-cli registry add --skip-validate --insecure <my-registry-with-anonymous-pull>`

**Comment by zhill** [comment]
@srmo if you don't need credentials to pull the images, then you don't need to add the registry at all, just use `anchore-cli image add...`.

The registry-add command is only for adding credentials to the system, but by default the system will try anonymous access (e.g using DockerHub public images)

**Comment by srmo** [comment]
@zhill Ah! I misunderstood the feature. I thought it's something like "Add a registry. anchore will scan the images of that registry." 
I now understand that this is only for pulling the specific image I want to have scanned.
