### ISSUE TITLE
policy engine should 400 (with instructive message) on invalid bundle upload instead of 500

### ISSUE THREAD

**Issue by bhearn7** [anchore/anchore-engine#634]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**: Engine/CLI 0.7.2 & Enterprise/UI 2.3.1

**What happened**: Tried to upload a policy bundle through the UI & CLI that had policy_ids in some mappings but I hadn't actually created the policies

**What did you expect to happen**: To be presented with a more meaningful error

**Any relevant log output from /var/log/anchore**:

1. Error message: 
`Policy bundle addition returned a status code of 500 with the message: "Error response from policy service during bundle validation. Validation could not be performed: failed post url=http://anchore-anchore-engine-policy:8087/v1/validate_bundle"`
2. policy engine pod logs:
`[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-] Traceback (most recent call last):
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/api/controllers/synchronous_operations.py", line 807, in validate_bundle
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-]     resp.validation_details = [problem_from_exception(i, severity='error') for i in problems]
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/api/controllers/synchronous_operations.py", line 807, in <listcomp>
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-]     resp.validation_details = [problem_from_exception(i, severity='error') for i in problems]
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/api/controllers/synchronous_operations.py", line 233, in problem_from_exception
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-]     prob.details = eval_exception.message
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-] AttributeError: 'AttributeError' object has no attribute 'message'
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [_GenericHTTPChannelProtocol,318800,10.131.6.222] [PoolThread-twisted.internet.reactor-0] [anchore_engine.services.policy_engine.api.controllers.synchronous_operations/validate_bundle()] [ERROR] Failed processing bundle evaluation: 'AttributeError' object has no attribute 'message'
[service:enterprise-policy-engine] 2020-10-01 16:46:55+0000 [-] "10.131.6.222" - - [01/Oct/2020:16:46:55 +0000] "POST /v1/validate_bundle HTTP/1.1" 500 130 "-" "python-requests/2.23.0"`

**What docker images are you using**: Anchore Enterprise, UI, & CLI

**How to reproduce the issue**: Upload a bundle with a mapping that specifies a policy_id but doesn't actually have the policy included in the bundle

**Anything else we need to know**: YOU GUYS ROCK! 😎

**Comment by zhill** [comment]
Yep, this looks like an error in the validation path that isn't getting handled.

**Comment by zhill** [comment]
Closed by #645
