### ISSUE TITLE
Deactivating repository subscription does not halt scanning tags

### ISSUE THREAD

**Issue by nightfurys** [anchore/anchore-engine#635]
Watching a repository is handled by an asynchronous catalog process periodically performing inventory of repository and queuing up images for analysis. This process does an atomic check for the subscription state before evaluating each tag manifest in a serial order. This is not very fast process which makes it seem like the tags are trickling into the system. Deactivating or even deleting the watch/subscription record does not halt this stream as the subscription state check is performed once at the top of the process

**Comment by zhill** [comment]
Closed by #637 in the v0.8.2-dev branch. Did not auto-close since it hasn't yet merged to master until after the patch release, so closing manually.
