### ISSUE TITLE
Missing requirement PrettyTable

### ISSUE THREAD

**Issue by CameronLonsdale** [anchore/anchore-engine#64]
**Is this a request for help?**:

YES

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:

0.2.2 

**What happened**:

anchore-engine won't install and run without error because the package `PrettyTable` was not installed. It appears to be missing from `requirements.txt`

**Comment by zhill** [comment]
@CameronLonsdale Thanks! We'll get this fixed. It is usually pulled in as part of the anchore CLI install, but should definitely be listed in the engine requirements.txt as well. Marking this as a bug and will update when merged.

**Comment by CameronLonsdale** [comment]
@zhill Yeah that sounds correct, I was installing anchore-engine without anchore-cli and that error popped up. Definitely should be in the the engine requirements.txt :)
