### ISSUE TITLE
Fixed in version broken for some distros

### ISSUE THREAD

**Issue by nightfurys** [anchore/anchore-engine#665]
Computation of fixed-in version is broken for distros where vulnerabilities are found using an exact match i.e. vulnerable-in records instead of version comparison with a fixed-in record. Caused by changes introduced for handling multiple fixed-in records by https://github.com/anchore/anchore-engine/pull/640

**Comment by zhill** [comment]
This only affects the v0.8.2-dev branch, not master, and not any released code.
