### ISSUE TITLE
Query: Image Analyse

### ISSUE THREAD

**Issue by listenerme** [anchore/anchore-engine#68]
If I add an image with tag "latest" with anchore-cli, will anchore-engine continue to monitor the registry  and analyse it again if a new version of image is pushed with same latest tag? or do I need to remove the old one and add it again to reanalyse the image?

**Comment by zhill** [comment]
@listenerme if you add the image with the cli command: `anchore-cli image add <tag>` then the engine will automatically setup a 'tag_update' subscription that causes the system to poll the registry periodically to detect changes to the image that the tag is mapped to. The engine will then automatically analyze the new image when one is detected and the response you get for `anchore-cli image get <tag>` will be the analysis of the new image. You can view the history of a tag using `anchore-cli image get <tag> --show-history` and you'll see a record for each image (based on digest) that the engine has seen for the specified tag. If you want to disable this behavior there is a cli flag you can use to avoid the auto-subscribe capability.

**Comment by listenerme** [comment]
Thanks zhill, I have checked it.. my new image with same tag is not getting added into anchore and "image get" still shows the old image.

My image name convention is : REGISTRY:PORT/NAMESPACE:ImageName-VersionNumber

Following is the subscription status for that particular image

imagestore:6544/store:centos7.5-v1                                     analysis_update          True
imagestore:6544/store:centos7.5-v1                                     policy_eval              False
imagestore:6544/store:centos7.5-v1                                     tag_update               True
imagestore:6544/store:centos7.5-v1                                     vuln_update              False

**Comment by listenerme** [comment]
Ok, now it got updated, but its taking long time. It was 200MB image.. Cant the anchore engine get it detected at early? Is there any way set a time interval for checking image?

**Comment by zhill** [comment]
@listenerme the default interval for checking updates of tags in the registry is 3600 seconds, but you can configure it in the config.yaml by setting the image_watcher cycle timer in the services->catalog->cycle_timers section (example for 60s):
```
services:
  catalog:
    cycle_timers:
      image_watcher: 60
```
That timer is what controls when the service runs the checks of tag->digest mappings on the registry vs in the db. You can shorten it to catch updates faster, but the trade-off is that the system will be much more busy and as you add more tags the scan time for updates will grow, so just be aware of that.

**Comment by nurmi** [comment]
Closing this ticket - the ability to tune the image_watcher cycle timer (e.g. set it to a short time while doing initial testing/evaluation, and increase for steady state) should be sufficient information to address the initial concern/observation
