### ISSUE TITLE
Investigate using OCI format exclusively during analysis

### ISSUE THREAD

**Issue by luhring** [anchore/anchore-engine#680]
Currently, there are ways for the analysis flow to result in skopeo to save an image using the `dir:` format instead of the `oci:` format. `dir:` is non-standard and only intended for debugging; moreover, the Toolbox tools support the OCI format but do not support skopeo's proprietary `dir:` format.

The `dir:` format is used if either of these are true:

- The image uses foreign diffs: https://github.com/anchore/anchore-engine/blob/master/anchore_engine/clients/skopeo_wrapper.py#L102
- The image is not a Linux image: https://github.com/anchore/anchore-engine/blob/master/anchore_engine/clients/skopeo_wrapper.py#L113

**Objective:** Determine if it's possible to always use the OCI format for saving images, thus resolving the issue of downstream tools (like syft and grype) being unable to inspect the given image.

### Suggested task breakdown

1. Look into https://github.com/containers/skopeo/issues/545 and see if it's feasible to update skopeo itself to save Windows images using the OCI format and avoid using foreign diffs.
1. Look at what would need to change in the anchore-engine code if the `dir:` format were no longer present anywhere.
1. Determine stereoscope's behavior with Windows images.

**Comment by luhring** [comment]
Regarding task 3 —

Stereoscope appears to be capable of handling Windows OCI images, as long as all blobs are present within the OCI directory structure, and no unsupported media types are present (e.g. `application/vnd.oci.image.layer.nondistributable.v1.tar+gzip`).

I tested with the image `mcr.microsoft.com/windows/nanoserver:1903`. The OCI directory's `index.json` listed its manifest at `"sha256:2a8ca7db7332bc6c3b825a4540c33b47ad588947aa130f07b7493a863daa3ba3"`.

The manifest looked like this:

```json
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:b4382afec288f18a7255c91b9c5dfe37d66dc1aca7be8cefdbbd5b14ae794d3f",
    "size": 354
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.nondistributable.v1.tar+gzip",
      "digest": "sha256:0e31ee8f400716f940be9db76d6eedb1a903860385b4ca8f70513012d53fe1f1",
      "size": 103066803,
      "urls": [
        "https://mcr.microsoft.com/v2/windows/nanoserver/blobs/sha256:0e31ee8f400716f940be9db76d6eedb1a903860385b4ca8f70513012d53fe1f1"
      ]
    }
  ]
}
```

In order to get stereoscope to read the image successfuly, it was necessary to `curl` the referenced URL for the layer and save it in the `blobs/sha256` directory, and also to remove the `nondistributable` component from the layer's `mediaType`.

**Comment by wagoodman** [comment]
For task 1, PR https://github.com/containers/image/pull/1063 is in to add initial support to enable downloading of foreign layers. Another skopeo PR is needed after this one to expose the option on the CLI. Something to note, this will not change the media type of the layers which is `application/vnd.oci.image.layer.nondistributable.v1.tar+gzip`. [Per the OCI spec](https://github.com/opencontainers/image-spec/blob/master/layer.md#non-distributable-layers) the media type should not affect how an implementation downloads or uses the layer blob, but this may not be honored in all tooling implementations.

**Comment by luhring** [comment]
Task 2 was explored and implemented via https://github.com/anchore/anchore-engine/pull/684
