### ISSUE TITLE
[policy_engine] connection is blocked. (403)

### ISSUE THREAD

**Issue by KoreaSecurity** [anchore/anchore-engine#71]
**It seems that Korea's IP is blocked. (univ)
**Please confirm**

------------------------------in Korea------------------------------
root@ubuntu:~/aevolume# anchore-cli --debug system status
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /v1 HTTP/1.1" 200 0
<Response [200]>
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/v1/system
DEBUG:anchorecli.clients.apiexternal:GET insecure=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /v1/system HTTP/1.1" 200 2598
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
Service simplequeue (dockerhostid-anchore-engine, http://anchore-engine:8083): up
Service apiext (dockerhostid-anchore-engine, http://anchore-engine:8228): up
Service kubernetes_webhook (dockerhostid-anchore-engine, http://anchore-engine:8338): up
**Service policy_engine (dockerhostid-anchore-engine, http://anchore-engine:8087): down (unavailable)**
Service analyzer (dockerhostid-anchore-engine, http://anchore-engine:8084): up
Service catalog (dockerhostid-anchore-engine, http://anchore-engine:8082): up

Engine DB Version: 0.0.7
Engine Code Version: 0.2.3

------------------------------another country ------------------------------
[root@9933447cb204 /]# anchore-cli --debug system status
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /v1 HTTP/1.1" 200 0
DEBUG:anchorecli.clients.apiexternal:GET url=http://localhost:8228/v1/system
DEBUG:anchorecli.clients.apiexternal:GET insecure=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /v1/system HTTP/1.1" 200 2749
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
Service apiext (dockerhostid-anchore-engine, http://anchore-engine:8228): up
Service kubernetes_webhook (dockerhostid-anchore-engine, http://anchore-engine:8338): up
Service analyzer (dockerhostid-anchore-engine, http://anchore-engine:8084): up
Service catalog (dockerhostid-anchore-engine, http://anchore-engine:8082): up
**Service policy_engine (dockerhostid-anchore-engine, http://anchore-engine:8087): up**
Service simplequeue (dockerhostid-anchore-engine, http://anchore-engine:8083): up

Engine DB Version: 0.0.7
Engine Code Version: 0.2.3

**Comment by nurmi** [comment]
Greetings,

It would help us if you could send the result of an http request to the endpoint in question - there are often systems in-between that could be causing network traffic to be blocked or interfered with. 

We'd invite you to join our community slack channel as well (https://www.anchore.com/slack) as well, so that you could DM one of us, if you would like to share some other information (like an example source IP that we can check with our providers).

**Comment by kts2597** [comment]
I encounterd to same issue.

# anchore-cli system status
`Service catalog (dockerhostid-anchore-engine, http://anchore-engine:8082): up
Service analyzer (dockerhostid-anchore-engine, http://anchore-engine:8084): up
Service policy_engine (dockerhostid-anchore-engine, http://anchore-engine:8087): down (registered)
Service simplequeue (dockerhostid-anchore-engine, http://anchore-engine:8083): up
Service apiext (dockerhostid-anchore-engine, http://anchore-engine:8228): up
Service kubernetes_webhook (dockerhostid-anchore-engine, http://anchore-engine:8338): up

Engine DB Version: 0.0.7
Engine Code Version: 0.2.3` 

docker logs as below

`[service:policy_engine] 2018-07-17 05:52:09+0000 [-] [bootstrap] [INFO] initializing database
[service:policy_engine] 2018-07-17 05:52:10+0000 [-] [bootstrap] [INFO] Registration complete.
[service:policy_engine] 2018-07-17 05:52:10+0000 [-] [bootstrap] [INFO] Checking feeds client credentials
[service:policy_engine] 2018-07-17 05:52:11+0000 [-] [bootstrap] [ERROR] Preflight checks failed with error: 403 Client Error: Forbidden for url: https://ancho.re/v1/account/users/anon@ancho.re. Aborting service startup
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
    raise Exception("process exited: " + str(rc))
Exception: process exited: 1
[anchore-policy-engine] [anchore_manager.cli.service/startup_service()] [INFO] service process exited at (Tue Jul 17 05:52:11 2018): process exited: 1
[anchore-policy-engine] [anchore_manager.cli.service/startup_service()] [INFO] exiting service thread
`

the result of http request to the endpoint as below.

`# curl --verbose https://ancho.re/v1/account/users/anon@ancho.re
* About to connect() to ancho.re port 443 (#0)
*   Trying 104.28.13.5...
* Connected to ancho.re (104.28.13.5) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=sni189579.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
*       start date: Jul 09 00:00:00 2018 GMT
*       expire date: Jan 15 23:59:59 2019 GMT
*       common name: sni189579.cloudflaressl.com
*       issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /v1/account/users/anon@ancho.re HTTP/1.1
> User-Agent: curl/7.29.0
> Host: ancho.re
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Tue, 17 Jul 2018 05:59:52 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d9dc4c6477205684b7a78ea4c7b4b680c1531807192; expires=Wed, 17-Jul-19 05:59:52 GMT; path=/; domain=.ancho.re; HttpOnly
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 43ba7c2869ea8544-HKG
<
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host ancho.re left intact`


In addition, I cannot access to https://anchore.io with web browser. 
It also returned me http code 403.

**Comment by nurmi** [comment]
On this topic - it does look like there is something blocking the source traffic here - in order to take the next step, I'd like to ask if you could join our community slack channel so that we can potentially share some information privately (source IP examples, etc), so that we can take a look and check with our providers - https://www.anchore.com/slack

**Comment by nurmi** [comment]
I'll close out this issue, pending more information from those who are experiencing connectivity issues (information that we can use to check with our providers)
