### ISSUE TITLE
remote authentication with anchore engine using java client API

### ISSUE THREAD

**Issue by SyCode7** [anchore/anchore-engine#72]
I did like to integrate my java application with a remotely deployed anchore-engine. I have used the API Client specified [here ](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/apiext/swagger/swagger.yaml)as a guide . I still encounter authentication errors as below : 

`Exception in thread "main" io.swagger.client.ApiException: Unauthorized
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:922)
	at io.swagger.client.ApiClient.execute(ApiClient.java:838)
	at io.swagger.client.api.VulnerabilitiesApi.getImageVulnerabilitiesByTypeWithHttpInfo(VulnerabilitiesApi.java:142)
	at io.swagger.client.api.VulnerabilitiesApi.getImageVulnerabilitiesByType(VulnerabilitiesApi.java:127)
	at io.cavasTest.CavasTest.main(CavasTest.java:28)`

I tried authenticating via the code below - 
`   // Setup authentications (key: authentication name, value: authentication).
     authentications = new HashMap<String, Authentication>();
     authentications.put("basicAuth", new HttpBasicAuth());
     HttpBasicAuth httpBasicAuth = new HttpBasicAuth();
     httpBasicAuth.setUsername("xxxxx");
     httpBasicAuth.setPassword("xxxxx");`

**Comment by zhill** [comment]
hi @SyCode7 , looks like you're setting the username and password in a different HttpBasicAuth object than the one you added to the authentications map. I think you need:
```
authentications = new HashMap<String, Authentication>();
HttpBasicAuth httpBasicAuth = new HttpBasicAuth();
httpBasicAuth.setUsername("xxxxx");
httpBasicAuth.setPassword("xxxxx");
authentications.put("basicAuth", httpBasicAuth); 
```

**Comment by SyCode7** [comment]
@zhill  thank  you very much. This works,  you are right the credentials were set in the wrong object. 👍
