### ISSUE TITLE
Unable to add local docker image to anchore-cli

### ISSUE THREAD

**Issue by Shriyanshmit** [anchore/anchore-engine#721]
Hi,

Once I try to add local images to anchore-cli it is throwing error:

**Command** : docker-compose exec api anchore-cli image add testImage:latest

**Error:**

Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {'error_codes': ['REGISTRY_PERMISSION_DENIED'], 'raw_exception_message': 'Error encountered in skopeo operation. cmd=/bin/sh -c skopeo   inspect --raw --tls-verify=false  docker://docker.io/library/testImage:latest, rc=1, stdout=None, stderr=b\'time="2020-11-18T11:44:53Z" level=fatal msg="Error parsing image name \\\\"docker://docker.io/library/testImage:latest\\\\": Error reading manifest latest in docker.io/library/testImage: errors:\\\\ndenied: requested access to the resource is denied\\\\nunauthorized: authentication required\\\\n"\\n\', error_code=REGISTRY_PERMISSION_DENIED'}

Please let me know the command for add the local images. Once I add the image from docker.io, It is working fine.\

Thanks
Shreyansh Jain

**Comment by zhill** [comment]
Thanks @Shriyanshmit. Unfortunately, local images are not supported by Anchore Engine, they must be pulled from a registry. For getting vulnerabilities for a local image you can use [Grype](https://github.com/anchore/Grype).

If you have any other questions or need more detail please feel free to re-open this issue.
