### ISSUE TITLE
Add support for handling Kubernetes Dynamic webhook: ValidatingAdmissionWebhook requests

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#73]
Anchore Engine has support for an older kubernetes webhook call, the ImagePolicyWebhook, but newer webhooks have been added that should also be supported: ValidatingWebhook.

The expected flow is that the Engine is configured as an endpoint for the validating webhooks and receives pod specs and validates the referenced images against the currently 'active' policy for the authenticated anchore user. If the policy status result is 'pass' then the webhook returns success, else failure.

**Comment by Evesy** [comment]
I'd be very interested in using Anchore Engine to validate pod images against given policies to ensure users aren't deploying vulnerable images, using `latest` tags etc. but so far the only way I've found to get this up & running is https://github.com/viglesiasce/kubernetes-anchore-image-validator

It would be great if Anchore Engine itself could be directly added as an endpoint for those webhooks without the need for a middleman, I wouldn't be comfortable right now using something that might quickly fall out of compatibility with newer releases of either Kubernetes or Anchore Engine, especially since pods being able to launch is a pretty critical path

Look forward to seeing this for sure

**Comment by zhill** [comment]
@Evesy I'll be getting into this very soon, but right now I'm thinking that the solution is to use a distinct controller to moderate between k8s and anchore engine APIs for a few reasons:

1. Independent release cycles. Can modify, update, enhance the controller as needed without requiring a full anchore release
2. Decoupled caching behavior and timeouts for robustness and performance
3. Simpler testing and contribution

The plan is that Anchore would provide and maintain such a controller, hopefully alleviating some of your concerns about compatibility and longevity. Would that satisfy your requirements?

**Comment by Evesy** [comment]
Absolutely @zhill, sounds great 👍

**Comment by pbalogh-sa** [comment]
@antimack hi! We created also an admission controller which scan pods automatically. Our implementation uses CRD to store result of scans, and an other CRD used for defining whitelist which is a deployment based approach. If it sounds good for you, you would check https://github.com/banzaicloud/anchore-image-validator. You can find related helm chart here: https://github.com/banzaicloud/banzai-charts/tree/master/anchore-policy-validator.

**Comment by antimack** [comment]
@pbalogh-sa thanks for a quick reply! yeah, I've seen it and actually checking right now, have some questions regarding that:
1. https://github.com/banzaicloud/anchore-image-validator as I understood is your implementation of admission controller but if I check 
https://github.com/banzaicloud/banzai-charts/tree/master/anchore-policy-validator chart is using an image from 
https://github.com/viglesiasce/kubernetes-anchore-image-validator, it's a little bit confusing, so what admission controller are you guys using?
2. Whitelist and audit CRD's are specific for Helm charts, will the base functionality work for Deployments, pods etc. ?
Thanks in advance!

**Comment by pbalogh-sa** [comment]
@antimack
1. I've just updated anchore-policy-validator's README. Thanks for your remark. Default image is banzaicloud/anchore-image-validator in values.yaml.
2. The base functionality will work. If you want you will be able to define whitelist but it's not necessary.
In case of defined whitelist anchore-image-validator will check 'release' label if it's set, otherwise try to match pod name to whitelist. (You can define regex in a whitelist)

**Comment by antimack** [comment]
@pbalogh-sa awesome! thanks a lot, will give it a try.

**Comment by zhill** [comment]
@antimack Yes, you've found the controller we support officially. The banzaicloud one is quite interesting as well. For using ours, see: https://anchore.com/blog/admission-control-in-kubernetes-with-anchore/

The chart itself is in another repo: https://github.com/anchore/anchore-charts.

The blog covers the feature set, it's a bit different in that it supports a few ways of leveraging the webhook. I'm also currently working on some regex-based selectors on labels/annotations for both the namespace and object itself to allow the policy bundle selection to be more sophisticated. That should be coming out very soon (in testing phase).We aren't (yet) using CRDs, though that is an interesting direction and we've been thinking about something similar. If you have specific requirements/features you'd like to see please open issues on the controller's project, and we'd love feedback.

@pbalogh-sa I like what you guys have done, and am curious how the CRDs are working out for you operationally.

**Comment by antimack** [comment]
@zhill thanks for such a great answer! will definitely check it, I like that it's a native solution!

**Comment by zhill** [comment]
I'm going to close this issue now, as a quick wrap-up:

* Kubernetes Admission control support for Anchore Engine/Enterprise is available via the [Admission Controller](https://github.com/anchore/kubernetes-admission-controller)
* Install it via a [helm chart](https://github.com/anchore/anchore-charts/tree/master/stable/anchore-admission-controller). 

For further questions, feedback, or issues please file them in the respective repos. Each of those projects are under active development, so feature requests and PRs very welcomed.

**Comment by pbalogh-sa** [comment]
@zhill - We use one CRD to store scan results we call audits and audit's ownerreferences are set to scanned pod, so if the pod is deleted related scanlogs will be deleted by k8s garbage collector as well. An other CRD is used for whitelisting, and you can define release name or regexp to ignore scan result. We wrote a blog post about it: https://banzaicloud.com/blog/anchore-image-validation/
