### ISSUE TITLE
Add automation for publication of engined documentation as part of release

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#735]
During the release of new versions of Anchore Engine, the documentation should be published from the docs/ directory in the repo. Addition of the docs is being tracked in #734 and is scoped to local builds. This issue is for automation of the publication to a site.

May use GitHub Pages from a 'docs' branch, or open to other suggestions and alternatives if there is a better option.

Requirements:
1. Documentation updated on release of new version of Engine
2. Documentation should indicate the current version of Engine it is documenting
3. Domain will be engine.anchore.io
4. Pushes/PRs to development or release branches should not trigger documentation updates, only the actual release process itself should result in an update to documentation.

**Comment by robertp** [comment]
I have a working toolchain w/a GH action to GH pages. At the moment it's triggered on pushing a specifically formatted tag (`docs-v*.*.*`).  It includes building w/Hugo *only* from the docs branch, and deploys the built static site to a subdomain (e.g., engine.x.y). (The GH action commits into/deploys using a branch called `gh-pages`.)

The workflow is roughly like this:

1. `git checkout docs`
1. `cd docs; hugo new posts/mygreatdocs.md`
1. `[editor] content/posts/mygreatdocs.md`
1. `git add content/posts/mygreatdocs.md`
1. [Commit and push to `docs` branch]
1. [Review/approve/etc]
1. `git tag docs-v0.9.1; git push --tags`
1. GH action runs, deploying

This would presumably work differently for e.g. a PR workflow, something like:

1. [Cut branch, working there]
1. `cd docs; hugo new posts/mygreatdocs.md`
1. `[editor] content/posts/mygreatdocs.md`
1. `git add content/posts/mygreatdocs.md`
1. [Commit and push to your branch]
1. PR to `docs` branch
1. [Review/approve/etc]
1. [Merge your branch to `docs` branch]
1. `git tag docs-v0.9.1; git push --tags`
1. GH actionsruns, deploying

The GH action could be automatically triggered by pushing a semver tag on the repo, which is effectively the step that says "we are releasing". However, a docs update need not correspond with a release, and a release need not require a docs update.

**Comment by robertp** [comment]
@zhill when we're ready with the docs, the GH pages/actions side of things is well understood and ready to roll out

**Comment by zhill** [comment]
@robertp I'll have the content ready very soon and will update here when the docs/ directory is ready and we can get the CI side added.

**Comment by robertp** [comment]
**Workflow/process update**

1. Branch from master
2. Change docs
3. PR to master
4. At release time (or any time docs need updating): maintainer merges master to publish-docs branch
5. Merge to publish-docs branch automagically triggers GH Action, building site w/hugo and pushing to GH pages
