### ISSUE TITLE
Anchore engine kills itself in docker or with docker-compose

### ISSUE THREAD

**Issue by Karreg** [anchore/anchore-engine#74]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.2.3

Name: anchore-engine
Version: 0.2.3

 
**What happened**:

When starting Anchore engine, either with docker start or docker-compose up, it kills itself randomly (but far more often than not killing itself). Key logs are:

```
anchore-engine_1  | [anchore-catalog] [anchore_manager.cli.service/terminate_service()] [INFO] Found old pid for service: anchore-catalog. Terminating it
anchore-engine_1  | [anchore-catalog] [anchore_manager.cli.service/terminate_service()] [INFO] killing old twistd pid: 18
anchore-engine_1  | /usr/bin/anchore-engine: line 11:     7 Killed                  /usr/bin/anchore-manager --configdir ${CONFIGDIR} service start $REST
anchore_anchore-engine_1 exited with code 137
```

**What did you expect to happen**:
Just start without failing. I don't see the check of PID in a container world, it does not make sense to me (am I missing something though?).
As a workaround, in the container, any running PID should just be ignored, since it's probably leftovers from the last execution.

**Any relevant log output from /var/log/anchore**:
```
...
[MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB connection configured: True
[MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB attempting to connect...
[MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB connected: True
[MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB compatibility check: running...
[MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB compatibility check success
[MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB post actions: running...
[MainThread] [anchore_manager.cli.service/start()] [INFO] DB version and code version in sync.
[MainThread] [anchore_manager.cli.service/start()] [INFO] Starting services: ['anchore-catalog', 'anchore-simplequeue', 'anchore-api', 'anchore-kubernetes-webhook', 'anchore-worker', 'anchore-policy-engine']
[anchore-catalog] [anchore_manager.cli.service/startup_service()] [INFO] cleaning up service: anchore-catalog
[anchore-catalog] [anchore_manager.cli.service/terminate_service()] [INFO] Found old pid for service: anchore-catalog. Terminating it
[anchore-catalog] [anchore_manager.cli.service/terminate_service()] [INFO] killing old twistd pid: 18
/usr/bin/anchore-engine: line 11:     7 Killed                  /usr/bin/anchore-manager --configdir ${CONFIGDIR} service start $REST

```

**What docker images are you using**:
anchore/anchore-engine                                     latest              7f60d4a6fdb7        3 weeks ago 

**How to reproduce the issue**:
Run anchore engine with the docker-compose given in GitHub, wait until the vulnerabilities are fetched, and try stopping/starting the anchore-ending container.
I could not find any context that could change the behavior. I had the issue after a system reboot between stop and start, and I also had no issue between 2 fast restarts... However, it seems that time has globally a positive impact on the next try.

**Anything else we need to know**:

**Comment by nurmi** [comment]
Hi @Karreg - thank you for the detailed report!  I looked at the logic, and I do see a way for this condition to arise (when new anchore service processes are getting the same PIDs as previous, when the previous   service PIDs are shut down with a hard kill (-9)) - I'll investigate further and will report status in this ticket, I believe the solution will be to improve the anchore manager service restart logic to be more specific about determining if an existing service is still running.

**Comment by Karreg** [comment]
Thanks for the fix. I'll be glad to test it as soon as a new image is available :)

**Comment by Karreg** [comment]
Is there any workaround until the new image is available? It's kinda blocking me to advance on the other issue ;)

**Comment by nurmi** [comment]
hi @Karreg - I can think of two workarounds currently if this condition is cropping up a lot:

1) use the process

```
docker-compose down 
docker-compose up -d
```
instead of 'stop, start', which will result in a clean pidfile state each time.

2) enable 'auto_restart_services: True' in your config.yaml - this should instruct the anchore_manager to automatically restart the service processes if they unexpectedly fail, and should result in all the services up and running.  

If you're in a testing environment only, the final workaround could be to try the dev container, which is auto-built from the latest code in master (which has the fix!), but caveat there is that we cannot guarantee upgrades/stability for dev containers, generally.  That container is always available at anchore/anchore-engine:dev on dockerhub.

Thanks!
-dan

**Comment by Karreg** [comment]
OK, thanks for the workaround!
