### ISSUE TITLE
Archive rules not working

### ISSUE THREAD

**Issue by juanjolmm** [anchore/anchore-engine#745]
**Is this a request for help?**:
Yes, I need your help

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
Not sure if it is bug, but something is not working as expected.
anchore-cli, version 0.8.2
"db_version": "0.0.13",
"version": "0.8.2"

**What happened**:
I have configured Anchore to use an S3 bucket to archive images. This is the configuration:
archive:
      compression:
        enabled: true
        min_size_kbytes: 100
      storage_driver:
        config:
          bucket: archive-bucket
          iamauto: true
          region: us-east-1
        name: s3
Also I have created two rules:
Global        Transition        Analysis Age (Days)        Tag Versions Newer        Registry        Repository        Tag        Last Updated
True          delete            10                         2                         *               *                 *          2020-11-26T17:23:28Z
True          archive           10                         1                         *               *                 *          2020-11-26T17:23:17Z
So, if I am not wrong I would have active one version (the newer version) in the DB and another version in the archive, older versions that those two would be deleted.
But it not working, if I execute "anchore-cli analysis-archive images list", I get no results
And If I execute "anchore-cli image list --show-all" I can see many images with a lot of different versions.

**What did you expect to happen**:
I expect to have images in the archive.

Let me know if you need more information please.
Thank you very much in advance.

**Comment by juanjolmm** [comment]
Hello again, I have been taking a look at this guide: https://docs.anchore.com/current/docs/engine/engine_installation/storage/object_store/migration/
But I am not sure if it applies to my case, I don't have the enterprise edition and the config in my config.yaml is different.
In catalog I had this config: 
archive:
      compression:
        enabled: true
        min_size_kbytes: 100
      storage_driver:
        config: {}
        name: db

And I now I have:
archive:
      compression:
        enabled: true
        min_size_kbytes: 100
      storage_driver:
        config:
          bucket: anchore-archive
          iamauto: true
          region: us-east-1
        name: s3

But in the guide:
object_store:
      compression:
        enabled: false
        min_size_kbytes: 100
      storage_driver:
        name: db
        config: {}
    analysis_archive:
      enabled: true
      compression:
        enabled: false
        min_size_kbytes: 100
      storage_driver:
        name: s3
        config: 
          access_key: 9EB92C7W61YPFQ6QLDOU
          secret_key: TuHo2UbBx+amD3YiCeidy+R3q82MPTPiyd+dlW+s
          url: 'http://minio-ephemeral-test:9000'
          region: null
          bucket: analysisarchive 

I executed this command: 
anchore-manager objectstorage --db-connect "postgresql://...." migrate --to-analysis-archive --bucket analysis_archive config.yaml config_dest.yaml

And I get this error:
[MainThread] [anchore_manager.util.logging/log_error()] [ERROR] Error: No valid destination configuration found. Needed a configuration section with key "analysis_archive" in the catalog service key
In my config if I replace archive by analysis_archive it works (log attached).
But now I am not sure it the archive is working in the DB or not.
[log.txt](https://github.com/anchore/anchore-engine/files/5609002/log.txt)

**Comment by zhill** [comment]
Hi @juanjolmm, can you provide some examples of image records that you expected to be archived? The other area to look is in the archive configuration (s3) but that should show errors in the catalog container log if it is causing issues or there are other problems in the execution of the rule processing. If you can share any error messages in that log you should see things by grepping 'archive'.

**Comment by juanjolmm** [comment]
Hello zhill, you are completely right, I saw some errors in the catalog and after that I changed the configuration of the archive and I did the required migration using this guide: https://docs.anchore.com/current/docs/engine/engine_installation/storage/object_store/migration/
Now, it seems everything is working fine.
Thank you very much.

**Comment by zhill** [comment]
@juanjolmm you're close. You'll have the newest tag version in the active set in the DB, and the 2 older versions in the archive set. The delete transition only examines the records already in the archive. So it controls the size of the archive set and would delete (from the archive) all but the 2 newest tag versions found in the archive.

**Comment by zhill** [comment]
I'm going to close this as answered, but @juanjolmm please re-open if the question was not resolved. Thanks!
