### ISSUE TITLE
Adding an insecure registry is failing

### ISSUE THREAD

**Issue by Karreg** [anchore/anchore-engine#76]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.2.3
Name: anchore-engine
Version: 0.2.3
 
**What happened**:

I have tried to follow the documentation here to add an registry that uses self signed certificate:

https://anchore.freshdesk.com/support/solutions/articles/36000003888-configuring-access-to-registries

Especially this part:

*Anchore Engine will only pull images from a TLS/SSL enabled registry. If the registry is protected with a self signed certificate or a certificated signed by an unknown certificate authority then the **--insecure** parameter can be passed which instructs the Anchore Engine not to validate the certificate.*

So I'm using this command:

`anchore-cli registry add <myrepo>:5002 <user> '<pass>' --insecure`

But I get a:

```
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://<myrepo>:5002,<user>) - exception: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
HTTP Code: 406
```

**What did you expect to happen**:

The registry should be added thanks to the insecure flag.

**Any relevant log output from /var/log/anchore**:

The log in the container say the same error:

```
[service:api] 2018-07-25 14:32:56+0000 [-] "172.23.0.1" - - [25/Jul/2018:14:32:56 +0000] "POST /v1/registries?validate=True HTTP/1.1" 406 336 "-" "python-requests/2.17.3"
[service:catalog] 2018-07-25 14:32:56+0000 [_GenericHTTPChannelProtocol,50,172.23.0.3] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.docker_registry/ping_docker_registry()] [WARN] failed check to access registry (https://<myrepo>:5002,<user>) - exception: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
[service:catalog] 2018-07-25 14:32:56+0000 [-] "172.23.0.3" - - [25/Jul/2018:14:32:56 +0000] "POST /v1/system/registries?validate=True HTTP/1.1" 406 336 "-" "python-requests/2.17.3"
```

**What docker images are you using**:

anchore/anchore-engine                                     latest              7f60d4a6fdb7        3 weeks ago         527MB

**How to reproduce the issue**:

Trying to add a self signed registry.

**Anything else we need to know**:

The registry in question is an Artifactory registry. I have no issue using it with docker, kubernetes and clair with the insecure flag.

Thanks!

**Comment by Karreg** [comment]
Thanks for the fast reply, let me check each point.

1. Yes, it's running on https (it's now mandatory for docker registry afaik). It's using a certificate from an unknown CA, and not a self signed certificate. But in general it falls in the same category when using tools. Maybe it has an impact here?

2. When I use the two commands, I have the exact same result, being the 406 error. No difference with or without the --insecure flag And the output is exactly the same as yours.

```
$ anchore-cli registry add <repo>:5002 <user> '<pass>'                                               
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://<repo>:5002,<user>) - exception: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
HTTP Code: 406

$ anchore-cli registry add <repo>:5002 <user> '<pass>' --insecure
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://<repo>:5002,<user>) - exception: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
HTTP Code: 406
```

3. Here is the result:
```
$ anchore-cli --debug --json registry add <repo>:5002 <user> '<pass>' --insecure
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /v1 HTTP/1.1" 200 0
DEBUG:anchorecli.clients.apiexternal:POST url=http://localhost:8228/v1/registries?validate=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8228 "POST /v1/registries?validate=True HTTP/1.1" 406 336
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 406
{
    "detail": {}, 
    "httpcode": 406, 
    "message": "cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://<repo>:5002,<user>) - exception: (\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",)"
}
```

4. It seems the registry_verify is not correctly set:

```
$ anchore-cli --debug --json registry add <repo>:5002 <user> '<pass>' --skip-validate
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8228 "GET /v1 HTTP/1.1" 200 0
DEBUG:anchorecli.clients.apiexternal:POST url=http://localhost:8228/v1/registries?validate=False
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8228 "POST /v1/registries?validate=False HTTP/1.1" 200 276
DEBUG:anchorecli.cli.utils:fetched httpcode from response: 200
[
    {
        "created_at": "2018-07-26T07:28:08Z", 
        "last_updated": "2018-07-26T07:28:08Z", 
        "registry": "<repo>:5002", 
        "registry_type": "docker_v2", 
        "registry_user": "<user>, 
        "registry_verify": true, 
        "userId": "admin"
    }
]
```

**Comment by nurmi** [comment]
thanks @Karreg - still a mystery but it gives us something to look into (signed by untrusted CA rather than self-signed is not a condition I've tested - we're using standatrd python http clients for this interaction but I'll see if I can figure out if that would change the behvaior.

as far as question 4), I noticed that in your command you removed the '--insecure' from the test, we'd like to make sure that when --insecure is supplied, the 'registry_verify' is being correctly set to 'false'.  the process then would be:

```
anchore-cli registry del <registry_hostname>:5002
anchore-cli --json --debug registry add <registry_hostname>:5002 <user> <pass> --insecure --skip-validate
(should see 'registry_verify' set to false)
```

Btw, after the above (if you see 'registry_verify' correctly set to false when --insecure is supplied, you could try adding an image, there is a different code path for image fetch versus registry ping, so its possible that for now you could make progress by just skipping the credential check when adding a registry credential (--skip-validate)

**Comment by Karreg** [comment]
Hello,

My bad, I have not seen the --insecure flag (I even asked myself why it was removed, but I thought it was just like that).

So the behavior is correct with the flag:

```
$ ac registry add <repo>:5002 <user> '<pass>' --skip-validate --insecure
Registry: <repo>:5002
User: <user>
Type: docker_v2
Verify TLS: False
Created: 2018-07-27T09:08:35Z
Updated: 2018-07-27T09:08:35Z
```

When I try to add an image from this repo, here is the result:

```
ac image add <repo>:5002/dt-test/hello-world:latest
Image Digest: sha256:32d85a45b217a48e26fd4ba8484606c28d4fdba72327fd62750c46037a7db704
Analysis Status: not_analyzed
Image Type: docker
Image ID: 32d85a45b217a48e26fd4ba8484606c28d4fdba72327fd62750c46037a7db704
Dockerfile Mode: None
Distro: None
Distro Version: None
Size: None
Architecture: None
Layer Count: None

Full Tag: <repo>:5002/dt-test/hello-world:latest
```

and the image is analyzed, everything seems fine.
It seems that it's the validate step that is blocking?

Thanks for the help! It has unblocked me until a fix.

Is there any way to add the unknown CA certificates in any way in anchore, so that it considers the CA as known?

**Comment by nurmi** [comment]
thanks @Karreg - I want to leave this issue open, at least until the new registry validate implementation can be tested (available today in anchore/anchore-engine:dev <-- latest development image, or anchore/anchore-engine:v0.2.4rc0  <-- release candidate for 0.2.4) - I believe the new implementation should work properly (in that it will circumvent all ssl cert checking when --insecure is supplied, by passing verify=False to python requests.get() routine for the check).

**Comment by Karreg** [comment]
Thanks. I'll keep an eye on it.

And what about configuring the tools with the unknown CA certificate so the registry is considered valid? Is it something that can be done somehow?

**Comment by Karreg** [comment]
Hi @nurmi 
Thanks for the update, I'll try as soon as I'm back on this subject. I'll let your know the results :)

**Comment by Karreg** [comment]
Hello, I'm back on the subject.
I tried again, and by passing the --insecure to the registry add action, it's working.

Funny command now includes 2 different --insecure options... One for the anchore engine, and one for the registry :)

**Comment by atnz28** [comment]
Hello, I have the same issue to add external registry. 
Once I added --insecure and --skip-validate flags. I was able to add the external registry, but I was able to add images from that registry to Anchore image list.

**Comment by jcsindelar** [comment]
I am also having the same issue as atnz28. I can create the registry with my ci token, but I am getting a registry permission denied error now when I attempt to add an image.

Any advice?
