### ISSUE TITLE
Docker image not getting anlyzed with anchore-engine

### ISSUE THREAD

**Issue by vedaprasad** [anchore/anchore-engine#78]
**Is this a request for help?**:
help
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.2.3
 
**What happened**:
Image is not being registered.
anchore-cli image add registry.gitlab.com/its_vedu/nginx-docker:latest
Image Digest: sha256:21a54b24b692dd1b7e7acc623ade182b649a12cbc63eb090abc801d5556c58d4
Analysis Status: not_analyzed
Image Type: docker
Image ID: de278a11a415411431f9ca81a14ca2a6250a7cf03576c09236b0d6d37a8c587f
Dockerfile Mode: None
Distro: None
Distro Version: None
Size: None
Architecture: None
Layer Count: None

**What did you expect to happen**:
Image to be registered.

**Any relevant log output from /var/log/anchore**:
anchore-engine_1 | [service:simplequeue] 2018-07-25 23:09:00+0000 [-] "172.18.0.3" - - [25/Jul/2018:23:09:00 +0000] "POST /v1/queues/watcher_tasks/is_inqueue HTTP/1.1" 200 3 "-" "python-requests/2.17.3"
anchore-engine_1 | [service:simplequeue] 2018-07-25 23:09:00+0000 [-] "172.18.0.3" - - [25/Jul/2018:23:09:00 +0000] "POST /v1/queues/watcher_tasks/?qcount=0&forcefirst=False HTTP/1.1" 200 5 "-" "python-requests/2.17.3"

anchore-engine_1 | [service:simplequeue] 2018-07-25 23:09:28+0000 [-] "172.18.0.3" - - [25/Jul/2018:23:09:28 +0000] "GET /v1/leases/analyzer_queue/release/?client_id=d1ea844bb62d:17:140187329885952:&epoch=2302[service:policy_engine] 2018-07-25 23:09:29+0000 [-] [bootstrap] [INFO] Registration complete.
anchore-engine_1 | [service:policy_engine] 2018-07-25 23:09:29+0000 [-] [bootstrap] [INFO] Checking feeds client credentials

anchore-engine_1 | Traceback (most recent call last):
anchore-engine_1 | File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
anchore-engine_1 | raise Exception("process exited: " + str(rc))
anchore-engine_1 | Exception: process exited: 1
anchore-engine_1 | [anchore-policy-engine] [anchore_manager.cli.service/startup_service()] [INFO] service process exited at (Wed Jul 25 23:09:30 2018): process exited: 1
anchore-engine_1 | [anchore-policy-engine] [anchore_manager.cli.service/startup_service()] [INFO] exiting service thread

**What docker images are you using**:
         Name                   Command                   State                    Ports
-------------------------------------------------------------------------------------------------
aevolume_anchore-db_1    docker-entrypoint.sh     Up                       5432/tcp
                         postgres
aevolume_anchore-        /bin/sh -c               Up                       0.0.0.0:8083->8083/tcp
engine_1                 /usr/bin/anchor ...                               , 0.0.0.0:8084->8084/t
                                                                           cp, 0.0.0.0:8087->8087
                                                                           /tcp, 0.0.0.0:8228->82
                                                                           28/tcp,
                                                                           0.0.0.0:8338->8338/tcp

**How to reproduce the issue**:

**Anything else we need to know**:
docker-compose ps 

Docker-compose ps

     Name                   Command                   State                    Ports
aevolume_anchore-db_1 docker-entrypoint.sh Up 5432/tcp
postgres
aevolume_anchore- /bin/sh -c Up 0.0.0.0:8083->8083/tcp
engine_1 /usr/bin/anchor ... , 0.0.0.0:8084->8084/t
cp, 0.0.0.0:8087->8087
/tcp, 0.0.0.0:8228->82
28/tcp,
0.0.0.0:8338->8338/tcp

**Comment by nurmi** [comment]
Hi @vedaprasad - I'm going to close this issue as quite a bit of time has passed, but feel free to re-open if your issue is not resolved or you have more information for us to discuss

**Comment by vedaprasad** [comment]
HI @nurmi: Please go ahead, the issue was with intermediate SSL certs on my Vagrant host. The issue got resolved when I tried it on an AWS instance.

**Comment by nurmi** [comment]
That's great to hear!  Thanks @vedaprasad
