### ISSUE TITLE
Anchore-engine and Nexus 3 private registry

### ISSUE THREAD

**Issue by atnz28** [anchore/anchore-engine#821]
**Is this a request for help?**:

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

**Version of Anchore Engine and Anchore CLI if applicable**:
v0.8.2

**What happened**:
docker-compose exec api anchore-cli image add my-private-nexus-repo/alpine:3.10

**What did you expect to happen**:
I'd expect image added to the image list, but instead got 404 error:
"... Error parsing image name .... Invalid status code from registry 404 (Not Found) .... error_code=SKOPEO_UNKNOWN_ERROR"

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:
anchore/anchore-engine:v0.8.2
anchore/engine-cli:v0.8.2
postgres:9

**How to reproduce the issue**:

**Anything else we need to know**:
I have no issue to pull image from my private registry by running this docker command on the VM anchore is on:
docker pull my-private-nexus-repo/alpine:3.10

**Comment by atnz28** [comment]
It was my haproxy issue. Once I fixed the ACL routing rule, I am able to add images from my Nexus container repo.

**Comment by bikashlama541** [comment]
Hi can you please share what was the change you made to your haproxy file?

**Comment by bikashlama541** [comment]
Hi @atnz28 I would really appreciate if you could share me your solution.

**Comment by atnz28** [comment]
It was basically in my case, my HAProxy routes incoming requests whether is a docker or else. Anchore is running RedHat 8 which is hiding the docker layer. Thus, my HAProxy sent the request to diff location instead of the docker image location (Hence 404 error). All I had to do is added a new rule to HAProxy to route Anchore request. 
Look at the HAProxy logs. Hope it helps.

**Comment by bikashlama541** [comment]
Thank you so much for replying @atnz28 . For some reason, I can relate to what you are saying. I am totally not good at using Haproxy configuration. I checked logs, nothing has been helping me. Can you show me the change you made from your side on haproxy file, where did you add that HAProxy route in config file, with edits. I would appreciate your help.
