### ISSUE TITLE
Update the Helm chart to use latest stable version of anchore-engine

### ISSUE THREAD

**Issue by Karreg** [anchore/anchore-engine#84]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**: N/A

 
**What happened**:

The Helm chart is still referencing Anchore 0.2.3, though version 0.2.4 is available for a few weeks.

**What did you expect to happen**:

The Helm chart should be updated with the latest stable version when it comes out

**Comment by zhill** [comment]
Hi @Karreg , thanks for filing this. We're working on an update and it should be released soon. If you want you can also set the image directly in invocation using: '--set image.tag=anchore/anchore-engine:v0.2.4' to try it out.

For bugs/issues with the chart itself, can you please file these in github.com/helm/charts so we can resolve them with PRs as things land? If you mention me in the issue I'll be sure to see it and you can track progress there.

Thanks!

**Comment by Karreg** [comment]
Got it. I will create issues over there for the chart. Thanks!
