### ISSUE TITLE
Define resources limits (and document resources recommendations)

### ISSUE THREAD

**Issue by Karreg** [anchore/anchore-engine#85]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**: 0.2.3 for both

 
**What happened**:

We have a big pike of memory from anchore-engine that crashes the kubernetes node (we will add limits on that to avoid it to happen again) because there is no resource limit on the pods. This could cause big issues, especially when scaling, if every pod becomes hungry on memory.

The pike happens after one hour, and it can become out of control:

![image](https://user-images.githubusercontent.com/9166144/44735098-ca210c00-aaeb-11e8-90f5-4277bfcc644d.png)

**What did you expect to happen**:

The memory should stay in control.
Also, what are your recommendation on resources? How should we define our resources so that anchore works fine?

**Any relevant log output from /var/log/anchore**:

I'm still trying to get them before the pod crashes.

**What docker images are you using**:

anchore-engine 0.2.3

**How to reproduce the issue**:

Install on a kubernetes cluster and monitor memory.

**Anything else we need to know**:

**Comment by zhill** [comment]
Hi @Karreg , this is something we're aware of but generally it's a function of the size of images being analyzed as well as concurrency level for components like the catalog and policy-engine. I believe there is a typo in the chart that indicates only one core service pod can run, but that has been removed as a real restriction and you can scale out the core services along with the worker deployment to ensure sufficient resources.

Our general resource recommendations are here: https://anchore.freshdesk.com/support/solutions/folders/36000173067

We're always working to make the resource consumption more consistent as well, but for the current version it's just best to provision a 4GB+ of memory to the core containers. Anchore does a lot of data processing which is fairly memory intensive.

We're happy to help with other recommendations as well on our slack channel if you're interested in an invite: https://communityinviter.com/apps/anchorecommunity/anchore

**Comment by Karreg** [comment]
Thanks for the quick reply. I was not able to find the reco in the documentation, and I see this is under another section. That explains why. But that's great you already have that documented :+1: 

We'll follow your recommendations, and yes, I'll apply to a slack invite.

Thanks! :bowing_man:
