### ISSUE TITLE
Docker Image download fails on Copying blob

### ISSUE THREAD

**Issue by mc422** [anchore/anchore-engine#86]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

BUG REPORT 

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.2.4
 
**What happened**:
When adding image for analysis, anchore-engine fails to download image, when getting image source signatures and copying blob

**What did you expect to happen**:
Successfully download image and analyze

**Any relevant log output from /var/log/anchore**:

[Thread-10945] [anchore_engine.auth.skopeo_wrapper/download_image()] [ERROR] command failed with exception - Error encountered in skopeo operation. cmd=/bin/sh -c skopeo copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}"  docker://us.gcr.io/api@sha256:3f2f3c60de630170647e33a17d29d2f5ce5b83b9d4fa3fdda2d8a48a97b94690 oci:/workspace/e10ccd52-df28-485b-80a8-7935ad43df36/raw:image, rc=1, stdout=Getting image source signatures Copying blob sha256:469cfcc7a4b3947a4fa549c68cf4f8570be53779725f0c19f3d33d1520b08db0   0 B / 69.78 MB   318.39 KB / 69.78 MB   1.06 MB / 69.78 MB   1.92 MB / 69.78 MB   2.72 MB / 69.78 MB   3.90 MB / 69.78 MB   5.01 MB / 69.78 MB   6.37 MB / 69.78 MB   8.06 MB / 69.78 MB   9.58 MB / 69.78 MB   10.94 MB / 69.78 MB   11.86 MB / 69.78 MB   13.48 MB / 69.78 MB   14.65 MB / 69.78 MB   16.33 MB / 69.78 MB   18.25 MB / 69.78 MB   20.56 MB / 69.78 MB   22.98 MB / 69.78 MB   24.92 MB / 69.78 MB   27.31 MB / 69.78 MB   29.15 MB / 69.78 MB   31.33 MB / 69.78 MB   33.58 MB / 69.78 MB   35.17 MB / 69.78 MB   36.55 MB / 69.78 MB   38.22 MB / 69.78 MB   39.17 MB / 69.78 MB   40.73 MB / 69.78 MB   42.67 MB / 69.78 MB   44.86 MB / 69.78 MB   47.01 MB / 69.78 MB   48.64 MB / 69.78 MB   50.08 MB / 69.78 MB   52.64 MB / 69.78 MB   53.75 MB / 69.78 MB   56.17 MB / 69.78 MB   58.12 MB / 69.78 MB   59.73 MB / 69.78 MB   62.09 MB / 69.78 MB   62.84 MB / 69.78 MB   63.55 MB / 69.78 MB   66.15 MB / 69.78 MB   68.73 MB / 69.78 MB   69.78 MB / 69.78 MB  8s Copying blob sha256:dbdfc33d70d157d5c1bf362872b271f82719008b02f70696c615618feee513b8   0 B / 87.97 MB   282.67 KB / 87.97 MB   1.17 MB / 87.97 MB   1.93 MB / 87.97 MB   3.28 MB / 87.97 MB   4.48 MB / 87.97 MB   5.73 MB / 87.97 MB   6.98 MB / 87.97 MB   8.25 MB / 87.97 MB   9.51 MB / 87.97 MB   10.95 MB / 87.97 MB   12.75 MB / 87.97 MB   14.79 MB / 87.97 MB   17.04 MB / 87.97 MB   19.14 MB / 87.97 MB   20.92 MB / 87.97 MB   22.98 MB / 87.97 MB   25.56 MB / 87.97 MB   79.45 MB / 87.97 MB   81.33 MB / 87.97 MB   81.97 MB / 87.97 MB   82.36 MB / 87.97 MB   83.33 MB / 87.97 MB   85.25 MB / 87.97 MB   87.11 MB / 87.97 MB   87.97 MB / 87.97 MB  11s Copying blob sha256:091dcf8d1297433afc5cd640cd1f2e1922bf508ac3d97f3180331044602c0d64   0 B / 360 B   360 B / 360 B  0s Copying blob sha256:47b108a7b085d80e72eb9d71a2d009e99de6675a2481f340b2641f36665c6b6f   0 B / 30.33 MB   296.24 KB / 30.33 MB   1.17 MB / 30.33 MB   2.25 MB / 30.33 MB   3.56 MB / 30.33 MB   5.26 MB / 30.33 MB   7.11 MB / 30.33 MB   9.34 MB / 30.33 MB   11.56 MB / 30.33 MB   13.39 MB / 30.33 MB   15.36 MB / 30.33 MB   17.12 MB / 30.33 MB   19.01 MB / 30.33 MB   21.39 MB / 30.33 MB   24.03 MB / 30.33 MB   26.72 MB / 30.33 MB   29.31 MB / 30.33 MB   30.33 MB / 30.33 MB  3s Copying blob sha256:1da3817aaec16f5824a90ee418820c07505cf31df01b6a33, stderr=time="2018-08-30T19:37:01Z" level=fatal msg="Error reading blob sha256:1da3817a38ce8ada0948af5faec16f5824a90ee418820c07505cf31df01b6a33: Get https://storage.googleapis.com/us.artifacts.appspot.com/containers/images/sha256:1da3817a38ce8ada0948af5faec16f5824a90ee418820c07505cf31df01b6a33?Expires=1535658391&GoogleAccessId=anchore-engine@iam.gserviceaccount.com&Signature=hqra7YtraiY18ZfuF3AJo1Ap/V6M4OHrhSE8sfZhMpFIbFADatFBJAic53tqlf9t/K%2BSPujKcwCIHdUIwm35jDAhTsQDAXmPKEd3cfwekhIvoKPJebxZM6dxEiMzU%MmIuBhdvIm0iSeNvEdecnkOWJtr5CBew4/4g%2Bnj/l5aHJS5%2BgODjd957C6%2B6mz/YTSVBtNZbO3pQjRhT0eBBvMj3D%3D: dial tcp 216.58.193.144:443: i/o timeout"

**What docker images are you using**:
Private image

**How to reproduce the issue**:

**Anything else we need to know**:
I create a named docker volume and use the named volumes to mount /tmp dir inside container.
* create docker volume
`docker volume create -o 'o=size=4000m' -o device=tmpfs -o type=tmpfs anchore-workspace`
* update the config.yaml to add tmp_dir
`tmp_dir: '/workspace'`
* update docker-compose.yaml to use named volume inside anchore-engine
```
volumes:
  anchore-workspace:
    external: true

services:
  anchore-engine:
    volumes:
     - ${PWD}/config:/config/:Z
     - anchore-workspace:/workspace:z
```

**Comment by nurmi** [comment]
Worked with @mc422 directly to determine that the cause was due to intermittent network connectivity between anchore-engine and the referenced image registry
