### ISSUE TITLE
aevolume_anchore-engine_1 fails with Exit 2

### ISSUE THREAD

**Issue by tarba12** [anchore/anchore-engine#87]
**Is this a request for help?**:

--- Yes

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

<!--
If this is a BUG REPORT, please:
  - Fill in as much of the template below as possible so we can reproduce and understand the issue.
  
I was following link https://github.com/anchore/anchore-engine/wiki to install anchor engine. I did not deviate at any step i just followed every step. But after running sudo docker-compose up -d i see below error. anchore-engine fails to start.

adminadmin@minikube:~/aevolume$ sudo docker-compose ps
WARNING: The PWD variable is not set. Defaulting to a blank string.
          Name                         Command               State     Ports
------------------------------------------------------------------------------
aevolume_anchore-db_1       docker-entrypoint.sh postgres    Up       5432/tcp
aevolume_anchore-engine_1   /bin/sh -c /usr/bin/anchor ...   Exit 2

Sudo docker-compose logs-follow shows compose cannot locate configuration file. In fact i have copied the file in the same directory aevolume/config 

adminadmin@minikube:~/aevolume$ sudo docker-compose logs --follow
WARNING: The PWD variable is not set. Defaulting to a blank string.
Attaching to aevolume_anchore-engine_1, aevolume_anchore-db_1
anchore-engine_1  | [MainThread] [anchore_manager.cli.service/start()] [ERROR] Error: cannot locate configuration file (/config/config.yaml)
anchore-engine_1  |
aevolume_anchore-engine_1 exited with code 2
anchore-db_1      | LOG:  database system was interrupted; last known up at 2018-08-30 06:27:04 UTC
anchore-db_1      | LOG:  database system was not properly shut down; automatic recovery in progress
anchore-db_1      | LOG:  invalid record length at 0/14EE698: wanted 24, got 0
anchore-db_1      | LOG:  redo is not required
anchore-db_1      | LOG:  MultiXact member wraparound protections are now enabled
anchore-db_1      | LOG:  database system is ready to accept connections
anchore-db_1      | LOG:  autovacuum launcher started

<!-- To get version info:
anchore-cli --version
anchore-cli, version 0.2.4

<img width="858" alt="anchor" src="https://user-images.githubusercontent.com/42163415/44895989-46963380-ad14-11e8-9965-80131283e70a.PNG">

**Comment by nurmi** [comment]
Hi @tarba12 ,

Can you supply us with some log output from the engine container?  The best way is to use 

```
docker logs <your_container>
```

and look at the first set of lines - that will help us determine the nature of the exit code

**Comment by tarba12** [comment]
adminadmin@anchor:~/aevolume$ sudo docker-compose ps
WARNING: The PWD variable is not set. Defaulting to a blank string.
          Name                         Command               State     Ports
------------------------------------------------------------------------------
aevolume_anchore-db_1       docker-entrypoint.sh postgres    Up       5432/tcp
aevolume_anchore-engine_1   /bin/sh -c /usr/bin/anchor ...   Exit 2

I see the aevolume_anchore-engile_1 exits immediately after running sudo docker-compose ps

when i do sudo docker ps is see

sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
14155b710696        postgres:9          "docker-entrypoint.s…"   5 days ago          Up 5 days           5432/tcp            aevolume_anchore-db_1

adminadmin@anchor:~/aevolume$ sudo docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                          PORTS               NAMES
01aa5c7527bd        anchore/anchore-engine:latest   "/bin/sh -c /usr/bin…"   5 days ago          Exited (2) About a minute ago                       aevolume_anchore-engine_1
14155b710696        postgres:9                      "docker-entrypoint.s…"   5 days ago          Up 5 days                       5432/tcp            aevolume_anchore-db_1

adminadmin@anchor:~/aevolume$ sudo docker logs 01aa5c7527bd
[MainThread] [anchore_manager.cli.service/start()] [ERROR] Error: cannot locate configuration file (/config/config.yaml)

[MainThread] [anchore_manager.cli.service/start()] [ERROR] Error: cannot locate configuration file (/config/config.yaml)

its strange the logs shows cannot locate the configuration file.  But if you see below the config file is placed in the aevolume folder

adminadmin@anchor:~/aevolume$ ls
config  db  docker-compose.yaml
adminadmin@anchor:~/aevolume$ cd config/
adminadmin@anchor:~/aevolume/config$ ls
config.yaml

**Comment by nurmi** [comment]
hi @tarba12 ,

You're correct in identifying the inability of the engine to access the /config/config.yaml config file as the cause of the engine not coming up cleanly.  It looks like you're using 'sudo' to prefix your commands, and I'm assuming also that sudo was used to run the initial 'docker-compose up -d' command as well.  If this is the case, you may need to review/alter your docker-compose.yaml to replace the volume mount references that use '${PWD}' to either the absolute path to the source volume location, or replace with './' relative path, since I believe that environment variables like PWD can get reset when using sudo.  there are several in the default/stock docker-compose.yaml that we reference in documentation, so they would all need to be changed if this is in fact the issue - for example:

```
    volumes:
     - ${PWD}/config:/config/:Z
```

would become

```
    volumes:
     - ./config:/config/:Z

```
and so on.  Let us know if that addresses the issue!

**Comment by tarba12** [comment]
Thank you this worked. May be you want to update the anchore wiki about this information

**Comment by nurmi** [comment]
Thanks @tarba12 - we'll likely see if we can adjust the example docker-compose.yaml to function better when docker-compose is invoked with sudo, there are a couple of options there for us to explore!
