### ISSUE TITLE
Retry on analysis_failed?

### ISSUE THREAD

**Issue by aurcioli-handy** [anchore/anchore-engine#9]
Is there a way to get the engine to retry analysis for things with status `analysis_failed` ?

**Comment by zhill** [comment]
hi @aurcioli-handy, the does a few retries before entering that state, but once there you can simply re-add the image with a 'force' option. On the cli: 'anchore-cli image add <img> --force' and it will ignore the current state and run the analysis.

**Comment by aurcioli-handy** [comment]
Thanks @zhill
