### ISSUE TITLE
address PRISMA-2021-0020 for next release

### ISSUE THREAD

**Issue by bhearn7** [anchore/anchore-engine#908]
**Version:** 0.9.1

**CVE ID:** PRISMA-2021-0020
**Package Name:** click
**Package Version:** 7.0
**Severity:** medium
**Status:** fixed in 8.0.0

**SBOM Files:**
- `/usr/local/lib/python3.6/site-packages/Click-7.0.dist-info`
- `/usr/local/lib/python3.6/site-packages/click`
- `/usr/local/lib/python3.6/site-packages/clickclick`
- `/usr/local/lib/python3.6/site-packages/botocore/data/iot1click-devices` (probably not related)

**Comment by zhill** [comment]
There is no click v8.0.0 released yet to upgrade to. I don't know what this vuln is so we cannot assess if it is actually impacting or not without at least some description or link to a CVE.

**Comment by zhill** [comment]
Removing the security label until we can get information on what this is. An ID is not sufficient to triage or verify.

**Comment by bhearn7** [comment]
@zhill @nightfurys It appears click-8.0 is out now:
- https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0

**Comment by bhearn7** [comment]
see [other issue](https://github.com/anchore/anchore-cli/issues/167#issuecomment-876767953) for additional context + link to the click issue
