### ISSUE TITLE
Anchore Layer Caching storage deletion.

### ISSUE THREAD

**Issue by prudhvigodithi** [anchore/anchore-engine#914]
**Is this a request for help?**:
yes
---

**Query**
 Hey I have a question about anchor Layer Caching, I have given layer_cache_max_gigabytes option to 10GB, we are using anchore to scan even for the windows images, due to the volume of our registry and when the scan happens, this scratch volume goes beyond 50 Gigs and we are using AWS EFS for this purpose, so if the size goes beyond the declared value 10GB, will the deletion of the extra GB happens from anchore side or we have to delete this scratch volume data periodically?

anchore-cli, version 0.9.0
Engine version v0.9.0

**What happened**:
The Size of the scratch volume goes beyond the declared layer_cache_max_gigabytes size.

**What did you expect to happen**:
Once the size exceeds beyond the declared layer_cache_max_gigabytes size, will the clean up of these layers automatically?

**What docker images are you using**:
Windows, alpine, Debian, dotnet

**Anything else we need to know**:
We are using AWS EFS, bursting mode, will this slow down the scan process?

**Comment by zhill** [comment]
hi @prudhvigodithi , the layer cache will expand to the size needed to download the image, but will then remove layers to get back to the stated max value. This ensures that images can always be analyzed, but the cache itself will never remain larger than the stated value. The cleanup is done after the image analysis is complete, and is performed automatically.

**Comment by prudhvigodithi** [comment]
Hey @zhill, thanks for the update, got cleared now, can you please add this in the docs for future reference?
Thanks

**Comment by zhill** [comment]
I have created a docs issue linked to this one. I'll close this issue since the question was answered and we can track the docs update in the other issue. Thanks @prudhvigodithi
