### ISSUE TITLE
BUG: S3 _check_creds doesn't work if you are not the owner of the S3 bucket

### ISSUE THREAD

**Issue by nyanshak** [anchore/anchore-engine#94]
anchore-cli, version 0.2.4

Name: anchore-engine
Version: 0.2.4

** Problem **

The s3 driver's _check_creds function in anchore_engine/subsys/object_store/drivers/s3.py calls:
```
self.s3_client.get_bucket_location(Bucket=self.bucket_name)
```

This line causes a BadCredentialsError to be raised if you're not the owner of the bucket (for example, you have access via AssumeRole from another account). [AWS Docs](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html) state that:

> To use this implementation of the operation, you must be the bucket owner.

As someone who has access to a bucket but is not the owner, I'm unable to use the s3 driver in anchore.

** Proposed solution **

Instead of calling get_bucket_location, replace do something like (pseudocode):
```
key = "__anchore_s3_key_self_check__{}".format(some_random_string)

try:
    self.put(someUserId, bucket, key, "anchore self-check data")
    data == self.get(someUserId, bucket, key)
    if not data == "anchore self-check data":
        raise SomeException
except:
    # do something here
finally:
    self.delete(someUserId, bucket, key)
```

**Comment by nyanshak** [comment]
I just realized _check_bucket does the same thing, so that would need to be adjusted as well.

**Comment by zhill** [comment]
@nyanshak the archive migration code has a similar check, I can re-use it here for the validity check
