### ISSUE TITLE
 Image Security scanning Licecycle Sample

### ISSUE THREAD

**Issue by jcamu** [anchore/anchore-engine#956]
**Is this a request for help?**:
YES, but to understand, define image security management.
---

There is some sample on how to manage image security notifications ? Done in other entreprise . Best practice.

Ex :
If we add a repo to watch, we have added subcription on vulnerability  update and analyses update.
If there is a new vulnerability issue on the os of all images used for our application.
We will received mails, notifications for every images. It could be a lot.
the same can occur with change of policy.

The solutions is only to purge often to reduce the numbers of possible image?

Or in fact, we should not use notification, only for specfic tagged "production" image for admission controller.

I don't know if you have some sample on how it could be managed.

Regards,

**Comment by zhill** [comment]
Hi @jcamu . In Anchore Engine you can manage subscriptions using the `anchore-cli subscription` command tree. An enabled `vuln_update` subscription will send new vuln notifications for the tag indicated in the subscription. An enabled `policy_eval` subscription will send notification for a change (pass->fail, fail-> pass) of the policy eval status for the given tag. See: https://engine.anchore.io/docs/general/concepts/subscriptions/ for more information on subscriptions.
