### ISSUE TITLE
Regression in 31_file_package_verify analyzer introduced in v0.9.0.

### ISSUE THREAD

**Issue by Vijay-P** [anchore/anchore-engine#965]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT - REGRESSION

**Version of Anchore Engine and Anchore CLI if applicable**:
engine version >= v0.9.0

**What happened**:
In 57d1c30397cd208fd86c01acfdf2357dad845d34, methods were removed from `anchore_engine/analyzers/utils.py` that were used by `anchore_engine/analyzers/modules/31_file_package_verify.py`. This caused the analyzer module in question to fail silently. Later, having mistaken this change to be intentional, `31_file_package_verify.py` was removed in 48dec358afd661378642cb1fffe6cd75002613d1.

**What did you expect to happen**:
Analyzer should be present and functional.

**Resolution Plan**
Map new syft output containing RPM, DPKG, and APK file manifest data into file_package_verify analyzer output format (to be consumed by rest of system).
Related issue in Syft: https://github.com/anchore/syft/issues/371

**Comment by zhill** [comment]
This impacts Engine v0.9.0+

**Comment by zhill** [comment]
This failure is only indicated by a log message in the analyzer service. The data itself is only exposed in the policy engine's "packages" gate via the "verify" trigger. Only users that leverage that specific trigger will be impacted.
