### ISSUE TITLE
Adding image to self-signed registry failed. Tried adding registry as insecure , command won't take credentials eventhough they are correct credentials for private registry. Tried --skip-validate flag and was able to add registry but when tried adding the image to analyze, error is seen. 

### ISSUE THREAD

**Issue by bikashlama541** [anchore/anchore-engine#972]
[anchore@2330fd64fb80 anchore-engine]$ anchore-cli --u admin --p ***** registry add myregistry.com:5000 anchore anchore --insecure
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://myregistry.com:5000,anchore) - exception: cannot access registry using registry version 2 https://myregistry.com:5000:5000/v2/
HTTP Code: 406
Detail: {'error_codes': []}

[anchore@2330fd64fb80 anchore-engine]$ anchore-cli --u admin --p ***** registry add myregistry.com:5000 anchore anchore --insecure
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://myregistry.com:5000,anchore) - exception: cannot access registry using registry version 2 https://myregistry.com:5000/v2/
HTTP Code: 406
Detail: {'error_codes': []}

[anchore@2330fd64fb80 anchore-engine]$ anchore-cli --u admin --p ***** registry add myregistry.com:5000 anchore anchore --insecure --skip-validate
Registry: myregistry.com:5000
Name: myregistry.com:5000
User: anchore
Type: docker_v2
Verify TLS: False
Created: 2021-04-14T16:09:57Z
Updated: 2021-04-14T16:09:57Z

Error: No such command "image".
[anchore@2330fd64fb80 anchore-engine]$ anchore-cli --u admin --p ***** image add nmyregistry.com:5000/ubuntu:18.04
Error: cannot fetch image digest/manifest from registry
**HTTP Code: 400
**Detail: {'error_codes': ['SKOPEO_UNKNOWN_ERROR'], 'raw_exception_message': 'Error encountered in skopeo operation. cmd=/bin/sh -c skopeo   inspect --raw --tls-verify=false --creds "${SKOPUSER}":"${SKOPPASS}" docker://nexus3.mmi.mig.corp:5000/migubuntu:18.04, rc=1, stdout=None, stderr=b\'time="2021-04-14T16:11:10Z" level=fatal msg="Error parsing image name \\\\"docker://myregistry.com:5000/ubuntu:18.04\\\\": error pinging docker registry myregistry.com:5000:5000: Get \\\\"http://myregistry.com:5000:5000/v2/\\\\": EOF"\\n\', error_code=SKOPEO_UNKNOWN_ERROR'}****

[anchore@2330fd64fb80 anchore-engine]$

**Comment by bikashlama541** [comment]
Anchore Engine : v0.9.3 
Private registry : Nexus
Private repo is running with SSL using reverse proxy. 

Docker pull and push from the server hosting anchore works fine.

**Comment by zhill** [comment]
hi @bikashlama541! That output doesn't look like the same ubuntu image, or something isn't quite lining up with your output (maybe due to you redacting/editing things?). Since you've take the good step of trying docker pull, can you also try execing into an anchore container and running the skopeo command the log is indicating directly? With the --debug command you may be able to see what is failing in the skopeo process. It looks like some path or port issues, but need more detail on exactly what skopeo is doing to determine how to fix it.

**Comment by bikashlama541** [comment]
Hi @zhill Thank you for replying. yes I have edited the image output. Trying debug with skopeo I get following output,

anchore@2330fd64fb80 anchore-engine]$ skopeo --debug inspect docker://myregistry.com:5000/ubuntu:18.04
DEBU[0000] reference rewritten from 'myregistry.com:5000/ubuntu:18.04' to 'myregistry.com:5000/ubuntu:18.04' 
DEBU[0000] Trying to access "myregistry.com:5000/ubuntu:18.04" 
DEBU[0000] Credentials not found                        
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  No signature storage configuration found for myregistry.com:5000/ubuntu:18.04 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/nexus3.mmi.mig.corp:5000 
DEBU[0000] GET https://myregistry.com:5000/v2/     
DEBU[0000] Ping https://myregistry.com:5000/v2/ status 404 
DEBU[0000] GET https://myregistry.com:5000/v2/_ping   
DEBU[0000] Ping https://myregistry.com:5000/v2/_ping  status 404 
DEBU[0000] Accessing "myregistry.com:5000:5000/ubuntu:18.04" failed: error pinging docker registry myregistry.com:5000p:5000: invalid status code from registry 404 (Not Found) 
FATA[0000] Error parsing image name "docker://myregistry.com:5000:5000/ubuntu:18.04": error pinging docker registry myregistry.com:5000:5000: invalid status code from registry 404 (Not Found)

And with credentials I am getting this

[anchore@2330fd64fb80 anchore-engine]$ skopeo --debug inspect --creds anchore:anchore docker://myregistry.com:5000/ubuntu:18.04
DEBU[0000] reference rewritten from 'myregistry.com:5000/ubuntu:18.04' to 'myregistry.com:5000/ubuntu:18.04' 
DEBU[0000] Trying to access "myregistry.com:5000/ubuntu:18.04" 
DEBU[0000] Returning credentials from DockerAuthConfig  
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  No signature storage configuration found for myregistry.com:5000/ubuntu:18.04 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/myregistry.com:5000 
DEBU[0000] GET https://myregistry.com:5000/v2/     
DEBU[0000] Ping https://myregistry.com:5000/v2/ status 404 
DEBU[0000] GET https://myregistry.com:5000/v1/_ping 
DEBU[0000] Ping https://myregistry.com:5000/v1/_ping status 404 
DEBU[0000] Accessing "myregistry.com:5000/ubuntu:18.04" failed: error pinging docker registry myregistry.com:5000: invalid status code from registry 404 (Not Found) 
FATA[0000] Error parsing image name "docker://myregistry.com:5000/ubuntu:18.04": error pinging docker registry myregistry.com:5000: invalid status code from registry 404 (Not Found)

Looks like, I need to pass in the cert of the registry to get it done. How do I that ? Do you have any documentation I can follow to resolve this?

**Comment by SudeepParajuli** [comment]
Hy @zhill , I am too facing the similar issue, any updates on this one ?

**Comment by bikashlama541** [comment]
It was my haproxy error, Had to add a routing rule to accept incoming traffic to docker registry V2 api.
