### ISSUE TITLE
Cache mechanism for image vulnerabilities

### ISSUE THREAD

**Issue by nightfurys** [anchore/anchore-engine#979]
Implement a vulnerability report cache manager (refer to policy eval cache manager) to retrieve an existing vulnerability report or generate a new report as necessary. This mechanism backs synchronous policy engine apis and internal use of vulnerability report for policy evaluation. Design the cache key to account for 
- image content 
- vulnerability database 

in order to compute the staleness of the cache. If the cache is stale or missing, the manager should generate a new report using the appropriate scanner

**Comment by zhill** [comment]
Closed by #973
