### ISSUE TITLE
Transform grype vulnerabilities output

### ISSUE THREAD

**Issue by nightfurys** [anchore/anchore-engine#981]
With grype performing vulnerability matching, policy engine will need to transform grype output into it's own format.  Policy-engine report format isn't all that great but that can be changed independently of this effort. All the information required to support pe response is not available from grype, missing attributes have been identified and tickets filed

CVSS scores (multiples and vendor scores) - https://github.com/anchore/grype/issues/287
Vendor advisory (wont fix and SAs) - https://github.com/anchore/grype/issues/276
NVD link - https://github.com/anchore/grype/issues/189
Feed group - https://github.com/anchore/grype/issues/283
Formatted string representation for CPEs - https://github.com/anchore/grype/issues/268
Image digest - https://github.com/anchore/grype/issues/269
grype-db checksum - https://github.com/anchore/grype/issues/270

**Comment by zhill** [comment]
Closed by #973
