### ISSUE TITLE
How to fix the docker image CVEs?

### ISSUE THREAD

**Issue by archwolf118** [anchore/anchore-engine#987]
I found some CVEs of ubuntu16.04 image through anchore-engine.
Like openssl-1.0.2g, I need to upgrade it to openssl-1.1.1g.
But after I upgrade the openssl, I commit a new image.
But the new image also have the same CVE of openssl.
I wonder how to fix the docker image CVEs?

**Comment by zhill** [comment]
Hi @archwolf118 , are you sure you analyzed the new image? Depending on how you "committed" the new image it may not have been pushed to a registry or scanned by anchore-engine again.

**Comment by Vijay-P** [comment]
No response from author. Closing.
