### ISSUE TITLE
Twisted connection timeout causes large image analysis to fail

### ISSUE THREAD

**Issue by blang9238** [anchore/anchore-engine#990]
On a large image analysis, the image analysis fails with logs indicating that the policy engine -> catalog image load task is timing out (causing fail back to the analyzer, causing image to reach "analysis failed" state).

There is a global service side timeout on all twisted connections set to 60 seconds, with a 15 second abort final timeout. 75 seconds total. If any reason a client -> end of read connections takes longer than 75 seconds, the server will kill the connection.

Any reason that impacts the total time from connection open to the end of the chunk loop on the policy engine being > 75 seconds will cause this behavior. Ordinarily, providing the Anchore deployment with sufficient resources can eliminate this, however, for cases where that does not address the issue users will experience connections being closed prior to image load task completing.

Suggest exposing an optional configuration within Anchore to change / bump up the default timeout when needed.

**Comment by blang9238** [comment]
It's also important to note that there were significant performance improvements with changing the requests.iter_content chunk size from 800KB to 16MB/32MB for these HTTP GETs/POSTs in https://github.com/anchore/anchore-engine/blob/master/anchore_engine/clients/services/http.py#L174

default chunk size (8192*100) -- errors out throwing connection timeout exception [here](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/clients/services/http.py#L181) before getting all the data via twisted default 60/15seconds timeout

**Comment by mathrock** [comment]
#994 is related and is why we were never logging the ConnectionResetError when twisted timed out the analysis_data GET.

**Comment by zhill** [comment]
Closed by #996
